<?php
/**
 * 404.php — Kamps Professional Roofing
 * Custom 404 error page
 * Generated by Page One Insights
 */
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/functions.php';

$pageTitle       = "Page Not Found | Kamps Professional Roofing";
$pageDescription = "The page you're looking for doesn't exist. Return to the Kamps Professional Roofing homepage or contact us for roofing services in Grand Rapids, MI.";
$pageKeywords    = "kamps professional roofing, roofing grand rapids mi";
$canonicalUrl    = SITE_URL . '/404';
$ogImage         = LOGO_URL;
$currentPage     = "";
$schemaMarkup    = "";

// Set HTTP 404 response code
http_response_code(404);

include $_SERVER['DOCUMENT_ROOT'] . '/includes/head.php';
include $_SERVER['DOCUMENT_ROOT'] . '/includes/header.php';
?>
<!-- noindex override -->
<meta name="robots" content="noindex, follow">

<style>
/* ── 404 Page Styles ──────────────────────────────────────── */
.error-section {
  padding: 8rem 0;
  text-align: center;
  background: var(--color-light);
  min-height: calc(100vh - 80px);
  display: flex;
  align-items: center;
}
.error-number {
  font-family: var(--font-heading);
  font-size: clamp(5rem, 15vw, 8rem);
  font-weight: 800;
  color: var(--color-accent);
  line-height: 1;
  margin-bottom: 1rem;
  letter-spacing: -0.04em;
}
.error-section h1 {
  font-family: var(--font-heading);
  font-size: clamp(1.5rem, 4vw, 2.2rem);
  font-weight: 800;
  color: var(--color-dark);
  letter-spacing: -0.02em;
  margin-bottom: 1rem;
}
.error-section > .container > p {
  color: var(--color-gray);
  font-size: 1.05rem;
  max-width: 500px;
  margin: 0 auto 2.5rem;
  line-height: 1.6;
}
.error-btn-row {
  display: flex;
  gap: 1rem;
  justify-content: center;
  flex-wrap: wrap;
  margin-bottom: 3rem;
}
.popular-pages {
  background: white;
  border-radius: var(--radius-lg);
  padding: 2rem;
  max-width: 500px;
  margin: 0 auto;
  box-shadow: var(--shadow-card);
  text-align: left;
}
.popular-pages h3 {
  font-family: var(--font-heading);
  font-size: 1rem;
  font-weight: 700;
  color: var(--color-dark);
  margin-bottom: 1rem;
  text-align: center;
  letter-spacing: 0.04em;
  text-transform: uppercase;
  font-size: 0.85rem;
  color: var(--color-gray);
}
.popular-pages ul {
  list-style: none;
  margin: 0;
  padding: 0;
}
.popular-pages li {
  padding: 0.6rem 0;
  border-bottom: 1px solid var(--color-gray-light);
}
.popular-pages li:last-child { border-bottom: none; }
.popular-pages a {
  color: var(--color-primary);
  font-weight: 600;
  font-size: 0.9rem;
  text-decoration: none;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  transition: color 0.2s ease, gap 0.2s ease;
}
.popular-pages a:hover { color: var(--color-accent); gap: 0.75rem; }
.popular-pages a::before {
  content: '→';
  color: var(--color-accent);
  font-size: 0.8rem;
}
</style>

<main id="main-content">

  <section class="error-section" aria-labelledby="error-heading">
    <div class="container-narrow">
      <div class="error-number" aria-hidden="true">404</div>
      <h1 id="error-heading">This Page Has Moved On</h1>
      <p>The page you're looking for doesn't exist or has been moved. Try one of the popular links below, or head back to the homepage.</p>

      <div class="error-btn-row">
        <a href="/" class="btn btn-primary">Back to Home</a>
        <a href="/services" class="btn btn-primary">Our Services</a>
        <a href="/contact" class="btn btn-accent">Get a Free Estimate</a>
      </div>

      <div class="popular-pages">
        <h3>Popular Pages</h3>
        <ul>
          <li><a href="/services/roof-replacement">Roof Replacement Grand Rapids</a></li>
          <li><a href="/services/emergency-roof-repair">Emergency Roof Repair</a></li>
          <li><a href="/services/storm-damage-roof-repair">Storm Damage Repair</a></li>
          <li><a href="/services/gutter-installation">Gutter Installation</a></li>
          <li><a href="/service-areas">Service Areas</a></li>
          <li><a href="/about">About Daniel Kamps</a></li>
          <li><a href="/contact">Contact Us</a></li>
        </ul>
      </div>
    </div>
  </section>

</main>

<?php include $_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php'; ?>
