<?php
/**
 * about.php — Kamps Professional Roofing
 * Company story, owner bio, values, certifications, and CTA
 * Generated by Page One Insights
 */
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/functions.php';

$pageTitle       = "About Kamps Professional Roofing | Grand Rapids, MI Roofer";
$pageDescription = "Kamps Professional Roofing is led by Daniel Kamps with 30+ years of roofing experience in Grand Rapids, MI. Learn our story, values, and commitment to West Michigan homeowners.";
$pageKeywords    = "about kamps professional roofing, daniel kamps roofer grand rapids, grand rapids roofing company history, west michigan roofing contractor";
$canonicalUrl    = SITE_URL . '/about';
$ogImage         = "https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914928-504379882_122166753146552346_6128510493070599625_n.jpg";
$currentPage     = "about";
$heroImage       = "https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914928-504379882_122166753146552346_6128510493070599625_n.jpg";

$breadcrumbs = [
    ['name' => 'Home',  'url' => '/'],
    ['name' => 'About', 'url' => '/about'],
];

$schemaMarkup = '[' . breadcrumb_schema($breadcrumbs) . ']';

include $_SERVER['DOCUMENT_ROOT'] . '/includes/head.php';
include $_SERVER['DOCUMENT_ROOT'] . '/includes/header.php';
?>

<style>
/* ── About — Page-specific styles ────────────────────────── */
.inner-hero {
  position: relative;
  min-height: 55vh;
  display: flex;
  align-items: center;
  background-size: cover;
  background-position: center top;
  padding-top: 80px;
}
.inner-hero::before {
  content: '';
  position: absolute;
  inset: 0;
  background: linear-gradient(135deg, rgba(26,43,60,0.88) 0%, rgba(26,43,60,0.5) 60%, rgba(6,182,212,0.2) 100%);
  z-index: 1;
}
.inner-hero .container { position: relative; z-index: 2; }
.inner-hero .hero-content { text-align: left; max-width: 700px; }

.breadcrumb-nav {
  background: var(--color-light);
  padding: 0.75rem 0;
  border-bottom: 1px solid var(--color-gray-light);
}
.breadcrumb {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  list-style: none;
  font-size: 0.875rem;
}
.breadcrumb-item + .breadcrumb-item::before { content: '/'; color: var(--color-gray); }
.breadcrumb-item a { color: var(--color-primary); }
.breadcrumb-item.active { color: var(--color-gray); }

/* ── Ticker ────────────────────────────────────────────────── */
.ticker-strip {
  background: var(--color-primary);
  padding: 0.75rem 0;
  overflow: hidden;
  white-space: nowrap;
}
.ticker-track {
  display: inline-flex;
  animation: ticker-scroll 30s linear infinite;
}
.ticker-track:hover { animation-play-state: paused; }
.ticker-item {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0 2rem;
  color: white;
  font-size: 0.8rem;
  font-weight: 600;
  letter-spacing: 0.1em;
  text-transform: uppercase;
}
.ticker-sep { color: var(--color-accent); }
@keyframes ticker-scroll {
  from { transform: translateX(0); }
  to   { transform: translateX(-50%); }
}

/* ── Shared section components ────────────────────────────── */
.eyebrow {
  display: inline-block;
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--color-accent);
  background: rgba(6,182,212,0.1);
  padding: 0.35rem 1rem;
  border-radius: 99px;
  margin-bottom: 1rem;
}
.section-title {
  font-family: var(--font-heading);
  font-size: clamp(1.8rem, 4vw, 2.8rem);
  font-weight: 800;
  color: var(--color-dark);
  letter-spacing: -0.02em;
  line-height: 1.15;
  margin-bottom: 1rem;
  text-wrap: balance;
}
.section-subtitle {
  color: var(--color-gray);
  font-size: 1.05rem;
  line-height: 1.6;
  max-width: 65ch;
}

/* ── Story Split ───────────────────────────────────────────── */
.story-section {
  padding: var(--space-16) 0;
  background: var(--color-white);
}
.story-split {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 4rem;
  align-items: center;
}
@media (max-width: 767px) {
  .story-split { grid-template-columns: 1fr; gap: 2.5rem; }
  .story-image-wrap { order: -1; }
}
.story-content { }
.story-content p {
  color: var(--color-gray);
  font-size: 1rem;
  line-height: 1.75;
  margin-bottom: 1.25rem;
  max-width: 65ch;
}
.story-content p:last-child { margin-bottom: 0; }

.story-image-wrap {
  position: relative;
}
.story-image-frame {
  border-radius: var(--radius-lg);
  overflow: hidden;
  box-shadow: 0 8px 28px rgba(0,0,0,0.16);
  aspect-ratio: 4/5;
  position: relative;
}
.story-image-frame img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
  filter: saturate(0.9);
}
.stat-overlay {
  position: absolute;
  bottom: -1.5rem;
  left: -1.5rem;
  background: var(--color-primary);
  color: white;
  padding: 1.5rem 2rem;
  border-radius: var(--radius-lg);
  box-shadow: 0 4px 16px rgba(0,0,0,0.2);
  display: flex;
  gap: 2rem;
  z-index: 2;
}
@media (max-width: 767px) {
  .stat-overlay { left: 0; bottom: -1rem; padding: 1rem 1.5rem; gap: 1.5rem; }
}
.stat-overlay-item { text-align: center; }
.stat-overlay-num {
  font-family: var(--font-heading);
  font-size: 2rem;
  font-weight: 800;
  color: var(--color-accent);
  line-height: 1;
  display: block;
}
.stat-overlay-label {
  font-size: 0.7rem;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: rgba(255,255,255,0.7);
  margin-top: 0.25rem;
  display: block;
}

/* ── Values Cards ──────────────────────────────────────────── */
.values-section {
  padding: var(--space-16) 0;
  background: var(--color-light);
}
.values-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 1.5rem;
  margin-top: 3rem;
}
@media (max-width: 1023px) { .values-grid { grid-template-columns: 1fr 1fr; } }
@media (max-width: 767px)  { .values-grid { grid-template-columns: 1fr; } }
.value-card {
  background: var(--color-white);
  border-radius: var(--radius-lg);
  padding: 2.5rem 2rem;
  box-shadow: var(--shadow-card);
  border-top: 4px solid var(--color-accent);
  transition: transform 0.25s ease, box-shadow 0.25s ease;
}
.value-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 8px 28px rgba(0,0,0,0.14);
}
.value-icon {
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  margin-bottom: 1.5rem;
}
.value-card h3 {
  font-family: var(--font-heading);
  font-size: 1.2rem;
  font-weight: 700;
  color: var(--color-dark);
  margin-bottom: 0.75rem;
}
.value-card p {
  font-size: 0.95rem;
  color: var(--color-gray);
  line-height: 1.65;
  max-width: 65ch;
}

/* ── CTA Banner ────────────────────────────────────────────── */
.cta-banner {
  position: relative;
  background: linear-gradient(135deg, var(--color-primary) 0%, #0f1c2b 100%);
  padding: 4rem 0;
  overflow: hidden;
  text-align: center;
}
.cta-banner::before {
  content: '';
  position: absolute;
  inset: 0;
  opacity: 0.04;
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E");
  pointer-events: none;
}
.cta-banner .container { position: relative; z-index: 1; }
.cta-banner h2 {
  font-family: var(--font-heading);
  font-size: clamp(1.8rem, 4vw, 2.6rem);
  font-weight: 800;
  color: white;
  letter-spacing: -0.02em;
  margin-bottom: 1rem;
}
.cta-banner p {
  color: rgba(255,255,255,0.8);
  font-size: 1.05rem;
  max-width: 600px;
  margin: 0 auto 2rem;
  line-height: 1.6;
}
.cta-phone {
  font-family: var(--font-heading);
  font-size: 1.8rem;
  font-weight: 800;
  color: var(--color-accent);
  letter-spacing: -0.02em;
  display: block;
  margin-top: 1rem;
}
.cta-phone a { color: inherit; text-decoration: none; }
.cta-phone a:hover { color: white; }

/* ── Stats Section ─────────────────────────────────────────── */
.stats-section {
  padding: var(--space-16) 0;
  background: var(--color-primary);
}
.stats-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 1.5rem;
  text-align: center;
}
@media (max-width: 1023px) { .stats-grid { grid-template-columns: repeat(2, 1fr); } }
@media (max-width: 767px)  { .stats-grid { grid-template-columns: repeat(2, 1fr); } }
.stat-item {
  padding: 2rem 1rem;
  border-radius: var(--radius-lg);
  background: rgba(255,255,255,0.05);
}
.stat-num {
  font-family: var(--font-heading);
  font-size: clamp(2.5rem, 5vw, 3.5rem);
  font-weight: 800;
  color: var(--color-accent);
  line-height: 1;
  display: block;
  margin-bottom: 0.5rem;
  letter-spacing: -0.02em;
}
.stat-label {
  font-size: 0.85rem;
  font-weight: 600;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: rgba(255,255,255,0.75);
}

/* ── Credentials Section ───────────────────────────────────── */
.credentials-section {
  padding: var(--space-16) 0;
  background: var(--color-light);
}
.credentials-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 1.5rem;
  margin-top: 3rem;
}
@media (max-width: 1023px) { .credentials-grid { grid-template-columns: repeat(2, 1fr); } }
@media (max-width: 767px)  { .credentials-grid { grid-template-columns: 1fr; } }
.credential-item {
  display: flex;
  gap: 1rem;
  align-items: flex-start;
  background: var(--color-white);
  border-radius: var(--radius-lg);
  padding: 1.5rem;
  box-shadow: var(--shadow-card);
}
.credential-icon {
  width: 44px;
  height: 44px;
  border-radius: var(--radius-md);
  background: rgba(6,182,212,0.1);
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--color-accent);
  flex-shrink: 0;
}
.credential-item h4 {
  font-family: var(--font-heading);
  font-size: 1rem;
  font-weight: 700;
  color: var(--color-dark);
  margin-bottom: 0.35rem;
}
.credential-item p {
  font-size: 0.875rem;
  color: var(--color-gray);
  line-height: 1.5;
  margin: 0;
  max-width: 65ch;
}

/* ── Closing CTA ───────────────────────────────────────────── */
.closing-cta {
  background: var(--color-dark);
  padding: 5rem 0;
  text-align: center;
}
.closing-cta h2 {
  font-family: var(--font-heading);
  font-size: clamp(1.8rem, 4vw, 2.8rem);
  font-weight: 800;
  color: white;
  letter-spacing: -0.02em;
  margin-bottom: 1rem;
}
.closing-cta p {
  color: rgba(255,255,255,0.7);
  font-size: 1.05rem;
  max-width: 560px;
  margin: 0 auto 2rem;
  line-height: 1.6;
}

/* Schema markup for Organization / Person (inline) */
</style>

<!-- Organization + Person schema (separate from breadcrumb) -->
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "Kamps Professional Roofing",
  "url": "<?php echo SITE_URL; ?>",
  "logo": "<?php echo LOGO_URL; ?>",
  "description": "Kamps Professional Roofing is a full-service roofing contractor in Grand Rapids, MI, led by Daniel Kamps with 30+ years of experience.",
  "address": {
    "@type": "PostalAddress",
    "addressLocality": "Grand Rapids",
    "addressRegion": "MI",
    "postalCode": "49525",
    "addressCountry": "US"
  },
  "areaServed": "West Michigan",
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "4.9",
    "reviewCount": "87",
    "bestRating": "5",
    "worstRating": "1"
  }
}
</script>
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Person",
  "name": "Daniel Kamps",
  "jobTitle": "Owner & Lead Roofer",
  "worksFor": {
    "@type": "Organization",
    "name": "Kamps Professional Roofing"
  },
  "description": "Daniel Kamps has been roofing in West Michigan since the early 1990s, building Kamps Professional Roofing into one of Grand Rapids' most recognized exterior contractors.",
  "address": {
    "@type": "PostalAddress",
    "addressLocality": "Grand Rapids",
    "addressRegion": "MI",
    "postalCode": "49525",
    "addressCountry": "US"
  }
}
</script>

<main id="main-content">

  <!-- ── Inner Hero ─────────────────────────────────────────── -->
  <section class="inner-hero"
    style="background-image: url('https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914928-504379882_122166753146552346_6128510493070599625_n.jpg');"
    aria-label="About page hero">
    <div class="container">
      <div class="hero-content">
        <span class="eyebrow" style="margin-bottom:1rem;display:inline-block;">Our Story</span>
        <h1 style="font-family:var(--font-heading);font-size:clamp(2.5rem,6vw,4.5rem);font-weight:800;letter-spacing:-0.02em;line-height:1.1;color:white;margin-bottom:1rem;text-wrap:balance;">
          About Kamps<br>
          <span style="background:linear-gradient(90deg,#06b6d4,#38bdf8);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;">Professional Roofing</span>
        </h1>
        <p style="font-size:1.15rem;color:rgba(255,255,255,0.85);max-width:560px;line-height:1.6;margin-bottom:2rem;">
          30+ years protecting Grand Rapids homes — roof by roof, relationship by relationship.
        </p>
        <div style="display:flex;gap:1rem;flex-wrap:wrap;">
          <a href="/contact" class="btn btn-accent btn-lg">Get Your Free Estimate</a>
          <a href="/services" class="btn btn-outline-white btn-lg">View All Services</a>
        </div>
      </div>
    </div>
  </section>

  <!-- ── Breadcrumb ─────────────────────────────────────────── -->
  <?php echo breadcrumb_nav($breadcrumbs); ?>

  <!-- ── Ticker Strip ───────────────────────────────────────── -->
  <div class="ticker-strip" aria-hidden="true">
    <div class="ticker-track">
      <span class="ticker-item">30+ Years in West Michigan <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Family-Operated <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">1,000+ Roofs Completed <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Licensed &amp; Insured <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">4.9★ Average Rating <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Grand Rapids, MI <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Free Estimates <span class="ticker-sep">✦</span></span>
      <!-- duplicate -->
      <span class="ticker-item">30+ Years in West Michigan <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Family-Operated <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">1,000+ Roofs Completed <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Licensed &amp; Insured <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">4.9★ Average Rating <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Grand Rapids, MI <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Free Estimates <span class="ticker-sep">✦</span></span>
    </div>
  </div>

  <!-- ── Company Story ──────────────────────────────────────── -->
  <section class="story-section" aria-labelledby="story-heading">
    <div class="container">
      <div class="story-split">

        <!-- Content -->
        <div class="story-content" data-animate>
          <span class="eyebrow">How We Started</span>
          <h2 class="section-title" id="story-heading">Built in Grand Rapids. One Roof at a Time.</h2>

          <p>Daniel Kamps picked up his first roofing hammer in the early 1990s, working on residential projects across West Michigan's neighborhoods — Eastown, Heritage Hill, Cascade, Forest Hills. He was a kid who learned the job from the ground up: staging, carrying bundles, nailing shingles in July heat and October cold.</p>

          <p>By the mid-90s, Daniel had started running his own jobs. The business grew the old-fashioned way — a homeowner would call because their neighbor recommended him. No ads, no billboards. Just work that held up and a crew that showed respect for the property they were on. That referral-first reputation became the foundation Kamps Professional Roofing is still built on today.</p>

          <p>Daniel personally oversees every project. He's not in an office reviewing paperwork while strangers work on your home. He's the one walking your roof during the estimate, answering your questions directly, and checking the finished work before his crew packs up. When something comes up — and in roofing, something always comes up — you're talking to the person who can make the call.</p>

          <p>Today, Kamps serves a 100-mile radius from Grand Rapids, covering the entire West Michigan region. The business is still family-operated, still built on referrals, and still doing things the way they worked in 1993: show up when you say you will, do the work right, and stand behind it.</p>
        </div>

        <!-- Image -->
        <div class="story-image-wrap" data-animate>
          <div class="story-image-frame">
            <picture>
              <source srcset="https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914928-504379882_122166753146552346_6128510493070599625_n.jpg" type="image/jpeg">
              <img
                src="https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914928-504379882_122166753146552346_6128510493070599625_n.jpg"
                alt="Daniel Kamps, owner of Kamps Professional Roofing, Grand Rapids MI roofing contractor"
                width="600"
                height="750"
                loading="lazy"
              >
            </picture>
          </div>
          <div class="stat-overlay">
            <div class="stat-overlay-item">
              <span class="stat-overlay-num">30+</span>
              <span class="stat-overlay-label">Years Experience</span>
            </div>
            <div class="stat-overlay-item">
              <span class="stat-overlay-num" style="font-size:1.1rem;letter-spacing:0;">Licensed<br>&amp; Insured</span>
              <span class="stat-overlay-label">Michigan State</span>
            </div>
          </div>
        </div>

      </div>
    </div>
  </section>

  <!-- ── Values ─────────────────────────────────────────────── -->
  <section class="values-section" aria-labelledby="values-heading">
    <div class="container">
      <div style="text-align:center;" data-animate>
        <span class="eyebrow">What We Stand On</span>
        <h2 class="section-title" id="values-heading">Three Values. Every Job.</h2>
        <p class="section-subtitle" style="margin-inline:auto;">These aren't mission statement words. They're what Daniel and his crew are held to on every project, every time.</p>
      </div>

      <div class="values-grid">

        <div class="value-card" data-animate>
          <div class="value-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>
          </div>
          <h3>Honesty First</h3>
          <p>Daniel will tell you when your roof has five good years left and doesn't need replacement. A lot of contractors won't. But homeowners who get straight answers come back — and they send their neighbors. That's been the business model since day one.</p>
        </div>

        <div class="value-card" data-animate>
          <div class="value-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
          </div>
          <h3>Craft Over Speed</h3>
          <p>Rushing a roof to get to the next job is how you end up getting called back in eighteen months with a leak nobody can explain. Kamps crews take the time that the job actually takes — because a roof is not something a homeowner should have to think about again for decades.</p>
        </div>

        <div class="value-card" data-animate>
          <div class="value-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="20 6 9 17 4 12"></polyline></svg>
          </div>
          <h3>Accountability</h3>
          <p>If something isn't right, Daniel fixes it. No runaround, no blame-the-material, no waiting six weeks to get on the schedule. When a job leaves this crew's hands, it's finished — and if it ever isn't, the phone gets answered and the problem gets solved.</p>
        </div>

      </div>
    </div>
  </section>

  <!-- ── Mid-page CTA (CTA #2) ──────────────────────────────── -->
  <section class="cta-banner" aria-label="Get a free roofing estimate from Daniel Kamps">
    <div class="container">
      <span class="eyebrow" style="background:rgba(255,255,255,0.1);color:white;margin-bottom:1.5rem;display:inline-block;">Talk to Daniel Directly</span>
      <h2>See the Difference an Experienced Owner Makes</h2>
      <p>When you schedule an estimate with Kamps, you're meeting Daniel — not a salesperson. He'll inspect your roof, answer every question, and give you a written estimate at no cost and no pressure.</p>
      <div style="display:flex;gap:1rem;justify-content:center;flex-wrap:wrap;margin-bottom:1.5rem;">
        <a href="/contact" class="btn btn-accent btn-lg">Schedule a Free Estimate</a>
        <a href="/services" class="btn btn-outline-white btn-lg">View All Services</a>
      </div>
      <?php if (!empty(SITE_PHONE)): ?>
      <span class="cta-phone"><a href="tel:<?php echo preg_replace('/[^0-9+]/', '', SITE_PHONE); ?>"><?php echo htmlspecialchars(SITE_PHONE_DISPLAY); ?></a></span>
      <?php endif; ?>
    </div>
  </section>

  <!-- ── By the Numbers ─────────────────────────────────────── -->
  <section class="stats-section" aria-labelledby="stats-heading">
    <div class="container">
      <div style="text-align:center;margin-bottom:3rem;" data-animate>
        <span class="eyebrow" style="background:rgba(6,182,212,0.2);color:var(--color-accent);">By the Numbers</span>
        <h2 class="section-title" id="stats-heading" style="color:white;">30 Years. Real Results.</h2>
      </div>
      <div class="stats-grid">
        <div class="stat-item" data-animate>
          <span class="stat-num">30+</span>
          <span class="stat-label">Years in Business</span>
        </div>
        <div class="stat-item" data-animate>
          <span class="stat-num">1,000+</span>
          <span class="stat-label">Roofs Replaced</span>
        </div>
        <div class="stat-item" data-animate>
          <span class="stat-num">4.9★</span>
          <span class="stat-label">Average Rating</span>
        </div>
        <div class="stat-item" data-animate>
          <span class="stat-num">100mi</span>
          <span class="stat-label">West Michigan Service Radius</span>
        </div>
      </div>
    </div>
  </section>

  <!-- ── Credentials ────────────────────────────────────────── -->
  <section class="credentials-section" aria-labelledby="credentials-heading">
    <div class="container">
      <div style="text-align:center;" data-animate>
        <span class="eyebrow">Credentials &amp; Certifications</span>
        <h2 class="section-title" id="credentials-heading">Fully Licensed. Properly Insured. Manufacturer-Certified.</h2>
        <p class="section-subtitle" style="margin-inline:auto;margin-bottom:0;">What's behind the work — before Daniel sets foot on your roof.</p>
      </div>

      <div class="credentials-grid">

        <div class="credential-item" data-animate>
          <div class="credential-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>
          </div>
          <div>
            <h4>Michigan State Licensed</h4>
            <p>Fully licensed residential roofing contractor in the State of Michigan — verified, current, and in good standing.</p>
          </div>
        </div>

        <div class="credential-item" data-animate>
          <div class="credential-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2"></rect><polyline points="9 11 12 14 22 4"></polyline></svg>
          </div>
          <div>
            <h4>Fully Insured</h4>
            <p>General liability and workers' compensation coverage — protecting your home and everyone on it throughout the project.</p>
          </div>
        </div>

        <div class="credential-item" data-animate>
          <div class="credential-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="8" r="6"></circle><path d="M15.477 12.89 17 22l-5-3-5 3 1.523-9.11"></path></svg>
          </div>
          <div>
            <h4>GAF Certified Materials</h4>
            <p>Kamps installs GAF roofing systems, unlocking enhanced warranty coverage available only through certified installers.</p>
          </div>
        </div>

        <div class="credential-item" data-animate>
          <div class="credential-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg>
          </div>
          <div>
            <h4>Owens Corning Preferred</h4>
            <p>Preferred installer status with Owens Corning — giving customers access to extended material warranties on qualifying projects.</p>
          </div>
        </div>

        <div class="credential-item" data-animate>
          <div class="credential-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
          </div>
          <div>
            <h4>BBB Member</h4>
            <p>Accredited member of the Better Business Bureau — maintaining a clear complaint record and a commitment to resolution.</p>
          </div>
        </div>

        <div class="credential-item" data-animate>
          <div class="credential-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path></svg>
          </div>
          <div>
            <h4>30+ Years West Michigan Experience</h4>
            <p>Three decades installing roofs across Grand Rapids and surrounding communities — that's a level of local climate knowledge no certification can replace.</p>
          </div>
        </div>

      </div>
    </div>
  </section>

  <!-- ── Closing CTA (CTA #3) ───────────────────────────────── -->
  <section class="closing-cta" aria-label="Schedule your free estimate with Kamps">
    <div class="container">
      <span class="eyebrow" style="background:rgba(6,182,212,0.15);color:var(--color-accent);margin-bottom:1.5rem;display:inline-block;">Ready to Get Started?</span>
      <h2>Your Roof Deserves Someone Who Knows What They're Doing</h2>
      <p>Three decades in West Michigan roofing. Every estimate is free. No obligation, no pressure — just a straight answer from an experienced roofer who's seen every situation this climate throws at a house.</p>
      <div style="display:flex;gap:1rem;justify-content:center;flex-wrap:wrap;margin-bottom:1.5rem;">
        <a href="/contact" class="btn btn-accent btn-lg">Request a Free Estimate</a>
        <a href="/services" class="btn btn-outline-white btn-lg">Explore Our Services</a>
      </div>
      <?php if (!empty(SITE_PHONE)): ?>
      <p style="color:rgba(255,255,255,0.5);font-size:0.9rem;">Prefer to call? <a href="tel:<?php echo preg_replace('/[^0-9+]/', '', SITE_PHONE); ?>" style="color:var(--color-accent);font-weight:700;"><?php echo htmlspecialchars(SITE_PHONE_DISPLAY); ?></a></p>
      <?php endif; ?>
    </div>
  </section>

</main>

<?php include $_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php'; ?>
