<?php
/**
 * contact.php — Kamps Professional Roofing
 * Contact form, business info, map placeholder, and estimate FAQs
 * Generated by Page One Insights
 */
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/functions.php';

$pageTitle       = "Contact Kamps Roofing | Free Roofing Estimate Grand Rapids MI";
$pageDescription = "Contact Kamps Professional Roofing in Grand Rapids, MI for a free roofing estimate. Call, email, or fill out our online form. Same-week appointments available.";
$pageKeywords    = "contact kamps professional roofing, free roofing estimate grand rapids mi, roofing estimate grand rapids, roof inspection grand rapids";
$canonicalUrl    = SITE_URL . '/contact';
$ogImage         = "https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914928-504418539_122166753074552346_1599975162091961710_n.jpg";
$currentPage     = "contact";
$heroImage       = "https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914928-504418539_122166753074552346_1599975162091961710_n.jpg";
$useSwiper       = false;

$breadcrumbs = [
    ['name' => 'Home',    'url' => '/'],
    ['name' => 'Contact', 'url' => '/contact'],
];

$schemaMarkup = '[' . breadcrumb_schema($breadcrumbs) . ']';

include $_SERVER['DOCUMENT_ROOT'] . '/includes/head.php';
include $_SERVER['DOCUMENT_ROOT'] . '/includes/header.php';
?>

<style>
/* ── Contact — Page-specific styles ──────────────────────── */
.inner-hero {
  position: relative;
  min-height: 55vh;
  display: flex;
  align-items: center;
  background-size: cover;
  background-position: center;
  padding-top: 80px;
}
.inner-hero::before {
  content: '';
  position: absolute;
  inset: 0;
  background: linear-gradient(135deg, rgba(26,43,60,0.88) 0%, rgba(26,43,60,0.55) 60%, rgba(6,182,212,0.15) 100%);
  z-index: 1;
}
.inner-hero .container { position: relative; z-index: 2; }
.inner-hero .hero-content { text-align: left; max-width: 700px; }

.breadcrumb-nav {
  background: var(--color-light);
  padding: 0.75rem 0;
  border-bottom: 1px solid var(--color-gray-light);
}
.breadcrumb {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  list-style: none;
  font-size: 0.875rem;
}
.breadcrumb-item + .breadcrumb-item::before { content: '/'; color: var(--color-gray); }
.breadcrumb-item a { color: var(--color-primary); }
.breadcrumb-item.active { color: var(--color-gray); }

.eyebrow {
  display: inline-block;
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--color-accent);
  background: rgba(6,182,212,0.1);
  padding: 0.35rem 1rem;
  border-radius: 99px;
  margin-bottom: 1rem;
}
.section-title {
  font-family: var(--font-heading);
  font-size: clamp(1.8rem, 4vw, 2.8rem);
  font-weight: 800;
  color: var(--color-dark);
  letter-spacing: -0.02em;
  line-height: 1.15;
  margin-bottom: 1rem;
  text-wrap: balance;
}

/* ── Contact Layout ────────────────────────────────────────── */
.contact-section {
  padding: var(--space-16) 0;
  background: var(--color-white);
}
.contact-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 3.5rem;
  align-items: start;
}
@media (max-width: 767px) {
  .contact-grid { grid-template-columns: 1fr; gap: 2.5rem; }
}

/* ── Form ──────────────────────────────────────────────────── */
.contact-form-wrap {
  background: var(--color-white);
  border-radius: var(--radius-lg);
  padding: 2.5rem;
  box-shadow: var(--shadow-card);
  border: 1px solid var(--color-gray-light);
}
.contact-form-wrap h2 {
  font-family: var(--font-heading);
  font-size: 1.5rem;
  font-weight: 800;
  color: var(--color-dark);
  margin-bottom: 0.5rem;
}
.contact-form-wrap > p {
  color: var(--color-gray);
  font-size: 0.9rem;
  margin-bottom: 2rem;
  max-width: 65ch;
}
.form-group {
  position: relative;
  margin-bottom: 1.5rem;
}
.form-group input,
.form-group textarea {
  width: 100%;
  padding: 1rem 1rem 0.5rem;
  border: 2px solid var(--color-gray-light);
  border-radius: var(--radius-md);
  font-family: var(--font-body);
  font-size: 1rem;
  background: var(--color-white);
  transition: border-color 0.2s ease, box-shadow 0.2s ease;
  outline: none;
  color: var(--color-dark);
  line-height: 1.5;
}
.form-group textarea {
  min-height: 120px;
  resize: vertical;
  padding-top: 1.25rem;
}
.form-group input:focus,
.form-group textarea:focus {
  border-color: var(--color-accent);
  box-shadow: 0 0 0 3px rgba(6,182,212,0.12);
}
.form-group label {
  position: absolute;
  left: 1rem;
  top: 1rem;
  font-size: 1rem;
  color: var(--color-gray);
  transition: all 0.2s ease;
  pointer-events: none;
  background: white;
  padding: 0 0.25rem;
  line-height: 1;
}
.form-group input:focus ~ label,
.form-group input:not(:placeholder-shown) ~ label,
.form-group textarea:focus ~ label,
.form-group textarea:not(:placeholder-shown) ~ label {
  top: -0.6rem;
  font-size: 0.75rem;
  color: var(--color-accent);
  font-weight: 600;
}

/* Select group (non-floating label for accessibility) */
.form-group-select label {
  display: block;
  font-size: 0.8rem;
  font-weight: 600;
  color: var(--color-gray);
  margin-bottom: 0.4rem;
  letter-spacing: 0.04em;
  text-transform: uppercase;
}
.form-group-select select {
  width: 100%;
  padding: 0.9rem 1rem;
  border: 2px solid var(--color-gray-light);
  border-radius: var(--radius-md);
  font-family: var(--font-body);
  font-size: 1rem;
  background: var(--color-white);
  color: var(--color-dark);
  transition: border-color 0.2s ease, box-shadow 0.2s ease;
  outline: none;
  appearance: none;
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%23888' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='6 9 12 15 18 9'%3E%3C/polyline%3E%3C/svg%3E");
  background-repeat: no-repeat;
  background-position: right 1rem center;
}
.form-group-select select:focus {
  border-color: var(--color-accent);
  box-shadow: 0 0 0 3px rgba(6,182,212,0.12);
}

/* ── Business Info Panel ───────────────────────────────────── */
.business-info {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}
.business-info h2 {
  font-family: var(--font-heading);
  font-size: 1.5rem;
  font-weight: 800;
  color: var(--color-dark);
  margin-bottom: 0.25rem;
}
.business-info > p {
  color: var(--color-gray);
  font-size: 0.95rem;
  line-height: 1.6;
  max-width: 65ch;
}
.info-item {
  display: flex;
  gap: 1rem;
  align-items: flex-start;
  padding: 1.25rem;
  background: var(--color-light);
  border-radius: var(--radius-md);
  border-left: 3px solid var(--color-accent);
}
.info-icon {
  width: 38px;
  height: 38px;
  border-radius: var(--radius-md);
  background: var(--color-primary);
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  flex-shrink: 0;
}
.info-item h4 {
  font-family: var(--font-heading);
  font-size: 0.85rem;
  font-weight: 700;
  letter-spacing: 0.06em;
  text-transform: uppercase;
  color: var(--color-gray);
  margin-bottom: 0.25rem;
}
.info-item p, .info-item a {
  font-size: 1rem;
  font-weight: 600;
  color: var(--color-dark);
  text-decoration: none;
  line-height: 1.5;
}
.info-item a:hover { color: var(--color-accent); }

/* ── FAQ Section ───────────────────────────────────────────── */
.faq-section {
  padding: var(--space-16) 0;
  background: var(--color-light);
}
.faq-section .section-title { text-align: center; }
.faq-section .eyebrow { display: block; text-align: center; }
.faq-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 1.5rem;
  margin-top: 3rem;
}
@media (max-width: 1023px) { .faq-grid { grid-template-columns: 1fr; } }
.faq-item {
  background: var(--color-white);
  border-radius: var(--radius-lg);
  padding: 2rem;
  box-shadow: var(--shadow-card);
}
.faq-item h3 {
  font-family: var(--font-heading);
  font-size: 1.05rem;
  font-weight: 700;
  color: var(--color-dark);
  margin-bottom: 0.75rem;
  line-height: 1.4;
}
.faq-item p {
  font-size: 0.925rem;
  color: var(--color-gray);
  line-height: 1.65;
  max-width: 65ch;
}

/* ── Closing CTA ───────────────────────────────────────────── */
.closing-cta {
  background: var(--color-dark);
  padding: 5rem 0;
  text-align: center;
}
.closing-cta h2 {
  font-family: var(--font-heading);
  font-size: clamp(1.8rem, 4vw, 2.8rem);
  font-weight: 800;
  color: white;
  letter-spacing: -0.02em;
  margin-bottom: 1rem;
}
.closing-cta p {
  color: rgba(255,255,255,0.7);
  font-size: 1.05rem;
  max-width: 540px;
  margin: 0 auto 2rem;
  line-height: 1.6;
}
</style>

<main id="main-content">

  <!-- ── Inner Hero ─────────────────────────────────────────── -->
  <section class="inner-hero"
    style="background-image: url('https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914928-504418539_122166753074552346_1599975162091961710_n.jpg');"
    aria-label="Contact page hero">
    <div class="container">
      <div class="hero-content">
        <span class="eyebrow" style="margin-bottom:1rem;display:inline-block;">No Obligation</span>
        <h1 style="font-family:var(--font-heading);font-size:clamp(2.5rem,6vw,4.5rem);font-weight:800;letter-spacing:-0.02em;line-height:1.1;color:white;margin-bottom:1rem;text-wrap:balance;">
          Get Your Free<br>
          <span style="background:linear-gradient(90deg,#06b6d4,#38bdf8);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;">Roofing Estimate</span>
        </h1>
        <p style="font-size:1.15rem;color:rgba(255,255,255,0.85);max-width:560px;line-height:1.6;">
          Same-week appointments available in Grand Rapids and all of West Michigan. Written, itemized estimate — no surprises.
        </p>
      </div>
    </div>
  </section>

  <!-- ── Breadcrumb ─────────────────────────────────────────── -->
  <?php echo breadcrumb_nav($breadcrumbs); ?>

  <!-- ── Contact Form + Business Info ───────────────────────── -->
  <section class="contact-section" aria-labelledby="contact-heading">
    <div class="container">
      <div class="contact-grid">

        <!-- LEFT: Contact Form -->
        <div class="contact-form-wrap" data-animate>
          <h2 id="contact-heading">Request Your Free Estimate</h2>
          <p>Fill out the form and Daniel will follow up within 1 business day to confirm your appointment.</p>

          <form action="<?php echo FORM_ACTION; ?>" method="POST" class="contact-form" novalidate>
            <?php echo form_hidden_fields(SITE_URL . '/thank-you', 'Kamps Professional Roofing — New Website Inquiry'); ?>

            <!-- Full Name -->
            <div class="form-group">
              <input type="text" id="name" name="name" placeholder=" " required autocomplete="name">
              <label for="name">Full Name *</label>
            </div>

            <!-- Phone -->
            <div class="form-group">
              <input type="tel" id="phone" name="phone" placeholder=" " autocomplete="tel">
              <label for="phone">Phone Number</label>
            </div>

            <!-- Email -->
            <div class="form-group">
              <input type="email" id="email" name="email" placeholder=" " required autocomplete="email">
              <label for="email">Email Address *</label>
            </div>

            <!-- Service -->
            <div class="form-group form-group-select">
              <label for="service">Service Needed</label>
              <select id="service" name="service">
                <option value="" disabled selected>Select a service...</option>
                <option value="Roof Replacement">Roof Replacement</option>
                <option value="Roof Repair">Roof Repair</option>
                <option value="Emergency Roof Repair">Emergency Roof Repair</option>
                <option value="Storm Damage Repair">Storm Damage Repair</option>
                <option value="Roof Inspection">Roof Inspection</option>
                <option value="Gutter Services">Gutter Services</option>
                <option value="Siding Services">Siding Services</option>
                <option value="Other">Other / Not Sure</option>
              </select>
            </div>

            <!-- Message -->
            <div class="form-group">
              <textarea id="message" name="message" placeholder=" " rows="5"></textarea>
              <label for="message">Tell Us About Your Project</label>
            </div>

            <button type="submit" class="btn btn-primary btn-lg" style="width:100%;justify-content:center;">
              Send My Request
            </button>

            <p style="font-size:0.8rem;color:var(--color-gray);margin-top:1rem;text-align:center;">
              We respond within 1 business day. No spam, ever.
            </p>
          </form>
        </div>

        <!-- RIGHT: Business Info -->
        <div class="business-info" data-animate>
          <div>
            <span class="eyebrow" style="display:inline-block;margin-bottom:0.75rem;">Reach Us Directly</span>
            <h2>Kamps Professional Roofing</h2>
            <p>Daniel and his team serve Grand Rapids and all of West Michigan. Prefer to call? Pick up the phone — someone will answer.</p>
          </div>

          <?php if (!empty(SITE_PHONE)): ?>
          <div class="info-item">
            <div class="info-icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 13a19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 3.6 2.18h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L7.91 9.91a16 16 0 0 0 6 6l.91-.91a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 17z"></path></svg>
            </div>
            <div>
              <h4>Phone</h4>
              <a href="tel:<?php echo preg_replace('/[^0-9+]/', '', SITE_PHONE); ?>"><?php echo htmlspecialchars(SITE_PHONE_DISPLAY); ?></a>
            </div>
          </div>
          <?php endif; ?>

          <?php if (!empty(SITE_EMAIL)): ?>
          <div class="info-item">
            <div class="info-icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
            </div>
            <div>
              <h4>Email</h4>
              <a href="mailto:<?php echo htmlspecialchars(SITE_EMAIL); ?>"><?php echo htmlspecialchars(SITE_EMAIL); ?></a>
            </div>
          </div>
          <?php endif; ?>

          <div class="info-item">
            <div class="info-icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
            </div>
            <div>
              <h4>Location</h4>
              <p>Grand Rapids, MI 49525<br><span style="font-size:0.85rem;color:var(--color-gray);font-weight:400;">Serving all of West Michigan</span></p>
            </div>
          </div>

          <div class="info-item">
            <div class="info-icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
            </div>
            <div>
              <h4>Business Hours</h4>
              <p>Mon–Fri: 7:00 AM – 6:00 PM<br>Saturday: 8:00 AM – 4:00 PM<br><span style="font-size:0.85rem;color:var(--color-gray);font-weight:400;">Emergency calls accepted 24/7</span></p>
            </div>
          </div>

          <!-- Map Placeholder -->
          <div style="width:100%;height:260px;background:var(--color-light);border-radius:var(--radius-lg);display:flex;align-items:center;justify-content:center;border:2px solid var(--color-gray-light);">
            <p style="color:var(--color-gray);text-align:center;line-height:1.6;">
              <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="var(--color-accent)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" style="display:block;margin:0 auto 0.5rem;"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
              <strong style="color:var(--color-dark);">Kamps Professional Roofing</strong><br>
              Grand Rapids, MI 49525<br>
              <span style="font-size:0.8rem;">Serving West Michigan within 100 miles</span>
            </p>
          </div>

        </div>

      </div>
    </div>
  </section>

  <!-- ── Estimate Process FAQs ──────────────────────────────── -->
  <section class="faq-section" aria-labelledby="faq-heading">
    <div class="container">
      <span class="eyebrow">Common Questions</span>
      <h2 class="section-title" id="faq-heading">About the Estimate Process</h2>

      <div class="faq-grid">

        <div class="faq-item" data-animate>
          <h3>Is the estimate really free — no strings attached?</h3>
          <p>Yes, completely free. Daniel comes out, inspects your roof, and gives you a written estimate with no obligation. If you decide not to move forward, that's fine — no pressure, no follow-up sales calls. He'd rather earn your trust than chase a sale.</p>
        </div>

        <div class="faq-item" data-animate>
          <h3>How soon can you come out for an estimate?</h3>
          <p>Most estimates are scheduled within the same week of your call. If you're dealing with an active leak or storm damage, call directly — emergency inspections are typically handled within 24 hours to prevent water damage from spreading.</p>
        </div>

        <div class="faq-item" data-animate>
          <h3>What should I have ready before the estimate?</h3>
          <p>If you've already noticed visible damage, photos help. If your claim is storm-related, having your homeowner's insurance info on hand speeds up the process — Daniel can document the damage in a format that directly supports your claim. Otherwise, just let him take a look.</p>
        </div>

      </div>
    </div>
  </section>

  <!-- ── Closing CTA ────────────────────────────────────────── -->
  <section class="closing-cta" aria-label="Contact Kamps to get started">
    <div class="container">
      <span class="eyebrow" style="background:rgba(6,182,212,0.15);color:var(--color-accent);margin-bottom:1.5rem;display:inline-block;">Same-Week Appointments</span>
      <h2>Your Estimate Costs Nothing.<br>Waiting Might.</h2>
      <p>Small roof issues become expensive repairs when water gets into the decking. Let Daniel take a look this week — written estimate, no obligation.</p>
      <div style="display:flex;gap:1rem;justify-content:center;flex-wrap:wrap;margin-bottom:1.5rem;">
        <a href="#contact-heading" class="btn btn-accent btn-lg">Fill Out the Form Above</a>
        <?php if (!empty(SITE_PHONE)): ?>
        <a href="tel:<?php echo preg_replace('/[^0-9+]/', '', SITE_PHONE); ?>" class="btn btn-outline-white btn-lg">Call <?php echo htmlspecialchars(SITE_PHONE_DISPLAY); ?></a>
        <?php else: ?>
        <a href="/services" class="btn btn-outline-white btn-lg">View Our Services</a>
        <?php endif; ?>
      </div>
    </div>
  </section>

</main>

<?php include $_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php'; ?>
