<?php
/**
 * service-area.php — Kamps Professional Roofing
 * Service areas listing page — Grand Rapids and West Michigan communities
 * Generated by Page One Insights
 */
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/functions.php';

$pageTitle       = "Roofing Services Grand Rapids & West Michigan | Kamps";
$pageDescription = "Kamps Professional Roofing serves Grand Rapids and all of West Michigan. Roof replacement, repair, gutters & siding in Kentwood, Wyoming, Grandville, Rockford, Lowell, and beyond.";
$pageKeywords    = "roofing service area grand rapids mi, west michigan roofing contractor, kentwood roofing, wyoming mi roofer, rockford mi roofing, grandville roofing";
$canonicalUrl    = SITE_URL . '/service-areas';
$ogImage         = "https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914924-2022-05-22.webp";
$currentPage     = "service-areas";
$heroImage       = "https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914924-2022-05-22.webp";

$breadcrumbs = [
    ['name' => 'Home',          'url' => '/'],
    ['name' => 'Service Areas', 'url' => '/service-areas'],
];

$schemaMarkup = '[' . breadcrumb_schema($breadcrumbs) . ']';

include $_SERVER['DOCUMENT_ROOT'] . '/includes/head.php';
include $_SERVER['DOCUMENT_ROOT'] . '/includes/header.php';
?>

<style>
/* ── Service Area — Page-specific styles ─────────────────── */
.breadcrumb-nav {
  background: var(--color-light);
  padding: 0.75rem 0;
  border-bottom: 1px solid var(--color-gray-light);
}
.breadcrumb {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  list-style: none;
  font-size: 0.875rem;
}
.breadcrumb-item + .breadcrumb-item::before { content: '/'; color: var(--color-gray); }
.breadcrumb-item a { color: var(--color-primary); }
.breadcrumb-item.active { color: var(--color-gray); }

/* ── Ticker ────────────────────────────────────────────────── */
.ticker-strip {
  background: var(--color-primary);
  padding: 0.75rem 0;
  overflow: hidden;
  white-space: nowrap;
}
.ticker-track {
  display: inline-flex;
  animation: ticker-scroll 32s linear infinite;
}
.ticker-track:hover { animation-play-state: paused; }
.ticker-item {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0 2rem;
  color: white;
  font-size: 0.8rem;
  font-weight: 600;
  letter-spacing: 0.1em;
  text-transform: uppercase;
}
.ticker-sep { color: var(--color-accent); }
@keyframes ticker-scroll {
  from { transform: translateX(0); }
  to   { transform: translateX(-50%); }
}

/* ── Shared ────────────────────────────────────────────────── */
.eyebrow {
  display: inline-block;
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--color-accent);
  background: rgba(6,182,212,0.1);
  padding: 0.35rem 1rem;
  border-radius: 99px;
  margin-bottom: 1rem;
}
.section-title {
  font-family: var(--font-heading);
  font-size: clamp(1.8rem, 4vw, 2.8rem);
  font-weight: 800;
  color: var(--color-dark);
  letter-spacing: -0.02em;
  line-height: 1.15;
  margin-bottom: 1rem;
  text-wrap: balance;
}

/* ── Intro ─────────────────────────────────────────────────── */
.intro-section {
  padding: var(--space-16) 0;
  background: var(--color-white);
}
.intro-split {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 4rem;
  align-items: start;
}
@media (max-width: 767px) {
  .intro-split { grid-template-columns: 1fr; gap: 2rem; }
}
.intro-split p {
  color: var(--color-gray);
  font-size: 1rem;
  line-height: 1.75;
  max-width: 65ch;
  margin-bottom: 1.25rem;
}
.intro-split p:last-child { margin-bottom: 0; }

/* ── Grand Rapids Feature Section ─────────────────────────── */
.gr-section {
  padding: var(--space-16) 0;
  background: var(--color-light);
}
.gr-feature {
  background: var(--color-white);
  border-radius: var(--radius-lg);
  overflow: hidden;
  box-shadow: var(--shadow-card);
  display: grid;
  grid-template-columns: 1fr 1fr;
}
@media (max-width: 767px) {
  .gr-feature { grid-template-columns: 1fr; }
}
.gr-feature-image {
  aspect-ratio: 4/3;
  overflow: hidden;
}
.gr-feature-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
.gr-feature-content {
  padding: 3rem 2.5rem;
}
.gr-feature-content h2 {
  font-family: var(--font-heading);
  font-size: clamp(1.4rem, 3vw, 2rem);
  font-weight: 800;
  color: var(--color-dark);
  letter-spacing: -0.02em;
  margin-bottom: 1rem;
}
.gr-feature-content p {
  font-size: 0.95rem;
  color: var(--color-gray);
  line-height: 1.7;
  max-width: 65ch;
  margin-bottom: 1.25rem;
}
.gr-feature-content p:last-of-type { margin-bottom: 1.5rem; }
.neighborhood-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-top: 1rem;
}
.neighborhood-tag {
  background: rgba(6,182,212,0.1);
  color: var(--color-primary);
  font-size: 0.8rem;
  font-weight: 600;
  padding: 0.3rem 0.75rem;
  border-radius: 99px;
  border: 1px solid rgba(6,182,212,0.2);
}

/* ── Area Cards Grid ───────────────────────────────────────── */
.areas-section {
  padding: var(--space-16) 0;
  background: var(--color-white);
}
.areas-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 1.25rem;
  margin-top: 3rem;
}
@media (max-width: 767px) {
  .areas-grid { grid-template-columns: 1fr; }
}
.area-card {
  background: var(--color-white);
  border-radius: var(--radius-lg);
  padding: 1.5rem;
  box-shadow: var(--shadow-card);
  border-top: 4px solid var(--color-accent);
  transition: transform 0.25s ease, box-shadow 0.25s ease;
}
.area-card:hover {
  transform: translateY(-4px);
  box-shadow: 0 8px 28px rgba(0,0,0,0.14);
}
.area-card h3 {
  font-family: var(--font-heading);
  font-size: 1.15rem;
  font-weight: 700;
  color: var(--color-dark);
  margin-bottom: 0.5rem;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}
.area-card h3 svg { color: var(--color-accent); flex-shrink: 0; }
.area-card p {
  color: var(--color-gray);
  font-size: 0.875rem;
  line-height: 1.6;
  margin-bottom: 1rem;
  max-width: 65ch;
}
.area-card a {
  color: var(--color-primary);
  font-weight: 700;
  font-size: 0.875rem;
  text-decoration: none;
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
  transition: gap 0.2s ease;
}
.area-card a:hover { gap: 0.6rem; color: var(--color-accent); }

/* ── CTA Banner ────────────────────────────────────────────── */
.cta-banner {
  position: relative;
  background: linear-gradient(135deg, var(--color-primary) 0%, #0f1c2b 100%);
  padding: 4rem 0;
  overflow: hidden;
  text-align: center;
}
.cta-banner::before {
  content: '';
  position: absolute;
  inset: 0;
  opacity: 0.04;
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)'/%3E%3C/svg%3E");
  pointer-events: none;
}
.cta-banner .container { position: relative; z-index: 1; }
.cta-banner h2 {
  font-family: var(--font-heading);
  font-size: clamp(1.8rem, 4vw, 2.6rem);
  font-weight: 800;
  color: white;
  letter-spacing: -0.02em;
  margin-bottom: 1rem;
}
.cta-banner p {
  color: rgba(255,255,255,0.8);
  font-size: 1.05rem;
  max-width: 600px;
  margin: 0 auto 2rem;
  line-height: 1.6;
}
.cta-phone {
  font-family: var(--font-heading);
  font-size: 1.8rem;
  font-weight: 800;
  color: var(--color-accent);
  letter-spacing: -0.02em;
  display: block;
  margin-top: 1rem;
}
.cta-phone a { color: inherit; text-decoration: none; }
.cta-phone a:hover { color: white; }

</style>

<main id="main-content">

  <!-- ── Inner Hero ─────────────────────────────────────────── -->
  <section class="hero hero-inner"
    style="background-image: url('https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914924-2022-05-22.webp');"
    aria-label="Service areas page hero">
    <div class="hero-overlay" aria-hidden="true"></div>
    <div class="container">
      <div class="hero-content">
        <span class="eyebrow" style="margin-bottom:1rem;display:inline-block;">West Michigan</span>
        <h1 style="font-family:var(--font-heading);font-size:clamp(2.2rem,5vw,4rem);font-weight:800;letter-spacing:-0.02em;line-height:1.1;color:white;margin-bottom:1rem;text-wrap:balance;">
          Roofing Services in Grand Rapids<br>
          <span style="background:linear-gradient(90deg,#06b6d4,#38bdf8);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;">&amp; Surrounding West Michigan Communities</span>
        </h1>
        <p style="font-size:1.1rem;color:rgba(255,255,255,0.85);max-width:600px;line-height:1.6;margin-bottom:2rem;">
          From Forest Hills to Holland — if you're within 100 miles of Grand Rapids, Kamps Professional Roofing comes to you.
        </p>
        <div style="display:flex;gap:1rem;flex-wrap:wrap;">
          <a href="/contact" class="btn btn-accent btn-lg">Get a Free Estimate</a>
          <a href="/services" class="btn btn-outline-white btn-lg">View All Services</a>
        </div>
      </div>
    </div>
  </section>

  <!-- ── Breadcrumb ─────────────────────────────────────────── -->
  <?php echo breadcrumb_nav($breadcrumbs); ?>

  <!-- ── Ticker Strip ───────────────────────────────────────── -->
  <div class="ticker-strip" aria-hidden="true">
    <div class="ticker-track">
      <span class="ticker-item">Grand Rapids <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Kentwood <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Wyoming <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Grandville <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Rockford <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Lowell <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Ada <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Holland <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Hudsonville <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Byron Center <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Jenison <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Caledonia <span class="ticker-sep">✦</span></span>
      <!-- duplicate -->
      <span class="ticker-item">Grand Rapids <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Kentwood <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Wyoming <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Grandville <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Rockford <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Lowell <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Ada <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Holland <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Hudsonville <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Byron Center <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Jenison <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Caledonia <span class="ticker-sep">✦</span></span>
    </div>
  </div>

  <!-- ── Service Coverage Intro ─────────────────────────────── -->
  <section class="intro-section" aria-labelledby="intro-heading">
    <div class="container">
      <div class="intro-split">
        <div data-animate>
          <span class="eyebrow">Coverage Area</span>
          <h2 class="section-title" id="intro-heading">One Crew. 100 Miles of West Michigan.</h2>
          <p>Kamps Professional Roofing is based in Grand Rapids but the work takes us across the full West Michigan region. Daniel has been on roofs in every kind of neighborhood this area has — from older Heritage Hill Victorians to newer construction in Byron Center and Caledonia.</p>
          <p>The 100-mile service radius isn't a marketing line. It reflects three decades of real project history across Kent, Ottawa, Allegan, and Ionia counties. If you're in West Michigan and your roof needs attention, we come to you.</p>
        </div>
        <div data-animate>
          <p style="color:var(--color-gray);font-size:1rem;line-height:1.75;margin-bottom:1.25rem;max-width:65ch;">West Michigan's climate is demanding on roofing systems — heavy lake-effect snow from Lake Michigan, freeze-thaw cycles that stress flashings and gutters, and spring storm seasons that bring hail and wind damage every year. Daniel knows exactly how these conditions affect the materials he works with, which is why Kamps roofs hold up differently than a contractor flying in from another region.</p>
          <p style="color:var(--color-gray);font-size:1rem;line-height:1.75;max-width:65ch;">Every estimate is scheduled at your convenience, and Daniel handles the inspection personally — no junior assessors or subcontracted evaluators. You get a straight answer about what your roof actually needs, along with a written estimate that holds.</p>
          <a href="/contact" class="btn btn-primary" style="margin-top:1.5rem;display:inline-flex;">Schedule a Free Estimate</a>
        </div>
      </div>
    </div>
  </section>

  <!-- ── Grand Rapids Feature ───────────────────────────────── -->
  <section class="gr-section" aria-labelledby="gr-heading">
    <div class="container">
      <div class="gr-feature" data-animate>
        <div class="gr-feature-image">
          <picture>
            <source srcset="https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914924-2022-05-22.webp" type="image/webp">
            <img
              src="https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914924-2022-05-22.webp"
              alt="Roof replacement in progress in Grand Rapids Michigan by Kamps Professional Roofing"
              width="700"
              height="525"
              loading="lazy"
            >
          </picture>
        </div>
        <div class="gr-feature-content">
          <span class="eyebrow">Primary Service Area</span>
          <h2 id="gr-heading">Grand Rapids, MI</h2>
          <p>Grand Rapids is where Kamps Professional Roofing was built — literally. Daniel started his roofing career working on homes in this city in the early 1990s, and Grand Rapids still makes up the majority of Kamps' annual project volume. If you're a Grand Rapids homeowner, you're in the area Daniel knows roof by roof.</p>
          <p>The neighborhoods Kamps serves most frequently in Grand Rapids include Eastown, Heritage Hill, Forest Hills, Cascade, Knapp's Corner, and the Northeast Side. Whether your home was built in 1910 or 2010, Daniel has seen its roof type before and knows what it takes to do the job right.</p>
          <div>
            <p style="font-size:0.8rem;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;color:var(--color-gray);margin-bottom:0.5rem;">Neighborhoods Served</p>
            <div class="neighborhood-tags">
              <span class="neighborhood-tag">Eastown</span>
              <span class="neighborhood-tag">Heritage Hill</span>
              <span class="neighborhood-tag">Forest Hills</span>
              <span class="neighborhood-tag">Cascade</span>
              <span class="neighborhood-tag">Knapp's Corner</span>
              <span class="neighborhood-tag">Northeast Side</span>
              <span class="neighborhood-tag">West Side</span>
              <span class="neighborhood-tag">Garfield Park</span>
            </div>
          </div>
          <a href="/contact" class="btn btn-primary" style="margin-top:2rem;display:inline-flex;">Get a Free Estimate in Grand Rapids</a>
        </div>
      </div>
    </div>
  </section>

  <!-- ── Mid-page CTA (CTA #2) ──────────────────────────────── -->
  <section class="cta-banner" aria-label="Free roofing estimates across West Michigan">
    <div class="container">
      <span class="eyebrow" style="background:rgba(255,255,255,0.1);color:white;margin-bottom:1.5rem;display:inline-block;">100-Mile Service Area</span>
      <h2>Not Sure If You're in Our Coverage Area?</h2>
      <p>Call or fill out the form — if you're in West Michigan, there's a strong chance we've already worked on a roof near yours. Free estimates include the drive.</p>
      <div style="display:flex;gap:1rem;justify-content:center;flex-wrap:wrap;margin-bottom:1.5rem;">
        <a href="/contact" class="btn btn-accent btn-lg">Check Availability</a>
        <a href="/services" class="btn btn-outline-white btn-lg">See All Services</a>
      </div>
      <?php if (!empty(SITE_PHONE)): ?>
      <span class="cta-phone"><a href="tel:<?php echo preg_replace('/[^0-9+]/', '', SITE_PHONE); ?>"><?php echo htmlspecialchars(SITE_PHONE_DISPLAY); ?></a></span>
      <?php endif; ?>
    </div>
  </section>

  <!-- ── Area Cards Grid ────────────────────────────────────── -->
  <section class="areas-section" aria-labelledby="areas-heading">
    <div class="container">
      <div style="text-align:center;" data-animate>
        <span class="eyebrow">West Michigan Communities</span>
        <h2 class="section-title" id="areas-heading">Everywhere Kamps Goes</h2>
        <p style="color:var(--color-gray);font-size:1.05rem;max-width:600px;margin:0 auto 0;">Beyond Grand Rapids, these are the West Michigan communities we serve most regularly — roofs, gutters, siding, and all.</p>
      </div>

      <div class="areas-grid">

        <div class="area-card" data-animate>
          <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
            Kentwood, MI
          </h3>
          <p>A high-volume residential suburb just south of Grand Rapids, Kentwood sees significant hail and wind damage each spring. Kamps handles dozens of Kentwood roofs every storm season, and is familiar with the neighborhood's mix of 1970s–2000s construction.</p>
          <a href="/services">View services for Kentwood →</a>
        </div>

        <div class="area-card" data-animate>
          <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
            Wyoming, MI
          </h3>
          <p>One of Kent County's largest communities, Wyoming has a dense mix of older ranch homes and newer mid-century builds. Many Wyoming roofs are approaching or past replacement age, making proper assessment during the estimate especially important.</p>
          <a href="/services">View services for Wyoming →</a>
        </div>

        <div class="area-card" data-animate>
          <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
            Grandville, MI
          </h3>
          <p>A west-side community with older ranch-style homes that often have low-slope roof sections requiring specific material selection. Kamps serves Grandville regularly and understands the specific drainage challenges common to this area's housing stock.</p>
          <a href="/services">View services for Grandville →</a>
        </div>

        <div class="area-card" data-animate>
          <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
            Rockford, MI
          </h3>
          <p>North of Grand Rapids on the Rogue River, Rockford combines newer residential developments with older established homes. The area's heavily wooded lots mean debris accumulation is a constant issue — Kamps handles both roofing and gutter maintenance calls here year-round.</p>
          <a href="/services">View services for Rockford →</a>
        </div>

        <div class="area-card" data-animate>
          <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
            Lowell, MI
          </h3>
          <p>East of Grand Rapids in the Flat River valley, Lowell homeowners deal with ice dam issues every winter. The area's topography traps cold air, and homes that lack proper attic ventilation are prone to repeated freeze-thaw cycles that destroy flashings and underlayment over time.</p>
          <a href="/services">View services for Lowell →</a>
        </div>

        <div class="area-card" data-animate>
          <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
            Comstock Park, MI
          </h3>
          <p>Just north of Grand Rapids along US-131, Comstock Park is a dense residential community with a wide range of housing ages. Daniel has completed projects here for over two decades and is familiar with the neighborhood's roofing patterns.</p>
          <a href="/services">View services for Comstock Park →</a>
        </div>

        <div class="area-card" data-animate>
          <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
            Ada, MI
          </h3>
          <p>An upscale east-side community where homeowners frequently request premium roofing systems — metal, slate, cedar shake, and architectural shingle upgrades. Kamps brings the same precision to high-end materials that characterizes every job, regardless of budget tier.</p>
          <a href="/services">View services for Ada →</a>
        </div>

        <div class="area-card" data-animate>
          <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
            Byron Center, MI
          </h3>
          <p>A rapidly growing south Grand Rapids suburb with a high concentration of newer construction. Byron Center homeowners often come to Kamps for the first time after storm events — and many become repeat customers for ongoing maintenance and eventual full replacement.</p>
          <a href="/services">View services for Byron Center →</a>
        </div>

        <div class="area-card" data-animate>
          <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
            Caledonia, MI
          </h3>
          <p>Southeast of Grand Rapids with a mix of established subdivisions and rural properties on larger lots. Caledonia roofs frequently have steeper pitches and more complex lines than urban projects — Daniel's experience with custom-pitch work makes this territory well within Kamps' wheelhouse.</p>
          <a href="/services">View services for Caledonia →</a>
        </div>

        <div class="area-card" data-animate>
          <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
            Jenison, MI
          </h3>
          <p>West of Grand Rapids in Ottawa County, Jenison has a large inventory of 1980s–1990s split-level and ranch homes. These roof types commonly develop flashing failures and granule loss on the same aging schedule — Kamps knows the pattern and comes prepared.</p>
          <a href="/services">View services for Jenison →</a>
        </div>

        <div class="area-card" data-animate>
          <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
            Hudsonville, MI
          </h3>
          <p>An Ottawa County community transitioning rapidly from agricultural land to residential development. Hudsonville homeowners in both new and older construction sections call Kamps for roofing, siding, and gutter work near me in Ottawa County.</p>
          <a href="/services">View services for Hudsonville →</a>
        </div>

        <div class="area-card" data-animate>
          <h3>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
            Holland, MI
          </h3>
          <p>On the Lake Michigan shoreline, Holland homes face wind loading and moisture exposure that inland homes don't see as severely. Coastal proximity accelerates granule loss and can compromise adhesive strips on standard shingles — Kamps accounts for these factors during material selection.</p>
          <a href="/services">View services for Holland →</a>
        </div>

      </div>
    </div>
  </section>

  <!-- ── Closing CTA (CTA #3) ───────────────────────────────── -->
  <section class="closing-cta" aria-label="Contact Kamps for your area">
    <div class="container">
      <span class="eyebrow" style="background:rgba(6,182,212,0.15);color:var(--color-accent);margin-bottom:1.5rem;display:inline-block;">Your Town. Our Work.</span>
      <h2>Your Neighborhood Is Probably on This List.</h2>
      <p>If you're in West Michigan and need a roof replaced, repaired, or inspected — Kamps comes to you, no extra charge for the drive. Free, written estimates within the week.</p>
      <div style="display:flex;gap:1rem;justify-content:center;flex-wrap:wrap;margin-bottom:1.5rem;">
        <a href="/contact" class="btn btn-accent btn-lg">Request Your Free Estimate</a>
        <a href="/services" class="btn btn-outline-white btn-lg">See All Services</a>
      </div>
      <?php if (!empty(SITE_PHONE)): ?>
      <p style="color:rgba(255,255,255,0.5);font-size:0.9rem;">Prefer to call? <a href="tel:<?php echo preg_replace('/[^0-9+]/', '', SITE_PHONE); ?>" style="color:var(--color-accent);font-weight:700;"><?php echo htmlspecialchars(SITE_PHONE_DISPLAY); ?></a></p>
      <?php endif; ?>
    </div>
  </section>

</main>

<?php include $_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php'; ?>
