<?php
/**
 * thank-you.php — Kamps Professional Roofing
 * Form submission confirmation page
 * Generated by Page One Insights
 */
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/functions.php';

$pageTitle       = "Thank You — We'll Be in Touch | Kamps Professional Roofing";
$pageDescription = "Your message has been received. Kamps Professional Roofing will contact you within 1 business day to schedule your free estimate.";
$pageKeywords    = "kamps professional roofing thank you, roofing estimate submitted grand rapids";
$canonicalUrl    = SITE_URL . '/thank-you';
$ogImage         = LOGO_URL;
$currentPage     = "";
$schemaMarkup    = "";

include $_SERVER['DOCUMENT_ROOT'] . '/includes/head.php';
include $_SERVER['DOCUMENT_ROOT'] . '/includes/header.php';
?>
<!-- noindex: confirmation page should not be indexed -->
<meta name="robots" content="noindex, follow">

<style>
/* ── Thank-You Page Styles ────────────────────────────────── */
.thankyou-section {
  padding: 8rem 0;
  text-align: center;
  background: var(--color-light);
  min-height: calc(100vh - 80px);
  display: flex;
  align-items: center;
}
.check-circle {
  width: 80px;
  height: 80px;
  border-radius: 50%;
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 2rem;
  box-shadow: 0 8px 28px rgba(6,182,212,0.3);
}
.thankyou-section h1 {
  font-family: var(--font-heading);
  font-size: clamp(2rem, 5vw, 3rem);
  font-weight: 800;
  color: var(--color-dark);
  letter-spacing: -0.02em;
  margin-bottom: 0.75rem;
  text-wrap: balance;
}
.thankyou-subheading {
  font-size: 1.15rem;
  color: var(--color-accent);
  font-weight: 600;
  margin-bottom: 2.5rem;
}

/* ── Next Steps card ───────────────────────────────────────── */
.next-steps {
  background: white;
  border-radius: var(--radius-lg);
  padding: 2.5rem;
  max-width: 560px;
  margin: 0 auto 2.5rem;
  box-shadow: var(--shadow-card);
  text-align: left;
}
.next-steps h2 {
  font-family: var(--font-heading);
  font-size: 1.1rem;
  font-weight: 700;
  color: var(--color-dark);
  margin-bottom: 1.5rem;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  font-size: 0.85rem;
  color: var(--color-gray);
  text-align: center;
}
.next-steps ol {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}
.next-steps li {
  display: flex;
  gap: 1rem;
  align-items: flex-start;
}
.step-num {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  color: white;
  font-family: var(--font-heading);
  font-size: 0.9rem;
  font-weight: 700;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  margin-top: 0.1rem;
}
.step-text {
  font-size: 0.95rem;
  color: var(--color-gray);
  line-height: 1.55;
  max-width: 65ch;
}
.step-text strong { color: var(--color-dark); font-weight: 700; }

/* ── Buttons ───────────────────────────────────────────────── */
.ty-btn-row {
  display: flex;
  gap: 1rem;
  justify-content: center;
  flex-wrap: wrap;
  margin-bottom: 2.5rem;
}

/* ── Direct contact ────────────────────────────────────────── */
.direct-contact {
  background: var(--color-white);
  border-radius: var(--radius-lg);
  padding: 1.5rem 2rem;
  max-width: 400px;
  margin: 0 auto;
  box-shadow: var(--shadow-card);
  border-top: 3px solid var(--color-accent);
}
.direct-contact p {
  font-size: 0.9rem;
  color: var(--color-gray);
  margin-bottom: 0.75rem;
  max-width: 65ch;
}
.direct-contact .contact-links {
  display: flex;
  gap: 1rem;
  justify-content: center;
  flex-wrap: wrap;
}
.direct-contact .contact-links a {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  font-weight: 700;
  font-size: 0.9rem;
  color: var(--color-primary);
  text-decoration: none;
  transition: color 0.2s ease;
}
.direct-contact .contact-links a:hover { color: var(--color-accent); }
</style>

<main id="main-content">

  <section class="thankyou-section" aria-labelledby="ty-heading">
    <div class="container-narrow">

      <!-- Checkmark icon -->
      <div class="check-circle" aria-hidden="true">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>
      </div>

      <h1 id="ty-heading">Your Estimate Request Is In</h1>
      <p class="thankyou-subheading">Daniel will be in touch within 1 business day.</p>

      <!-- What happens next -->
      <div class="next-steps">
        <h2>What Happens Next</h2>
        <ol>
          <li>
            <span class="step-num">1</span>
            <span class="step-text"><strong>We review your request.</strong> Daniel or a team member reads through your submission, including any notes about damage or urgency, and checks your location within the service area.</span>
          </li>
          <li>
            <span class="step-num">2</span>
            <span class="step-text"><strong>Someone calls to confirm your time.</strong> We'll reach out to find a day and window that works for you — usually within the same week, sooner for emergencies.</span>
          </li>
          <li>
            <span class="step-num">3</span>
            <span class="step-text"><strong>We arrive for your free inspection.</strong> Daniel or a senior crew member walks your roof, checks the gutters and any other areas you mentioned, and documents the condition thoroughly.</span>
          </li>
          <li>
            <span class="step-num">4</span>
            <span class="step-text"><strong>You get a written, itemized estimate.</strong> No vague number with a handshake. You'll have a clear breakdown of material costs, scope of work, and timeline — no pressure to sign anything on the spot.</span>
          </li>
        </ol>
      </div>

      <!-- Buttons -->
      <div class="ty-btn-row">
        <a href="/" class="btn btn-primary">Back to Home</a>
        <a href="/services" class="btn btn-accent">View Our Services</a>
      </div>

      <!-- Direct contact if questions arise -->
      <div class="direct-contact">
        <p>Questions before we call? Reach Daniel directly:</p>
        <div class="contact-links">
          <?php if (!empty(SITE_PHONE)): ?>
          <a href="tel:<?php echo preg_replace('/[^0-9+]/', '', SITE_PHONE); ?>">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 13a19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 3.6 2.18h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L7.91 9.91a16 16 0 0 0 6 6l.91-.91a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 17z"></path></svg>
            <?php echo htmlspecialchars(SITE_PHONE_DISPLAY); ?>
          </a>
          <?php endif; ?>
          <?php if (!empty(SITE_EMAIL)): ?>
          <a href="mailto:<?php echo htmlspecialchars(SITE_EMAIL); ?>">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
            <?php echo htmlspecialchars(SITE_EMAIL); ?>
          </a>
          <?php endif; ?>
          <?php if (empty(SITE_PHONE) && empty(SITE_EMAIL)): ?>
          <a href="/contact">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle></svg>
            Contact Page
          </a>
          <?php endif; ?>
        </div>
      </div>

    </div>
  </section>

</main>

<?php include $_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php'; ?>
