<?php
/**
 * cedar-shake-roofing.php — Kamps Professional Roofing
 * Service Page: Cedar Shake Roofing — Grand Rapids, MI
 * Generated by Page One Insights
 */

require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/functions.php';

$breadcrumbs = [
    ['name' => 'Home',     'url' => '/'],
    ['name' => 'Services', 'url' => '/services'],
    ['name' => 'Cedar Shake Roofing', 'url' => '/services/cedar-shake-roofing'],
];

$pageTitle       = "Cedar Shake Roofing Grand Rapids MI | Kamps Roofing";
$pageDescription = "Cedar shake roof installation in Grand Rapids, MI. Western red cedar with proper Michigan moisture management — breathable underlayment, correct spacing, honest maintenance guidance. Free estimates.";
$pageKeywords    = "cedar shake roof grand rapids, wood shake roofing mi, cedar shingle installation grand rapids, natural wood roofing kent county, cedar roof replacement west michigan";
$canonicalUrl    = SITE_URL . '/services/cedar-shake-roofing';
$ogImage         = 'https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470067945_122125377158552346_4518004843740215702_n.jpg';
$heroImage       = 'https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470067945_122125377158552346_4518004843740215702_n.jpg';
$currentPage     = 'services';

$schemaMarkup = '[' . breadcrumb_schema($breadcrumbs) . ',' . service_schema(
    'Cedar Shake Roofing',
    'Professional cedar shake roof installation in Grand Rapids, MI. Western red cedar with breathable underlayment and proper spacing for Michigan\'s moisture-heavy climate. 20–30 year lifespans with proper maintenance.',
    '/services/cedar-shake-roofing'
) . ',' . json_encode([
    '@context'   => 'https://schema.org',
    '@type'      => 'FAQPage',
    'mainEntity' => [
        [
            '@type'          => 'Question',
            'name'           => 'How long do cedar shake roofs last in Michigan?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Cedar shake roofs last 20–30 years in West Michigan with proper maintenance. Michigan\'s moisture and humidity are cedar\'s main adversaries. Roofs with good ventilation, breathable underlayment, and periodic cleaning and treatment (every 5–7 years) reach the longer end of that range.'],
        ],
        [
            '@type'          => 'Question',
            'name'           => 'Are cedar roofs high maintenance?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'More maintenance than asphalt, less than most homeowners expect. Cedar benefits from moss/algae cleaning every 5–7 years and a preservative treatment to prevent rot. Neglected cedar shortens to 10–15 years; properly maintained cedar reaches 25–30. Kamps is upfront about what ownership requires.'],
        ],
        [
            '@type'          => 'Question',
            'name'           => 'How much does cedar shake roofing cost in Grand Rapids?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Cedar shake roofing in Grand Rapids typically runs $10,000–$22,000 for residential installation. Cedar grade, shake style (hand-split vs. sawn), and roof complexity affect cost. A detailed, itemized estimate is provided after Daniel inspects your roof.'],
        ],
    ],
], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ']';

include $_SERVER['DOCUMENT_ROOT'] . '/includes/head.php';
include $_SERVER['DOCUMENT_ROOT'] . '/includes/header.php';
?>

<style>
.process-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.process-step {
  text-align: center;
  padding: 2rem 1.5rem;
  background: var(--color-white);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-card);
}
.process-number {
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  color: white;
  font-family: var(--font-heading);
  font-size: 1.5rem;
  font-weight: 800;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 1rem;
}
.process-step h3 { font-size: 1rem; margin-bottom: 0.5rem; color: var(--color-dark); }
.process-step p { font-size: 0.875rem; color: var(--color-gray); line-height: 1.5; }
.why-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.why-item {
  display: flex;
  gap: 1rem;
  padding: 1.5rem;
  background: var(--color-white);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-card);
}
.why-icon {
  flex-shrink: 0;
  width: 48px;
  height: 48px;
  border-radius: var(--radius-md);
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
}
.why-item h3 { font-size: 1rem; margin-bottom: 0.4rem; color: var(--color-dark); }
.why-item p { font-size: 0.875rem; color: var(--color-gray); line-height: 1.5; }
.faq-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.faq-item {
  background: var(--color-white);
  border-radius: var(--radius-lg);
  padding: 1.75rem;
  box-shadow: var(--shadow-card);
  border-left: 4px solid var(--color-accent);
}
.faq-item h3 { font-size: 1rem; margin-bottom: 0.75rem; color: var(--color-dark); }
.faq-item p { font-size: 0.9rem; color: var(--color-gray); line-height: 1.6; }
@media (max-width: 1023px) {
  .process-grid { grid-template-columns: 1fr 1fr; }
}
@media (max-width: 767px) {
  .why-grid { grid-template-columns: 1fr; }
}
@media (max-width: 480px) {
  .process-grid { grid-template-columns: 1fr; }
}
</style>

<?php echo breadcrumb_nav($breadcrumbs); ?>

<!-- Hero — CTA #1 -->
<section class="hero hero-inner" style="background-image: url('https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470067945_122125377158552346_4518004843740215702_n.jpg');">
  <div class="hero-overlay"></div>
  <div class="container">
    <div class="hero-content">
      <span class="hero-eyebrow">Kamps Professional Roofing</span>
      <h1>Cedar Shake Roofing Grand Rapids, MI</h1>
      <p class="hero-subtitle">Western red cedar installed for Michigan's moisture-heavy climate — breathable underlayment, proper spacing, and honest guidance on what cedar ownership requires.</p>
      <div class="hero-buttons">
        <a href="/contact" class="btn btn-accent btn-lg">Get a Free Estimate</a>
        <?php echo phone_link('btn btn-outline-white btn-lg', 'Call Now'); ?>
      </div>
      <div class="hero-trust">
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg> Licensed &amp; Insured</span>
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg> 30+ Years Experience</span>
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="20 6 9 17 4 12"></polyline></svg> Free Estimates</span>
      </div>
    </div>
  </div>
</section>

<!-- Service Detail -->
<section style="background: var(--color-light); padding: var(--space-16) 0;">
  <div class="container">
    <div class="about-split" data-animate>
      <div class="about-content">
        <div class="section-header" style="text-align:left; margin-bottom: 2rem;">
          <span class="eyebrow">Cedar Shake Roofing in Grand Rapids</span>
          <h2>The Look Homeowners Want — Installed for Michigan's Climate</h2>
        </div>
        <p>Cedar shake is one of the most aesthetically desirable roofing materials available. Western red cedar has a natural warmth, a rustic texture that improves with age, and genuine thermal properties — it insulates roughly twice as effectively as asphalt shingles. A cedar shake roof on a Grand Rapids home costs $10,000–$22,000 and lasts 20–30 years with proper maintenance. Cedar grade (No. 1 Handsplit, Blue Label) and shake style (hand-split vs. sawn vs. tapersplit) affect both appearance and cost, and Daniel walks you through each option during the estimate.</p>
        <p>The honest challenge with cedar in West Michigan: moisture is its adversary, and this region has plenty of it. Most cedar roofs that fail early weren't installed with Michigan's humidity and rainfall in mind. The critical factors are breathable underlayment — not standard 15# felt, which traps moisture under cedar and accelerates rot — proper shake spacing for air circulation, and adequate attic ventilation. These details add a few hours to installation but add years to lifespan.</p>
        <p>Daniel Kamps is direct about cedar maintenance requirements before any project begins. Cedar benefits from moss and algae cleaning every 5–7 years and a preservative treatment to prevent rot. Neglected cedar shortens to 10–15 years; properly maintained cedar reaches 25–30. If you want a completely hands-off roof, he'll tell you that and point you toward metal or architectural shingles instead. Hand-split cedar shakes also have natural interlocking properties and significant weight, giving them strong wind resistance in West Michigan weather systems.</p>
        <p>Fire-treated Class A cedar shake is available and sometimes required by HOAs or insurance carriers in the Grand Rapids area. Kamps confirms your requirements before ordering material — there are no surprises after the cedar is on the roof. Stainless steel or hot-dipped galvanized fasteners are used on every cedar job, because standard galvanized nails corrode under cedar's natural oils and Michigan's humidity, causing unsightly rust staining and premature fastener failure.</p>
        <p style="font-size: 0.8rem; color: var(--color-gray);">Last Updated: <?php echo date('F Y'); ?></p>
      </div>
      <div class="about-image">
        <picture>
          <img src="https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470067945_122125377158552346_4518004843740215702_n.jpg" alt="Cedar shake roof installation on Grand Rapids Michigan home by Kamps Professional Roofing" width="600" height="450" loading="lazy" style="border-radius: var(--radius-lg); width: 100%; object-fit: cover;">
        </picture>
      </div>
    </div>
  </div>
</section>

<!-- Why Choose Kamps -->
<section style="padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">Why Kamps</span>
      <h2>Cedar Installation Built for West Michigan's Humidity</h2>
    </div>
    <div class="why-grid">
      <div class="why-item">
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>
        </div>
        <div>
          <h3>Breathable Installation Systems</h3>
          <p>Kamps uses breathable underlayment on every cedar job — not standard felt. This is the single most important factor in cedar longevity in Michigan's climate. It adds cost to the job and years to the roof.</p>
        </div>
      </div>
      <div class="why-item">
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
        </div>
        <div>
          <h3>Honest About Maintenance</h3>
          <p>Cedar needs cleaning and preservative treatment every 5–7 years. Daniel explains this during the estimate — if low-maintenance is the priority, he'll say so and recommend alternatives. No surprises after the sale.</p>
        </div>
      </div>
      <div class="why-item">
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="20 6 9 17 4 12"></polyline></svg>
        </div>
        <div>
          <h3>Correct Fastener Specification</h3>
          <p>Standard galvanized fasteners corrode under cedar's natural oils and Michigan's humidity. Kamps uses only stainless steel or hot-dipped galvanized fasteners — preventing rust staining and fastener failure.</p>
        </div>
      </div>
      <div class="why-item">
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
        </div>
        <div>
          <h3>Fire Treatment Confirmation</h3>
          <p>Before ordering cedar material, Kamps confirms HOA requirements and insurance specifications. Fire-treated Class A shake is available and sometimes required — confirmed upfront, not discovered after installation.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Mid-page CTA — CTA #2 -->
<div class="cta-banner">
  <div class="container">
    <h2>Get an Honest Cedar Shake Estimate — No Surprises</h2>
    <p>Daniel explains cedar's maintenance requirements upfront so you know exactly what you're committing to before signing anything. Free estimates across Grand Rapids and Kent County.</p>
    <div style="display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap;">
      <a href="/contact" class="btn btn-accent btn-lg">Get My Free Estimate</a>
      <?php echo phone_link('btn btn-outline-white btn-lg'); ?>
    </div>
  </div>
</div>

<!-- Process Steps -->
<section style="background: var(--color-light); padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">How It Works</span>
      <h2>Cedar Shake Installation: Built for Michigan Moisture</h2>
    </div>
    <div class="process-grid">
      <div class="process-step">
        <div class="process-number">1</div>
        <h3>Grade &amp; Style Consultation</h3>
        <p>Cedar grade and style are selected. Fire treatment, HOA compliance, and insurance requirements are confirmed before any material is ordered.</p>
      </div>
      <div class="process-step">
        <div class="process-number">2</div>
        <h3>Tear-Off &amp; Deck Prep</h3>
        <p>Old roofing removed, deck inspected and repaired. Any areas of moisture damage from the previous roof are addressed — cedar amplifies problems it's installed over.</p>
      </div>
      <div class="process-step">
        <div class="process-number">3</div>
        <h3>Breathable Underlayment</h3>
        <p>Breathable, non-perforated felt or specialty cedar underlayment is installed. Standard 15# felt traps moisture under cedar — this is where most Michigan cedar installations fail.</p>
      </div>
      <div class="process-step">
        <div class="process-number">4</div>
        <h3>Cedar Install with Proper Spacing</h3>
        <p>Shakes installed with correct side-lap spacing for airflow and drying. Stainless or hot-dipped galvanized fasteners only — steel nails corrode cedar within years in West Michigan.</p>
      </div>
    </div>
  </div>
</section>

<!-- FAQ -->
<section style="padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">Frequently Asked Questions</span>
      <h2>What Grand Rapids Homeowners Ask About Cedar Shake</h2>
    </div>
    <div class="faq-grid">
      <div class="faq-item">
        <h3>How long do cedar shake roofs last in Michigan?</h3>
        <p>20–30 years with proper maintenance. Michigan's moisture is cedar's main adversary. Roofs with good ventilation, breathable underlayment, and periodic cleaning and treatment every 5–7 years consistently reach the longer end of that range.</p>
      </div>
      <div class="faq-item">
        <h3>Are cedar roofs high maintenance?</h3>
        <p>More maintenance than asphalt, less than most expect. Cedar benefits from moss and algae cleaning every 5–7 years and a preservative treatment to prevent rot. Properly maintained cedar reaches 25–30 years. Kamps is upfront about what ownership requires before any estimate is signed.</p>
      </div>
      <div class="faq-item">
        <h3>How much does cedar shake roofing cost in Grand Rapids?</h3>
        <p>$10,000–$22,000 for most residential applications. Cedar grade, shake style, and roof complexity affect cost. A detailed, itemized estimate is provided after Daniel inspects your roof — no guessing from aerial photos.</p>
      </div>
    </div>
  </div>
</section>

<!-- Closing CTA — CTA #3 -->
<section class="closing-cta">
  <div class="container">
    <h2>Get Your Cedar Shake Roof Estimate This Week</h2>
    <p>$10,000–$22,000 installed. Free estimate within 24–48 hours. Daniel explains the full maintenance picture before you commit — so your cedar roof performs for the full 20–30 years.</p>
    <div class="btn-row">
      <a href="/contact" class="btn btn-accent btn-lg">Schedule My Free Estimate</a>
      <?php echo phone_link('btn btn-outline-white btn-lg'); ?>
    </div>
  </div>
</section>

<?php include $_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php'; ?>
