<?php
/**
 * services/index.php — Kamps Professional Roofing
 * Services listing page — all roofing, gutter & siding services
 * Generated by Page One Insights
 */
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/functions.php';

$pageTitle       = "Roofing, Gutters & Siding Services Grand Rapids MI | Kamps";
$pageDescription = "Full-service roofing contractor in Grand Rapids, MI. Roof replacement, repair, emergency roofing, gutters, siding, and more. Free estimates. Call Kamps Professional Roofing.";
$pageKeywords    = "roofing services grand rapids mi, roof replacement grand rapids, gutter installation grand rapids, siding contractor grand rapids, emergency roof repair west michigan";
$canonicalUrl    = SITE_URL . '/services';
$ogImage         = "https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914925-2022-05-22__1_.webp";
$currentPage     = "services";
$heroImage       = "https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914925-2022-05-22__1_.webp";

$breadcrumbs = [
    ['name' => 'Home',     'url' => '/'],
    ['name' => 'Services', 'url' => '/services'],
];

$schemaMarkup = '[' . breadcrumb_schema($breadcrumbs) . ']';

include $_SERVER['DOCUMENT_ROOT'] . '/includes/head.php';
include $_SERVER['DOCUMENT_ROOT'] . '/includes/header.php';
?>

<style>
/* ── Services Index — Page-specific styles ────────────────── */
.inner-hero {
  position: relative;
  min-height: 55vh;
  display: flex;
  align-items: center;
  background-size: cover;
  background-position: center;
  padding-top: 80px;
}
.inner-hero::before {
  content: '';
  position: absolute;
  inset: 0;
  background: linear-gradient(135deg, rgba(26,43,60,0.85) 0%, rgba(6,182,212,0.25) 100%);
  z-index: 1;
}
.inner-hero .container { position: relative; z-index: 2; }
.inner-hero .hero-content { text-align: left; max-width: 700px; }

.breadcrumb-nav {
  background: var(--color-light);
  padding: 0.75rem 0;
  border-bottom: 1px solid var(--color-gray-light);
}
.breadcrumb {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  list-style: none;
  font-size: 0.875rem;
}
.breadcrumb-item + .breadcrumb-item::before { content: '/'; color: var(--color-gray); }
.breadcrumb-item a { color: var(--color-primary); }
.breadcrumb-item.active { color: var(--color-gray); }

/* ── Ticker ────────────────────────────────────────────────── */
.ticker-strip {
  background: var(--color-primary);
  padding: 0.75rem 0;
  overflow: hidden;
  white-space: nowrap;
}
.ticker-track {
  display: inline-flex;
  animation: ticker-scroll 30s linear infinite;
}
.ticker-track:hover { animation-play-state: paused; }
.ticker-item {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0 2rem;
  color: white;
  font-size: 0.8rem;
  font-weight: 600;
  letter-spacing: 0.1em;
  text-transform: uppercase;
}
.ticker-sep { color: var(--color-accent); }
@keyframes ticker-scroll {
  from { transform: translateX(0); }
  to   { transform: translateX(-50%); }
}

/* ── Services sections ─────────────────────────────────────── */
.services-section {
  padding: var(--space-16) 0;
}
.services-section:nth-child(even) {
  background: var(--color-light);
}
.section-header {
  text-align: center;
  margin-bottom: 3rem;
}
.eyebrow {
  display: inline-block;
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--color-accent);
  background: rgba(6,182,212,0.1);
  padding: 0.35rem 1rem;
  border-radius: 99px;
  margin-bottom: 1rem;
}
.section-title {
  font-family: var(--font-heading);
  font-size: clamp(1.8rem, 4vw, 2.8rem);
  font-weight: 800;
  color: var(--color-dark);
  letter-spacing: -0.02em;
  line-height: 1.15;
  margin-bottom: 1rem;
}
.section-subtitle {
  color: var(--color-gray);
  font-size: 1.1rem;
  max-width: 600px;
  margin: 0 auto;
  line-height: 1.6;
}

/* ── Service Cards Grid ────────────────────────────────────── */
.services-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 1.5rem;
}
@media (max-width: 1023px) {
  .services-grid { grid-template-columns: repeat(2, 1fr); }
}
@media (max-width: 767px) {
  .services-grid { grid-template-columns: 1fr; }
}

.service-card {
  background: var(--color-white);
  border-radius: var(--radius-lg);
  padding: 2rem 1.75rem;
  box-shadow: var(--shadow-card);
  border-top: 4px solid transparent;
  transition: all 0.25s ease;
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}
.service-card:hover {
  transform: translateY(-6px);
  box-shadow: 0 8px 28px rgba(0,0,0,0.16);
  border-top-color: var(--color-accent);
}
.service-card-icon {
  width: 52px;
  height: 52px;
  border-radius: var(--radius-md);
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
  flex-shrink: 0;
  transition: transform 0.2s ease;
}
.service-card:hover .service-card-icon {
  transform: scale(1.1) rotate(-5deg);
}
.service-card h3 {
  font-family: var(--font-heading);
  font-size: 1.1rem;
  font-weight: 700;
  color: var(--color-dark);
  margin: 0;
}
.service-card p {
  font-size: 0.9rem;
  color: var(--color-gray);
  line-height: 1.5;
  margin: 0;
  flex: 1;
}
.learn-more {
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
  font-size: 0.875rem;
  font-weight: 700;
  color: var(--color-accent);
  text-decoration: none;
  margin-top: auto;
  transition: gap 0.2s ease;
}
.learn-more:hover { gap: 0.6rem; }

/* ── Intro section ─────────────────────────────────────────── */
.intro-section {
  padding: 3rem 0;
  background: var(--color-white);
  border-bottom: 1px solid var(--color-gray-light);
}
.intro-section p {
  font-size: 1.1rem;
  color: var(--color-gray);
  line-height: 1.7;
  max-width: 65ch;
  margin: 0 auto;
  text-align: center;
}

/* ── CTA Banner ────────────────────────────────────────────── */
.cta-banner {
  position: relative;
  background: linear-gradient(135deg, var(--color-primary) 0%, #0f1c2b 100%);
  padding: 4rem 0;
  overflow: hidden;
  text-align: center;
}
.cta-banner::before {
  content: '';
  position: absolute;
  inset: 0;
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.04'/%3E%3C/svg%3E");
  opacity: 0.04;
  pointer-events: none;
}
.cta-banner .container { position: relative; z-index: 1; }
.cta-banner h2 {
  font-family: var(--font-heading);
  font-size: clamp(1.8rem, 4vw, 2.8rem);
  font-weight: 800;
  color: white;
  letter-spacing: -0.02em;
  margin-bottom: 1rem;
}
.cta-banner p {
  color: rgba(255,255,255,0.8);
  font-size: 1.1rem;
  margin-bottom: 2rem;
  max-width: 600px;
  margin-inline: auto;
}
.cta-banner .btn-row {
  display: flex;
  gap: 1rem;
  justify-content: center;
  flex-wrap: wrap;
  margin-bottom: 1.5rem;
}
.cta-phone {
  font-family: var(--font-heading);
  font-size: 1.8rem;
  font-weight: 800;
  color: var(--color-accent);
  letter-spacing: -0.02em;
  display: block;
}
.cta-phone a { color: inherit; text-decoration: none; }
.cta-phone a:hover { color: white; }

/* ── Closing CTA ───────────────────────────────────────────── */
.closing-cta {
  background: var(--color-dark);
  padding: 5rem 0;
  text-align: center;
}
.closing-cta h2 {
  font-family: var(--font-heading);
  font-size: clamp(1.8rem, 4vw, 2.8rem);
  font-weight: 800;
  color: white;
  letter-spacing: -0.02em;
  margin-bottom: 1rem;
}
.closing-cta p {
  color: rgba(255,255,255,0.7);
  font-size: 1.05rem;
  max-width: 560px;
  margin: 0 auto 2rem;
  line-height: 1.6;
}

/* ── Section divider ───────────────────────────────────────── */
.divider-wave {
  line-height: 0;
  overflow: hidden;
}
.divider-wave svg { display: block; }
</style>

<main id="main-content">

  <!-- ── Inner Hero ─────────────────────────────────────────── -->
  <section class="inner-hero" style="background-image: url('https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914925-2022-05-22__1_.webp');" aria-label="Services page hero">
    <div class="container">
      <div class="hero-content">
        <span class="eyebrow" style="margin-bottom:1rem;display:inline-block;">All Services</span>
        <h1 style="font-family:var(--font-heading);font-size:clamp(2.5rem,6vw,4.5rem);font-weight:800;letter-spacing:-0.02em;line-height:1.1;color:white;margin-bottom:1rem;text-wrap:balance;">
          Roofing, Gutters &amp; Siding<br>
          <span style="background:linear-gradient(90deg,#06b6d4,#38bdf8);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;">in Grand Rapids, MI</span>
        </h1>
        <p style="font-size:1.15rem;color:rgba(255,255,255,0.85);max-width:560px;line-height:1.6;margin-bottom:2rem;">
          Every component of your home's exterior, handled by one crew — so nothing slips through the cracks.
        </p>
        <div style="display:flex;gap:1rem;flex-wrap:wrap;">
          <a href="/contact" class="btn btn-accent btn-lg">Get a Free Estimate</a>
          <?php if (!empty(SITE_PHONE)): ?>
          <a href="tel:<?php echo preg_replace('/[^0-9+]/', '', SITE_PHONE); ?>" class="btn btn-outline-white btn-lg">Call <?php echo htmlspecialchars(SITE_PHONE_DISPLAY); ?></a>
          <?php else: ?>
          <a href="/contact" class="btn btn-outline-white btn-lg">View All Services</a>
          <?php endif; ?>
        </div>
      </div>
    </div>
  </section>

  <!-- ── Breadcrumb ─────────────────────────────────────────── -->
  <?php echo breadcrumb_nav($breadcrumbs); ?>

  <!-- ── Ticker Strip ───────────────────────────────────────── -->
  <div class="ticker-strip" aria-hidden="true">
    <div class="ticker-track">
      <span class="ticker-item">Roof Replacement <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Storm Damage Repair <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Emergency Roofing <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Gutter Installation <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Siding Replacement <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Free Estimates <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">30+ Years Experience <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Licensed &amp; Insured <span class="ticker-sep">✦</span></span>
      <!-- duplicate for seamless loop -->
      <span class="ticker-item">Roof Replacement <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Storm Damage Repair <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Emergency Roofing <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Gutter Installation <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Siding Replacement <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Free Estimates <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">30+ Years Experience <span class="ticker-sep">✦</span></span>
      <span class="ticker-item">Licensed &amp; Insured <span class="ticker-sep">✦</span></span>
    </div>
  </div>

  <!-- ── Intro Section ──────────────────────────────────────── -->
  <section class="intro-section">
    <div class="container">
      <p>Kamps Professional Roofing handles every component of your home's exterior — from a full roof teardown and replacement to a single gutter end cap. Daniel Kamps has built this company on one principle: show up, do it right, and stand behind the work. No subcontracting the hard parts. No disappearing after the invoice is paid.</p>
    </div>
  </section>

  <!-- ── Roofing Services Grid ──────────────────────────────── -->
  <section class="services-section" aria-labelledby="roofing-heading">
    <div class="container">
      <div class="section-header" data-animate>
        <span class="eyebrow">Roofing Services</span>
        <h2 class="section-title" id="roofing-heading">Every Roof. Every Material. Done Right.</h2>
        <p class="section-subtitle">From asphalt shingle reroof to full slate installation — if it covers a West Michigan home, Kamps installs it.</p>
      </div>

      <div class="services-grid">

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
          </div>
          <h3>Roof Replacement</h3>
          <p>Complete teardown and installation of a new roof system — including decking inspection, ice &amp; water shield, and full cleanup.</p>
          <a href="/services/roof-replacement" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>
          </div>
          <h3>Roof Repair</h3>
          <p>Targeted repair of leaks, missing shingles, flashing failures, and other damage — diagnosed honestly, fixed once.</p>
          <a href="/services/residential-roof-leak-repair" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"></polygon></svg>
          </div>
          <h3>Emergency Roof Repair</h3>
          <p>Active leaks and storm breaches addressed fast — because water damage compounds by the hour.</p>
          <a href="/services/emergency-roof-repair" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14.5 10c-.83 0-1.5-.67-1.5-1.5v-5c0-.83.67-1.5 1.5-1.5s1.5.67 1.5 1.5v5c0 .83-.67 1.5-1.5 1.5z"></path><path d="M20.5 10H19V8.5c0-.83.67-1.5 1.5-1.5s1.5.67 1.5 1.5-.67 1.5-1.5 1.5z"></path><path d="M9.5 14c.83 0 1.5.67 1.5 1.5v5c0 .83-.67 1.5-1.5 1.5S8 21.33 8 20.5v-5c0-.83.67-1.5 1.5-1.5z"></path><path d="M3.5 14H5v1.5c0 .83-.67 1.5-1.5 1.5S2 16.33 2 15.5 2.67 14 3.5 14z"></path><path d="M14 14.5c0-.83.67-1.5 1.5-1.5h5c.83 0 1.5.67 1.5 1.5s-.67 1.5-1.5 1.5h-5c-.83 0-1.5-.67-1.5-1.5z"></path><path d="M15.5 19H14v1.5c0 .83.67 1.5 1.5 1.5s1.5-.67 1.5-1.5-.67-1.5-1.5-1.5z"></path><path d="M10 9.5C10 8.67 9.33 8 8.5 8h-5C2.67 8 2 8.67 2 9.5S2.67 11 3.5 11h5c.83 0 1.5-.67 1.5-1.5z"></path><path d="M8.5 5H10V3.5C10 2.67 9.33 2 8.5 2S7 2.67 7 3.5 7.67 5 8.5 5z"></path></svg>
          </div>
          <h3>Storm Damage Repair</h3>
          <p>Hail, wind, and fallen tree damage documented and repaired — with full insurance claim support from start to finish.</p>
          <a href="/services/storm-damage-roof-repair" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>
          </div>
          <h3>Roof Inspection</h3>
          <p>Detailed inspection of your roof's condition — shingles, flashing, gutters, ridge, and decking — with a written report.</p>
          <a href="/services/roof-inspection" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
          </div>
          <h3>Roof Maintenance</h3>
          <p>Proactive maintenance plans that extend roof life — clearing debris, sealing flashings, and catching small issues before they become big ones.</p>
          <a href="/services/roof-maintenance" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><line x1="3" y1="9" x2="21" y2="9"></line><line x1="9" y1="21" x2="9" y2="9"></line></svg>
          </div>
          <h3>Asphalt Shingle Roofing</h3>
          <p>Architectural and 3-tab asphalt shingle installation — West Michigan's most cost-effective roofing system, installed to manufacturer spec.</p>
          <a href="/services/asphalt-shingle-roofing" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
          </div>
          <h3>Metal Roofing</h3>
          <p>Standing seam and corrugated metal roofing systems — 40–70 year lifespans, superior wind resistance, and a bold clean aesthetic.</p>
          <a href="/services/metal-roofing" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22V2M2 12h20"></path></svg>
          </div>
          <h3>Tile Roof Installation</h3>
          <p>Concrete and clay tile roofing for West Michigan homes that want lasting curb appeal and exceptional durability.</p>
          <a href="/services/tile-roof-installation" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"></path></svg>
          </div>
          <h3>Slate Roof Installation</h3>
          <p>Natural slate roofing — among the most durable materials available, with lifespans exceeding 100 years when installed correctly.</p>
          <a href="/services/slate-roof-installation" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M17 8h1a4 4 0 1 1 0 8h-1"></path><path d="M3 8h14v9a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V8z"></path><line x1="6" y1="2" x2="6" y2="4"></line><line x1="10" y1="2" x2="10" y2="4"></line><line x1="14" y1="2" x2="14" y2="4"></line></svg>
          </div>
          <h3>Cedar Shake Roofing</h3>
          <p>Hand-split and sawn cedar shake installation — a natural look that weathers beautifully in Michigan's four-season climate.</p>
          <a href="/services/cedar-shake-roofing" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>
          </div>
          <h3>Insurance Claims Help</h3>
          <p>Daniel works directly with your adjuster — documenting damage, providing accurate scope estimates, and keeping the process moving.</p>
          <a href="/services/insurance-roof-replacement" class="learn-more">Learn more →</a>
        </div>

      </div>
    </div>
  </section>

  <!-- ── Section Divider ────────────────────────────────────── -->
  <div class="divider-wave" aria-hidden="true" style="background:var(--color-light);">
    <svg viewBox="0 0 1440 50" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" width="100%" height="50">
      <path d="M0,0 L0,30 Q360,60 720,30 Q1080,0 1440,30 L1440,0 Z" fill="var(--color-white)"></path>
    </svg>
  </div>

  <!-- ── Mid-page CTA Banner (CTA #2) ───────────────────────── -->
  <section class="cta-banner" aria-label="Get a free roofing estimate">
    <div class="container">
      <span class="eyebrow" style="background:rgba(255,255,255,0.1);color:white;margin-bottom:1.5rem;display:inline-block;">Free Estimates</span>
      <h2>Not Sure Which Service You Need?</h2>
      <p>Daniel Kamps will inspect your roof, gutters, and siding — tell you honestly what needs attention and what doesn't — and give you a written, itemized estimate at no charge.</p>
      <div class="btn-row">
        <a href="/contact" class="btn btn-accent btn-lg">Schedule Your Free Estimate</a>
        <a href="/about" class="btn btn-outline-white btn-lg">Meet Daniel Kamps</a>
      </div>
      <?php if (!empty(SITE_PHONE)): ?>
      <span class="cta-phone"><a href="tel:<?php echo preg_replace('/[^0-9+]/', '', SITE_PHONE); ?>"><?php echo htmlspecialchars(SITE_PHONE_DISPLAY); ?></a></span>
      <?php endif; ?>
    </div>
  </section>

  <!-- ── Gutters & Siding Grid ──────────────────────────────── -->
  <section class="services-section" aria-labelledby="gutters-heading" style="background:var(--color-white);">
    <div class="container">
      <div class="section-header" data-animate>
        <span class="eyebrow">Gutters &amp; Siding</span>
        <h2 class="section-title" id="gutters-heading">Your Whole Exterior. One Contractor.</h2>
        <p class="section-subtitle">Gutter failures and siding gaps let water into your home just as surely as a failing roof. We cover all three.</p>
      </div>

      <div class="services-grid">

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path></svg>
          </div>
          <h3>Gutter Installation</h3>
          <p>Seamless aluminum gutters cut to exact length on-site — no seams, no weak points, properly pitched and fastened.</p>
          <a href="/services/gutter-installation" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
          </div>
          <h3>Gutter Repair</h3>
          <p>Leaking seams, sagging sections, and detached spikes fixed — before a minor drip becomes a foundation issue.</p>
          <a href="/services/gutter-repair" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="1 4 1 10 7 10"></polyline><path d="M3.51 15a9 9 0 1 0 .49-3.51"></path></svg>
          </div>
          <h3>Gutter Replacement</h3>
          <p>Full gutter system replacement when repair isn't enough — sized right for your roof's drainage load.</p>
          <a href="/services/gutter-replacement" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>
          </div>
          <h3>Gutter Cleaning</h3>
          <p>Debris removal, downspout flushing, and end cap checks — the basic maintenance that prevents most gutter problems.</p>
          <a href="/services/gutter-cleaning" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2"></rect></svg>
          </div>
          <h3>Siding Installation</h3>
          <p>Vinyl, fiber cement, and engineered wood siding installed with proper housewrap, flashing, and trim for Michigan's freeze-thaw cycles.</p>
          <a href="/services/siding-installation" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>
          </div>
          <h3>Siding Repair</h3>
          <p>Cracked, warped, or impact-damaged panels replaced and matched — keeping your exterior weathertight without a full replacement.</p>
          <a href="/services/siding-repair" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="1 4 1 10 7 10"></polyline><path d="M3.51 15a9 9 0 1 0 .49-3.51"></path></svg>
          </div>
          <h3>Siding Replacement</h3>
          <p>Complete siding system removal and replacement — including sheathing inspection, housewrap, and all trim and corner details.</p>
          <a href="/services/siding-replacement" class="learn-more">Learn more →</a>
        </div>

        <div class="service-card" data-animate>
          <div class="service-card-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="8" y1="6" x2="21" y2="6"></line><line x1="8" y1="12" x2="21" y2="12"></line><line x1="8" y1="18" x2="21" y2="18"></line><line x1="3" y1="6" x2="3.01" y2="6"></line><line x1="3" y1="12" x2="3.01" y2="12"></line><line x1="3" y1="18" x2="3.01" y2="18"></line></svg>
          </div>
          <h3>Fence Installation</h3>
          <p>Wood, vinyl, and chain-link fence installation across West Michigan — finished with the same attention to detail as every Kamps project.</p>
          <a href="/services/fence-installation" class="learn-more">Learn more →</a>
        </div>

      </div>
    </div>
  </section>

  <!-- ── Section Divider ────────────────────────────────────── -->
  <div class="divider-wave" aria-hidden="true" style="background:var(--color-white);">
    <svg viewBox="0 0 1440 50" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="none" width="100%" height="50">
      <path d="M0,50 L0,20 Q720,0 1440,20 L1440,50 Z" fill="var(--color-dark)"></path>
    </svg>
  </div>

  <!-- ── Closing CTA (CTA #3) ───────────────────────────────── -->
  <section class="closing-cta" aria-label="Contact Kamps for a free estimate">
    <div class="container">
      <span class="eyebrow" style="background:rgba(6,182,212,0.15);color:var(--color-accent);margin-bottom:1.5rem;display:inline-block;">West Michigan's Roofer</span>
      <h2>Same Crew You Meet Is the Crew on Your Roof</h2>
      <p>No handoffs. No strangers. Daniel's team handles the estimate, the work, and any callbacks. Get your free, written estimate this week.</p>
      <div style="display:flex;gap:1rem;justify-content:center;flex-wrap:wrap;margin-bottom:1.5rem;">
        <a href="/contact" class="btn btn-accent btn-lg">Request a Free Estimate</a>
        <a href="/service-areas" class="btn btn-outline-white btn-lg">Check Your Area</a>
      </div>
      <?php if (!empty(SITE_PHONE)): ?>
      <p style="color:rgba(255,255,255,0.5);font-size:0.9rem;">Or call direct: <a href="tel:<?php echo preg_replace('/[^0-9+]/', '', SITE_PHONE); ?>" style="color:var(--color-accent);font-weight:700;"><?php echo htmlspecialchars(SITE_PHONE_DISPLAY); ?></a></p>
      <?php endif; ?>
    </div>
  </section>

</main>

<?php include $_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php'; ?>
