<?php
/**
 * insurance-roof-replacement.php — Kamps Professional Roofing
 * Service Page: Insurance Roof Replacement — Grand Rapids, MI
 * Generated by Page One Insights
 */

require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/functions.php';

$breadcrumbs = [
    ['name' => 'Home',     'url' => '/'],
    ['name' => 'Services', 'url' => '/services'],
    ['name' => 'Insurance Roof Replacement', 'url' => '/services/insurance-roof-replacement'],
];

$pageTitle       = "Insurance Roof Replacement Grand Rapids MI | Kamps Roofing";
$pageDescription = "Daniel Kamps guides Grand Rapids homeowners through insurance roof replacement claims — documentation, adjuster meetings, and full approved scope. No out-of-pocket beyond deductible. Free inspection.";
$pageKeywords    = "insurance roof replacement grand rapids, roofing insurance claims mi, storm restoration roofing grand rapids, insurance claim assistance kent county, hail damage roof replacement west michigan";
$canonicalUrl    = SITE_URL . '/services/insurance-roof-replacement';
$ogImage         = 'https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470681461_122127113786552346_8603661316175448269_n.jpg';
$heroImage       = 'https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470681461_122127113786552346_8603661316175448269_n.jpg';
$currentPage     = 'services';

$schemaMarkup = '[' . breadcrumb_schema($breadcrumbs) . ',' . service_schema(
    'Insurance Roof Replacement',
    'Complete insurance claim assistance for storm-damaged roofs in Grand Rapids, MI. Daniel Kamps documents damage, communicates with adjusters, and ensures approved scopes cover the full repair. No out-of-pocket cost beyond your deductible.',
    '/services/insurance-roof-replacement'
) . ',' . json_encode([
    '@context'   => 'https://schema.org',
    '@type'      => 'FAQPage',
    'mainEntity' => [
        [
            '@type'          => 'Question',
            'name'           => 'Will filing a roof claim raise my insurance rates?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Possibly — consult your agent to understand your specific policy terms before filing. That said, most major storm damage is worth filing regardless of rate impact. Delaying a legitimate claim can compound damage and reduce your payout if the insurer determines neglect contributed to worsening conditions.'],
        ],
        [
            '@type'          => 'Question',
            'name'           => 'What if my insurance company lowballs my claim?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Kamps communicates directly with adjusters on your behalf. If the initial scope is insufficient, Daniel can request a re-inspection, provide supplemental documentation, and advocate for the full scope needed to restore your roof to pre-storm condition. This is a normal part of the process.'],
        ],
        [
            '@type'          => 'Question',
            'name'           => 'How long does the insurance roof replacement process take?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'From the initial damage inspection to a completed roof typically takes 2–6 weeks. Claim processing time depends on your insurer and their workload, especially after widespread storm events that affect many Grand Rapids homes simultaneously.'],
        ],
    ],
], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ']';

include $_SERVER['DOCUMENT_ROOT'] . '/includes/head.php';
include $_SERVER['DOCUMENT_ROOT'] . '/includes/header.php';
?>

<style>
.process-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.process-step {
  text-align: center;
  padding: 2rem 1.5rem;
  background: var(--color-white);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-card);
}
.process-number {
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  color: white;
  font-family: var(--font-heading);
  font-size: 1.5rem;
  font-weight: 800;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 1rem;
}
.process-step h3 { font-size: 1rem; margin-bottom: 0.5rem; color: var(--color-dark); }
.process-step p { font-size: 0.875rem; color: var(--color-gray); line-height: 1.5; }
.why-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.why-item {
  display: flex;
  gap: 1rem;
  padding: 1.5rem;
  background: var(--color-white);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-card);
}
.why-icon {
  flex-shrink: 0;
  width: 48px;
  height: 48px;
  border-radius: var(--radius-md);
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
}
.why-item h3 { font-size: 1rem; margin-bottom: 0.4rem; color: var(--color-dark); }
.why-item p { font-size: 0.875rem; color: var(--color-gray); line-height: 1.5; }
.faq-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.faq-item {
  background: var(--color-white);
  border-radius: var(--radius-lg);
  padding: 1.75rem;
  box-shadow: var(--shadow-card);
  border-left: 4px solid var(--color-accent);
}
.faq-item h3 { font-size: 1rem; margin-bottom: 0.75rem; color: var(--color-dark); }
.faq-item p { font-size: 0.9rem; color: var(--color-gray); line-height: 1.6; }
@media (max-width: 1023px) {
  .process-grid { grid-template-columns: 1fr 1fr; }
}
@media (max-width: 767px) {
  .why-grid { grid-template-columns: 1fr; }
}
@media (max-width: 480px) {
  .process-grid { grid-template-columns: 1fr; }
}
</style>

<?php echo breadcrumb_nav($breadcrumbs); ?>

<!-- Hero — CTA #1 -->
<section class="hero hero-inner" style="background-image: url('https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470681461_122127113786552346_8603661316175448269_n.jpg');">
  <div class="hero-overlay"></div>
  <div class="container">
    <div class="hero-content">
      <span class="hero-eyebrow">Kamps Professional Roofing</span>
      <h1>Insurance Roof Replacement Grand Rapids, MI</h1>
      <p class="hero-subtitle">Daniel Kamps handles storm damage claims from documentation through adjuster meetings to finished roof — your only cost is your deductible.</p>
      <div class="hero-buttons">
        <a href="/contact" class="btn btn-accent btn-lg">Get a Free Storm Inspection</a>
        <?php echo phone_link('btn btn-outline-white btn-lg', 'Call Now'); ?>
      </div>
      <div class="hero-trust">
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg> Licensed &amp; Insured</span>
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg> 30+ Years Experience</span>
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="20 6 9 17 4 12"></polyline></svg> Free Estimates</span>
      </div>
    </div>
  </div>
</section>

<!-- Service Detail -->
<section style="background: var(--color-light); padding: var(--space-16) 0;">
  <div class="container">
    <div class="about-split" data-animate>
      <div class="about-content">
        <div class="section-header" style="text-align:left; margin-bottom: 2rem;">
          <span class="eyebrow">Storm Damage &amp; Insurance Claims</span>
          <h2>Most Storm Damage Costs You Nothing Beyond Your Deductible — If the Claim Is Filed Correctly</h2>
        </div>
        <p>Hail, wind, and falling branches — standard homeowner's insurance covers most storm damage to your roof in Grand Rapids. The problem isn't coverage; it's documentation. Claims that arrive at an insurer with weak documentation get underpaid or denied. Daniel Kamps has spent 30+ years learning what adjusters need to see, how damage is photographed and described to maximize approved scope, and when to push back on an insufficient payout.</p>
        <p>The insurance roof replacement process, done right: Daniel inspects your roof and provides a professional damage report with dated photos and a written scope. You file the claim. Daniel meets the adjuster on-site — this is the step most Kent County homeowners skip, and it's where scope gets cut. Once your insurer approves the work and releases funds, Kamps completes the replacement. Your out-of-pocket cost is your deductible — nothing more. The typical timeline from inspection to finished roof is 2-6 weeks depending on insurer workload.</p>
        <p>Claims that come in weak — a few phone photos and "missing shingles" — get partial approvals. Kamps' documentation package includes systematic photos, a written damage assessment, and a defined scope that adjusters take seriously. When initial payouts fall short, Daniel files supplemental documentation and requests re-inspection. This is a normal part of the insurance process, not an escalation.</p>
        <p>Kamps does not begin work until the claim is approved and funds are confirmed. Any contractor who pressures you to sign before approval is creating risk for you, not for them. That's not how Daniel has run insurance jobs in West Michigan for three decades.</p>
        <p style="font-size: 0.8rem; color: var(--color-gray);">Last Updated: <?php echo date('F Y'); ?></p>
      </div>
      <div class="about-image">
        <picture><img src="https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470681461_122127113786552346_8603661316175448269_n.jpg" alt="storm damaged roof in Grand Rapids Michigan inspected by Kamps Professional Roofing for insurance claim" width="600" height="450" loading="lazy" style="border-radius: var(--radius-lg); width: 100%; object-fit: cover;"></picture>
      </div>
    </div>
  </div>
</section>

<!-- Why Choose Kamps -->
<section style="padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">Why Kamps</span>
      <h2>Three Decades of Working Directly with Insurance Companies</h2>
    </div>
    <div class="why-grid">
      <div class="why-item" data-animate>
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline></svg>
        </div>
        <div>
          <h3>Professional Damage Documentation</h3>
          <p>Kamps provides a damage report that adjusters recognize as professional documentation — systematic photos, written assessment, and defined scope. This materially affects approved payout amounts.</p>
        </div>
      </div>
      <div class="why-item" data-animate>
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
        </div>
        <div>
          <h3>Daniel Meets the Adjuster on Your Roof</h3>
          <p>Most homeowners let the adjuster inspect alone — and adjusters miss damage. Having Daniel on the roof pointing out hail strikes, granule loss, and flashing damage routinely adds scope that otherwise gets excluded.</p>
        </div>
      </div>
      <div class="why-item" data-animate>
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>
        </div>
        <div>
          <h3>No Work Until Claim Approval — Period</h3>
          <p>Kamps begins no work until your claim is approved and funds are confirmed. This protects you from liability if the claim is disputed and ensures the work is fully covered before a single shingle comes off.</p>
        </div>
      </div>
      <div class="why-item" data-animate>
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="20 6 9 17 4 12"></polyline></svg>
        </div>
        <div>
          <h3>Written Scopes — No Surprise Bills</h3>
          <p>Every project has a written scope matching the approved insurance work. You won't receive a bill for work not covered by your claim without explicit prior authorization. No hidden charges, no unapproved add-ons.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Mid-page CTA — CTA #2 -->
<div class="cta-banner">
  <div class="container">
    <h2>Get a Free Storm Damage Inspection — Before You File</h2>
    <p>Daniel inspects your roof and provides a professional damage report at no charge. You'll have the documentation you need to file a complete, defensible insurance claim in Grand Rapids.</p>
    <div style="display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap;">
      <a href="/contact" class="btn btn-accent btn-lg">Schedule My Free Inspection</a>
      <?php echo phone_link('btn btn-outline-white btn-lg'); ?>
    </div>
  </div>
</div>

<!-- Process Steps -->
<section style="background: var(--color-light); padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">How It Works</span>
      <h2>From Storm Damage to Finished Roof — Step by Step</h2>
    </div>
    <div class="process-grid">
      <div class="process-step" data-animate>
        <div class="process-number">1</div>
        <h3>Free Inspection &amp; Documentation</h3>
        <p>Daniel inspects the roof, photographs all damage systematically, and produces a written damage assessment — the documentation package your insurer needs to process a complete claim.</p>
      </div>
      <div class="process-step" data-animate>
        <div class="process-number">2</div>
        <h3>You File the Claim</h3>
        <p>You file with your insurance company using the documentation package. Daniel walks you through exactly what to say and send so the claim goes in complete — not as a vague "storm damage" report.</p>
      </div>
      <div class="process-step" data-animate>
        <div class="process-number">3</div>
        <h3>Adjuster Meeting on the Roof</h3>
        <p>Daniel meets the adjuster on your roof. Every damage point is shown and documented in real-time. If the initial scope falls short, supplemental documentation is filed immediately.</p>
      </div>
      <div class="process-step" data-animate>
        <div class="process-number">4</div>
        <h3>Work Begins on Approval</h3>
        <p>Kamps begins work only after your claim is approved and funds are released. Your only out-of-pocket expense is your deductible. The replacement meets the same standards as any Kamps roof installation.</p>
      </div>
    </div>
  </div>
</section>

<!-- FAQ -->
<section style="padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">Frequently Asked Questions</span>
      <h2>Insurance Roof Replacement Questions Grand Rapids Homeowners Ask</h2>
    </div>
    <div class="faq-grid">
      <div class="faq-item" data-animate>
        <h3>Will filing a roof claim raise my insurance rates?</h3>
        <p>Possibly — consult your agent to understand your specific policy terms before filing. That said, most major storm damage is worth filing regardless of rate impact. Delaying a legitimate claim can compound damage and reduce your payout if the insurer determines neglect contributed to worsening conditions.</p>
      </div>
      <div class="faq-item" data-animate>
        <h3>What if my insurance company lowballs my claim?</h3>
        <p>Kamps communicates directly with adjusters on your behalf. If the initial scope is insufficient, Daniel requests a re-inspection, provides supplemental documentation, and advocates for the full scope needed to restore your roof to pre-storm condition. This is a normal, expected part of the insurance process in Grand Rapids — not an exceptional escalation.</p>
      </div>
      <div class="faq-item" data-animate>
        <h3>How long does the insurance roof replacement process take?</h3>
        <p>From the initial damage inspection to a completed roof typically takes <strong>2-6 weeks</strong>. Claim processing time depends on your insurer and their workload — after a widespread West Michigan hail event, insurers can take longer. Daniel keeps you informed at every stage of the process.</p>
      </div>
    </div>
  </div>
</section>

<!-- Closing CTA — CTA #3 -->
<section class="closing-cta">
  <div class="container">
    <h2>Every Day You Wait Is a Day Storm Damage Can Spread</h2>
    <p>Free storm damage inspection. Professional documentation package. Adjuster meeting included. Work begins only when your claim is approved. Your deductible is your only out-of-pocket cost.</p>
    <div class="btn-row">
      <a href="/contact" class="btn btn-accent btn-lg">Schedule My Free Inspection</a>
      <?php echo phone_link('btn btn-outline-white btn-lg'); ?>
    </div>
  </div>
</section>

<?php include $_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php'; ?>
