<?php
/**
 * metal-roofing.php — Kamps Professional Roofing
 * Service Page: Metal Roofing — Grand Rapids, MI
 * Generated by Page One Insights
 */

require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/functions.php';

$breadcrumbs = [
    ['name' => 'Home',     'url' => '/'],
    ['name' => 'Services', 'url' => '/services'],
    ['name' => 'Metal Roofing', 'url' => '/services/metal-roofing'],
];

$pageTitle       = "Metal Roofing Grand Rapids MI | Kamps Professional Roofing";
$pageDescription = "Standing seam and steel metal roofing installation in Grand Rapids, MI. Lasts 40–70 years, sheds Michigan snow naturally. Free estimates from Daniel Kamps — 30+ years experience.";
$pageKeywords    = "metal roofing grand rapids mi, standing seam metal roof grand rapids, residential metal roofing grand rapids, steel roof installation kent county, metal roof replacement west michigan";
$canonicalUrl    = SITE_URL . '/services/metal-roofing';
$ogImage         = 'https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914926-2023-05-26__3_.webp';
$heroImage       = 'https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914926-2023-05-26__3_.webp';
$currentPage     = 'services';

$schemaMarkup = '[' . breadcrumb_schema($breadcrumbs) . ',' . service_schema(
    'Metal Roofing',
    'Professional standing seam and steel metal roofing installation in Grand Rapids, MI. 40–70 year lifespans, energy-efficient reflective panels, and expert installation for Michigan freeze-thaw conditions.',
    '/services/metal-roofing'
) . ',' . json_encode([
    '@context'   => 'https://schema.org',
    '@type'      => 'FAQPage',
    'mainEntity' => [
        [
            '@type'          => 'Question',
            'name'           => 'How much does metal roofing cost in Grand Rapids?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Metal roofing in Grand Rapids typically runs $12,000–$25,000+ for a full residential installation. Standing seam systems are at the higher end; exposed fastener panels cost less. The longer 40–70 year lifespan makes the per-year cost competitive with asphalt.'],
        ],
        [
            '@type'          => 'Question',
            'name'           => 'Is metal roofing loud when it rains?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'With proper underlayment and insulation between the panel and the decking, a metal roof is no louder than an asphalt shingle roof during rain. The "loud tin roof" experience comes from uninsulated agricultural buildings — not residential installations.'],
        ],
        [
            '@type'          => 'Question',
            'name'           => 'How long does a metal roof last in Michigan?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'A properly installed metal roof in Michigan lasts 40–70 years with minimal maintenance. Metal handles freeze-thaw cycles better than asphalt — it expands and contracts without cracking, and sheds snow naturally without the ice dam risk.'],
        ],
    ],
], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ']';

include $_SERVER['DOCUMENT_ROOT'] . '/includes/head.php';
include $_SERVER['DOCUMENT_ROOT'] . '/includes/header.php';
?>

<style>
.process-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.process-step {
  text-align: center;
  padding: 2rem 1.5rem;
  background: var(--color-white);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-card);
}
.process-number {
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  color: white;
  font-family: var(--font-heading);
  font-size: 1.5rem;
  font-weight: 800;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 1rem;
}
.process-step h3 { font-size: 1rem; margin-bottom: 0.5rem; color: var(--color-dark); }
.process-step p { font-size: 0.875rem; color: var(--color-gray); line-height: 1.5; }
.why-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.why-item {
  display: flex;
  gap: 1rem;
  padding: 1.5rem;
  background: var(--color-white);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-card);
}
.why-icon {
  flex-shrink: 0;
  width: 48px;
  height: 48px;
  border-radius: var(--radius-md);
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
}
.why-item h3 { font-size: 1rem; margin-bottom: 0.4rem; color: var(--color-dark); }
.why-item p { font-size: 0.875rem; color: var(--color-gray); line-height: 1.5; }
.faq-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.faq-item {
  background: var(--color-white);
  border-radius: var(--radius-lg);
  padding: 1.75rem;
  box-shadow: var(--shadow-card);
  border-left: 4px solid var(--color-accent);
}
.faq-item h3 { font-size: 1rem; margin-bottom: 0.75rem; color: var(--color-dark); }
.faq-item p { font-size: 0.9rem; color: var(--color-gray); line-height: 1.6; }
@media (max-width: 1023px) {
  .process-grid { grid-template-columns: 1fr 1fr; }
}
@media (max-width: 767px) {
  .why-grid { grid-template-columns: 1fr; }
}
@media (max-width: 480px) {
  .process-grid { grid-template-columns: 1fr; }
}
</style>

<?php echo breadcrumb_nav($breadcrumbs); ?>

<!-- Hero — CTA #1 -->
<section class="hero hero-inner" style="background-image: url('https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914926-2023-05-26__3_.webp');">
  <div class="hero-overlay"></div>
  <div class="container">
    <div class="hero-content">
      <span class="hero-eyebrow">Kamps Professional Roofing</span>
      <h1>Metal Roofing Grand Rapids, MI</h1>
      <p class="hero-subtitle">A standing seam metal roof installed today will still be performing when asphalt shingles would have been replaced twice over.</p>
      <div class="hero-buttons">
        <a href="/contact" class="btn btn-accent btn-lg">Get a Free Estimate</a>
        <?php echo phone_link('btn btn-outline-white btn-lg', 'Call Now'); ?>
      </div>
      <div class="hero-trust">
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg> Licensed &amp; Insured</span>
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg> 30+ Years Experience</span>
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="20 6 9 17 4 12"></polyline></svg> Free Estimates</span>
      </div>
    </div>
  </div>
</section>

<!-- Service Detail -->
<section style="background: var(--color-light); padding: var(--space-16) 0;">
  <div class="container">
    <div class="about-split" data-animate>
      <div class="about-content">
        <div class="section-header" style="text-align:left; margin-bottom: 2rem;">
          <span class="eyebrow">Metal Roofing in Grand Rapids</span>
          <h2>The Last Roof Most Grand Rapids Homeowners Will Ever Need</h2>
        </div>
        <p>A metal roof installed in Grand Rapids today costs $12,000–$25,000+ depending on the system and home size. That's higher upfront than asphalt — but a metal roof lasts 40–70 years, meaning the per-year cost is often lower than replacing shingles twice in the same period. For West Michigan specifically, metal has real advantages: snow sheds off naturally instead of building into ice dams, the panels expand and contract through freeze-thaw cycles without cracking, and the reflective surface reduces summer cooling costs by roughly 25%.</p>
        <p>Daniel Kamps specializes in standing seam systems — the premium metal roofing option with concealed fasteners and zero exposed leak points. Every panel is measured and cut precisely at the factory; there's no excess material and no visible penetrations where water can enter. Standing seam clip systems also accommodate thermal expansion, which is critical in Michigan where temperature swings of 40 degrees in a single day are common.</p>
        <p>Exposed fastener panels are also available as a lower-cost entry into metal roofing. They use visible screws with rubber gaskets that seal each penetration, making them better suited for outbuildings, pole barns, and lower-slope applications. For residential homes in Grand Rapids, Daniel typically recommends standing seam for its longer warranty, cleaner aesthetic, and elimination of gasket degradation over time.</p>
        <p>Every metal roofing estimate includes a 40-year cost comparison against asphalt replacement cycles so you can see the real financial picture — not just the invoice total. If you've had recurring ice dam damage on the north side of your home, metal roofing eliminates the problem at the source.</p>
        <p style="font-size: 0.8rem; color: var(--color-gray);">Last Updated: <?php echo date('F Y'); ?></p>
      </div>
      <div class="about-image">
        <picture>
          <img src="https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914926-2023-05-26__3_.webp" alt="Standing seam metal roof installation on Grand Rapids Michigan residential home" width="600" height="450" loading="lazy" style="border-radius: var(--radius-lg); width: 100%; object-fit: cover;">
        </picture>
      </div>
    </div>
  </div>
</section>

<!-- Why Choose Kamps -->
<section style="padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">Why Kamps</span>
      <h2>Metal Roofing Expertise Built for Michigan Conditions</h2>
    </div>
    <div class="why-grid">
      <div class="why-item">
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline></svg>
        </div>
        <div>
          <h3>Precision Measurements — No Waste</h3>
          <p>Panels are cut to exact length before arriving on-site. Waste is minimal, pricing is accurate, and the finished product has no field-trimmed edges that can degrade over time.</p>
        </div>
      </div>
      <div class="why-item">
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>
        </div>
        <div>
          <h3>Built for Freeze-Thaw</h3>
          <p>Michigan's temperature swings — sometimes 40 degrees in a single day — require metal roofing systems that account for thermal expansion. Standing seam clip systems accommodate movement without stress.</p>
        </div>
      </div>
      <div class="why-item">
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
        </div>
        <div>
          <h3>Long-Term Cost Analysis Provided</h3>
          <p>Every metal roofing estimate includes a 40-year cost comparison against asphalt replacement cycles so you can see the real financial picture — not just the invoice total.</p>
        </div>
      </div>
      <div class="why-item">
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
        </div>
        <div>
          <h3>30+ Years of West Michigan Installs</h3>
          <p>Daniel has installed metal roofs on Grand Rapids homes in every neighborhood and roof configuration. Experience with complex hip-and-valley layouts, dormers, and steep pitches that require extra detailing.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Mid-page CTA — CTA #2 -->
<div class="cta-banner">
  <div class="container">
    <h2>Find Out if Metal Roofing Makes Sense for Your Home</h2>
    <p>Daniel provides a detailed cost comparison — metal vs. asphalt over 40 years — so you can make the right choice for your budget and timeline.</p>
    <div style="display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap;">
      <a href="/contact" class="btn btn-accent btn-lg">Get My Free Estimate</a>
      <?php echo phone_link('btn btn-outline-white btn-lg'); ?>
    </div>
  </div>
</div>

<!-- Process Steps -->
<section style="background: var(--color-light); padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">How It Works</span>
      <h2>Metal Roof Installation: Step by Step</h2>
    </div>
    <div class="process-grid">
      <div class="process-step">
        <div class="process-number">1</div>
        <h3>Measure &amp; Design</h3>
        <p>Precise measurements of every roof plane. Panel layout is engineered for minimal seams, optimal drainage, and no visible penetrations on the finished surface.</p>
      </div>
      <div class="process-step">
        <div class="process-number">2</div>
        <h3>Custom Panel Order</h3>
        <p>Panels are cut to exact length at the factory — no field trimming waste. Color selection happens at this stage with dozens of options from multiple manufacturers.</p>
      </div>
      <div class="process-step">
        <div class="process-number">3</div>
        <h3>Deck &amp; Underlayment</h3>
        <p>Tear-off, deck inspection, and repairs. Specialty high-temp underlayment is installed — metal panels transfer heat and standard felt underlayments can fail underneath them.</p>
      </div>
      <div class="process-step">
        <div class="process-number">4</div>
        <h3>Panel Install &amp; Trim</h3>
        <p>Panels installed sequentially, seams locked, ridge cap and trim pieces fitted precisely. Every penetration receives custom metal flashing — no sealant-only details.</p>
      </div>
    </div>
  </div>
</section>

<!-- FAQ -->
<section style="padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">Frequently Asked Questions</span>
      <h2>What Grand Rapids Homeowners Ask About Metal Roofing</h2>
    </div>
    <div class="faq-grid">
      <div class="faq-item">
        <h3>How much does metal roofing cost in Grand Rapids?</h3>
        <p>$12,000–$25,000+ for full residential installation. Standing seam is on the higher end; exposed fastener costs less. Over 40 years, the per-year cost is often competitive with replacing asphalt shingles twice in the same period.</p>
      </div>
      <div class="faq-item">
        <h3>Is metal roofing loud when it rains?</h3>
        <p>With proper underlayment and insulation, a residential metal roof is no louder than asphalt during rain. The "loud tin roof" experience is from uninsulated agricultural buildings — not properly installed standing seam systems.</p>
      </div>
      <div class="faq-item">
        <h3>How long does a metal roof last in Michigan?</h3>
        <p>40–70 years with minimal maintenance. Metal handles Michigan freeze-thaw cycles better than asphalt — it expands and contracts without cracking and sheds snow without the ice dam risk that shortens shingle lifespan.</p>
      </div>
    </div>
  </div>
</section>

<!-- Closing CTA — CTA #3 -->
<section class="closing-cta">
  <div class="container">
    <h2>Get Your Metal Roofing Estimate — No Obligation</h2>
    <p>$12,000–$25,000+ installed. Free 40-year cost comparison included. Daniel Kamps personally handles every estimate in Grand Rapids and across West Michigan.</p>
    <div class="btn-row">
      <a href="/contact" class="btn btn-accent btn-lg">Schedule My Free Estimate</a>
      <?php echo phone_link('btn btn-outline-white btn-lg'); ?>
    </div>
  </div>
</section>

<?php include $_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php'; ?>
