<?php
/**
 * metal-roofing.php — Kamps Professional Roofing
 * Service Page: Metal Roofing — Grand Rapids, MI
 * Generated by Page One Insights
 */

require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/functions.php';

$breadcrumbs = [
    ['name' => 'Home',     'url' => '/'],
    ['name' => 'Services', 'url' => '/services'],
    ['name' => 'Metal Roofing', 'url' => '/services/metal-roofing'],
];

$pageTitle       = "Metal Roofing Grand Rapids MI | Standing Seam & Steel Roofs | Kamps";
$pageDescription = "Standing seam and steel metal roofing installation in Grand Rapids, MI. Lasts 40–70 years, sheds Michigan snow naturally. Free estimates from Daniel Kamps — 30+ years experience.";
$pageKeywords    = "metal roofing grand rapids mi, standing seam metal roof grand rapids, residential metal roofing grand rapids, steel roof installation kent county, metal roof replacement west michigan";
$canonicalUrl    = SITE_URL . '/services/metal-roofing';
$ogImage         = 'https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914926-2023-05-26__3_.webp';
$heroImage       = 'https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914926-2023-05-26__3_.webp';
$currentPage     = 'services';

$schemaMarkup = '[' . breadcrumb_schema($breadcrumbs) . ',' . service_schema(
    'Metal Roofing',
    'Professional standing seam and steel metal roofing installation in Grand Rapids, MI. 40–70 year lifespans, energy-efficient reflective panels, and expert installation for Michigan freeze-thaw conditions.',
    '/services/metal-roofing'
) . ',' . json_encode([
    '@context'   => 'https://schema.org',
    '@type'      => 'FAQPage',
    'mainEntity' => [
        [
            '@type'          => 'Question',
            'name'           => 'Is metal roofing loud when it rains?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'With proper underlayment and insulation between the panel and the decking, a metal roof is no louder than an asphalt shingle roof during rain. The "loud tin roof" experience comes from uninsulated agricultural buildings — not residential installations.'],
        ],
        [
            '@type'          => 'Question',
            'name'           => 'How much does metal roofing cost in Grand Rapids?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Metal roofing in Grand Rapids typically runs $12,000–$25,000+ for a full residential installation. Standing seam systems are at the higher end; exposed fastener panels cost less. The longer 40–70 year lifespan makes the per-year cost competitive with asphalt.'],
        ],
        [
            '@type'          => 'Question',
            'name'           => 'Can metal roofing be installed over existing shingles?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Sometimes, but a full tear-off is better. Installing over shingles traps moisture between layers and can void manufacturer warranties. Tear-off also lets us inspect the deck and address ventilation — both critical for a 40–70 year metal roof.'],
        ],
        [
            '@type'          => 'Question',
            'name'           => 'How long does a metal roof last in Michigan?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'A properly installed metal roof in Michigan lasts 40–70 years with minimal maintenance. Metal handles freeze-thaw cycles better than asphalt — it expands and contracts without cracking, and sheds snow naturally without the ice dam risk.'],
        ],
    ],
], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ']';

include $_SERVER['DOCUMENT_ROOT'] . '/includes/head.php';
include $_SERVER['DOCUMENT_ROOT'] . '/includes/header.php';
?>

<style>
/* ── Page-specific styles ─────────────────────────────────────────── */
.inner-hero {
    position: relative;
    min-height: 55vh;
    display: flex;
    align-items: center;
    background-size: cover;
    background-position: center;
    padding-top: 80px;
}
.inner-hero .hero-content { text-align: left; max-width: 700px; }
.breadcrumb-nav {
    background: var(--color-light);
    padding: 0.75rem 0;
    border-bottom: 1px solid var(--color-gray-light);
}
.breadcrumb {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    list-style: none;
    font-size: 0.875rem;
}
.breadcrumb-item + .breadcrumb-item::before { content: '/'; color: var(--color-gray); }
.breadcrumb-item a { color: var(--color-primary); }
.breadcrumb-item.active { color: var(--color-gray); }

.process-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 1.5rem;
}
.process-step {
    text-align: center;
    padding: 2rem 1.5rem;
    background: var(--color-white);
    border-radius: var(--radius-lg);
    box-shadow: var(--shadow-card);
}
.process-number {
    width: 56px;
    height: 56px;
    border-radius: 50%;
    background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
    color: white;
    font-family: var(--font-heading);
    font-size: 1.5rem;
    font-weight: 800;
    display: flex;
    align-items: center;
    justify-content: center;
    margin: 0 auto 1rem;
}
.why-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.5rem;
}
.why-item {
    display: flex;
    gap: 1rem;
    padding: 1.5rem;
    background: var(--color-white);
    border-radius: var(--radius-lg);
    box-shadow: var(--shadow-card);
}
.why-icon {
    flex-shrink: 0;
    width: 48px;
    height: 48px;
    border-radius: var(--radius-md);
    background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
}
.metal-compare {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1.5rem;
    margin-top: var(--space-8);
}
.metal-card {
    border-radius: var(--radius-lg);
    overflow: hidden;
    box-shadow: var(--shadow-card);
}
.metal-card-header {
    background: var(--color-primary);
    color: white;
    padding: 1rem 1.5rem;
    font-family: var(--font-heading);
    font-weight: 700;
    font-size: 1.1rem;
}
.metal-card-header.accent-bg { background: linear-gradient(135deg, var(--color-primary), var(--color-accent)); }
.metal-card-body {
    padding: 1.5rem;
    background: var(--color-white);
}
.metal-card-body ul {
    list-style: none;
    padding: 0;
    margin: 0;
}
.metal-card-body ul li {
    padding: 0.4rem 0;
    border-bottom: 1px solid var(--color-gray-light);
    font-size: 0.9rem;
    display: flex;
    gap: 0.5rem;
    align-items: flex-start;
}
.metal-card-body ul li:last-child { border-bottom: none; }
.metal-card-body ul li::before {
    content: '✓';
    color: var(--color-accent);
    font-weight: 700;
    flex-shrink: 0;
}
.stats-row {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 1.5rem;
    margin-top: var(--space-10);
}
.stat-block {
    text-align: center;
    padding: 2rem 1rem;
    background: var(--color-white);
    border-radius: var(--radius-lg);
    box-shadow: var(--shadow-card);
}
.stat-block .stat-num {
    font-family: var(--font-heading);
    font-size: clamp(2rem, 4vw, 2.8rem);
    font-weight: 800;
    color: var(--color-accent);
    line-height: 1;
}
.stat-block .stat-label {
    font-size: 0.85rem;
    color: var(--color-text-light);
    margin-top: 0.4rem;
}
.faq-grid { display: grid; gap: 1rem; }
.faq-item {
    background: var(--color-white);
    border-radius: var(--radius-lg);
    box-shadow: var(--shadow-card);
    overflow: hidden;
}
.faq-question {
    padding: 1.25rem 1.5rem;
    font-family: var(--font-heading);
    font-weight: 700;
    font-size: 1rem;
    color: var(--color-primary);
    display: flex;
    align-items: flex-start;
    gap: 0.75rem;
}
.faq-icon {
    flex-shrink: 0;
    width: 28px;
    height: 28px;
    border-radius: 50%;
    background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
    color: white;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 0.8rem;
    font-weight: 800;
    margin-top: 1px;
}
.faq-answer {
    padding: 0 1.5rem 1.25rem 3.75rem;
    font-size: 0.95rem;
    line-height: 1.65;
    color: var(--color-text-light);
}
.closing-cta {
    background: var(--color-dark);
    padding: var(--space-16) 0;
    text-align: center;
    position: relative;
    overflow: hidden;
}
.closing-cta::before {
    content: '';
    position: absolute;
    inset: 0;
    background: url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.04'/%3E%3C/svg%3E");
    opacity: 0.06;
    pointer-events: none;
}
@media (max-width: 768px) {
    .process-grid { grid-template-columns: 1fr 1fr; }
    .why-grid { grid-template-columns: 1fr; }
    .metal-compare { grid-template-columns: 1fr; }
    .stats-row { grid-template-columns: 1fr; }
}
@media (max-width: 480px) {
    .process-grid { grid-template-columns: 1fr; }
    .stats-row { grid-template-columns: 1fr 1fr; }
}
</style>

<!-- ── Hero ───────────────────────────────────────────────────────────── -->
<section class="inner-hero hero-overlay"
         style="background-image: url('https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914926-2023-05-26__3_.webp');"
         aria-label="Metal roofing service hero">
    <div class="container">
        <div class="hero-content">
            <p class="hero-eyebrow eyebrow" data-animate="fade-up">Roofing Materials</p>
            <h1 data-animate="fade-up">Metal Roofing<br><span style="color: var(--color-accent);">Grand Rapids, MI</span></h1>
            <p class="hero-subtitle" data-animate="fade-up">
                A standing seam metal roof installed on a Grand Rapids home today will still be performing when your asphalt shingles would have been replaced twice over.
            </p>
            <div class="hero-buttons" data-animate="fade-up">
                <a href="/contact" class="btn btn-accent btn-lg magnetic">Get a Free Metal Roof Estimate</a>
                <a href="tel:" class="btn btn-outline-white btn-lg">Call Daniel Kamps</a>
            </div>
            <div class="hero-trust" data-animate="fade-up">
                <div class="hero-trust-item">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>
                    Licensed &amp; Insured
                </div>
                <div class="hero-trust-item">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
                    40–70 Year Lifespans
                </div>
                <div class="hero-trust-item">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="20 6 9 17 4 12"></polyline></svg>
                    Standing Seam Specialists
                </div>
            </div>
        </div>
    </div>
</section>

<!-- ── Breadcrumb ───────────────────────────────────────────────────── -->
<?php echo breadcrumb_nav($breadcrumbs); ?>

<!-- ── Ticker Strip ─────────────────────────────────────────────────── -->
<div class="ticker-strip" aria-hidden="true">
    <div class="ticker-track">
        <span>Standing Seam Metal</span><span class="ticker-sep">✦</span>
        <span>40–70 Year Lifespan</span><span class="ticker-sep">✦</span>
        <span>Snow Sheds Naturally</span><span class="ticker-sep">✦</span>
        <span>Energy Efficient</span><span class="ticker-sep">✦</span>
        <span>Freeze-Thaw Resistant</span><span class="ticker-sep">✦</span>
        <span>West Michigan Specialists</span><span class="ticker-sep">✦</span>
        <span>Grand Rapids, MI</span><span class="ticker-sep">✦</span>
        <span>Custom-Cut Panels</span><span class="ticker-sep">✦</span>
        <!-- duplicate for seamless loop -->
        <span>Standing Seam Metal</span><span class="ticker-sep">✦</span>
        <span>40–70 Year Lifespan</span><span class="ticker-sep">✦</span>
        <span>Snow Sheds Naturally</span><span class="ticker-sep">✦</span>
        <span>Energy Efficient</span><span class="ticker-sep">✦</span>
        <span>Freeze-Thaw Resistant</span><span class="ticker-sep">✦</span>
        <span>West Michigan Specialists</span><span class="ticker-sep">✦</span>
        <span>Grand Rapids, MI</span><span class="ticker-sep">✦</span>
        <span>Custom-Cut Panels</span><span class="ticker-sep">✦</span>
    </div>
</div>

<!-- ── Intro / Answer Block ─────────────────────────────────────────── -->
<section style="padding: var(--space-16) 0; background: var(--color-white);">
    <div class="container">
        <div class="split" style="align-items: center; gap: var(--space-12);">

            <div class="img-reveal" data-animate="wipe-right" style="border-radius: var(--radius-lg); overflow: hidden; box-shadow: var(--shadow-lg);">
                <picture>
                    <source srcset="https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914926-2023-05-26__3_.webp" type="image/webp">
                    <img src="https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914926-2023-05-26__3_.webp"
                         alt="Standing seam metal roof installation on Grand Rapids Michigan residential home"
                         width="700" height="500" loading="lazy">
                </picture>
            </div>

            <div data-animate="fade-up">
                <p class="eyebrow">Metal Roofing in Grand Rapids</p>
                <h2>The Last Roof Most Grand Rapids Homeowners Will Ever Need</h2>
                <div class="prose" style="margin-top: var(--space-6);">
                    <p>A metal roof installed in Grand Rapids today costs <strong>$12,000–$25,000+</strong> depending on the system and home size. That's higher upfront than asphalt — but a metal roof lasts 40–70 years, meaning the per-year cost is often lower than replacing shingles twice in the same period.</p>
                    <p style="margin-top: var(--space-4);">For West Michigan specifically, metal has real advantages: snow sheds off naturally instead of building into ice dams, the panels expand and contract through freeze-thaw cycles without cracking, and the reflective surface reduces summer cooling costs. If you've had recurring ice dam damage on the north side of your Grand Rapids home, metal roofing eliminates the problem at the source.</p>
                    <p style="margin-top: var(--space-4);">Daniel Kamps specializes in standing seam systems — the premium metal roofing option with concealed fasteners and no exposed leak points. Every panel is measured and cut precisely; there's no excess material and no visible penetrations where water can enter.</p>
                </div>
                <div style="margin-top: var(--space-8); display: flex; gap: var(--space-4); flex-wrap: wrap;">
                    <a href="/contact" class="btn btn-primary">Get a Metal Roof Estimate</a>
                    <a href="/services/asphalt-shingle-roofing" class="btn btn-outline-white" style="color: var(--color-primary); border-color: var(--color-primary);">Compare: Asphalt Shingles</a>
                </div>
            </div>

        </div>
    </div>
</section>

<!-- ── Stats Row ─────────────────────────────────────────────────────── -->
<section style="padding: var(--space-12) 0; background: var(--color-primary);">
    <div class="container">
        <div class="stats-row">
            <div class="stat-block" data-animate="fade-up">
                <div class="stat-num">40–70</div>
                <div class="stat-label">Year lifespan — 2–3x longer than asphalt shingles</div>
            </div>
            <div class="stat-block" data-animate="fade-up">
                <div class="stat-num">~25%</div>
                <div class="stat-label">Energy cost reduction from solar-reflective panels in summer</div>
            </div>
            <div class="stat-block" data-animate="fade-up">
                <div class="stat-num">0</div>
                <div class="stat-label">Exposed fasteners with standing seam — no leak points</div>
            </div>
        </div>
    </div>
</section>

<!-- ── System Comparison ─────────────────────────────────────────────── -->
<section style="padding: var(--space-16) 0; background: var(--color-light);">
    <div class="container">
        <div class="section-header" data-animate="fade-up">
            <p class="eyebrow">Choosing Your System</p>
            <h2>Standing Seam vs. Exposed Fastener Metal Panels</h2>
            <p class="prose-centered" style="margin-top: var(--space-4); text-align: center;">Two metal roofing systems with different price points and performance profiles. Daniel walks you through both during your free estimate.</p>
        </div>

        <div class="metal-compare" data-animate="fade-up">
            <div class="metal-card">
                <div class="metal-card-header">Exposed Fastener Panels</div>
                <div class="metal-card-body">
                    <ul>
                        <li>Lower cost — good entry into metal roofing</li>
                        <li>Screws visible on panel surface</li>
                        <li>Rubber gaskets seal fasteners — degrade over 15–20 years</li>
                        <li>Better suited for low-slope and outbuildings</li>
                        <li>Faster installation</li>
                        <li>Shorter warranty than standing seam</li>
                    </ul>
                </div>
            </div>
            <div class="metal-card">
                <div class="metal-card-header accent-bg">Standing Seam — Recommended for Residential</div>
                <div class="metal-card-body">
                    <ul>
                        <li>Concealed fasteners — no exposed screws or rubber gaskets</li>
                        <li>Panels interlock via raised seams — no penetrations</li>
                        <li>Handles thermal expansion and contraction without stress cracking</li>
                        <li>Clean, premium aesthetic for residential applications</li>
                        <li>Longest-lasting metal roofing system available</li>
                        <li>Full manufacturer warranties — 40+ years on premium systems</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- ── Mid-Page CTA Banner ───────────────────────────────────────────── -->
<section class="cta-banner" aria-label="Request a free metal roofing estimate">
    <div class="container" style="text-align: center;">
        <p class="eyebrow" style="color: rgba(255,255,255,0.7);">Long-Term Investment</p>
        <h2 style="color: white; margin-bottom: var(--space-4);">Find Out if Metal Roofing Makes Sense for Your Home</h2>
        <p style="color: rgba(255,255,255,0.85); max-width: 580px; margin: 0 auto var(--space-8); line-height: 1.6;">
            Daniel provides a detailed cost comparison — metal vs. asphalt over 40 years — so you can make the right choice for your budget and timeline.
        </p>
        <div style="display: flex; gap: var(--space-4); justify-content: center; flex-wrap: wrap;">
            <a href="/contact" class="btn btn-accent btn-lg">Get My Free Estimate</a>
            <a href="tel:" class="btn btn-outline-white btn-lg">Call Now</a>
        </div>
    </div>
</section>

<!-- ── Installation Process ─────────────────────────────────────────── -->
<section style="padding: var(--space-16) 0; background: var(--color-light);">
    <div class="container">
        <div class="section-header" data-animate="fade-up">
            <p class="eyebrow">How It Works</p>
            <h2>Metal Roof Installation: Step by Step</h2>
        </div>
        <div class="process-grid" style="margin-top: var(--space-10);">
            <div class="process-step" data-animate="fade-up">
                <div class="process-number">1</div>
                <h3>Measure &amp; Design</h3>
                <p style="font-size: 0.9rem; color: var(--color-text-light); margin-top: var(--space-2);">Precise measurements of every roof plane. Panel layout is engineered for minimal seams, optimal drainage, and no visible penetrations on the finished surface.</p>
            </div>
            <div class="process-step" data-animate="fade-up">
                <div class="process-number">2</div>
                <h3>Custom Panel Order</h3>
                <p style="font-size: 0.9rem; color: var(--color-text-light); margin-top: var(--space-2);">Panels are cut to exact length at the factory — no field trimming waste. Color selection happens at this stage; dozens of options available from multiple manufacturers.</p>
            </div>
            <div class="process-step" data-animate="fade-up">
                <div class="process-number">3</div>
                <h3>Deck &amp; Underlayment</h3>
                <p style="font-size: 0.9rem; color: var(--color-text-light); margin-top: var(--space-2);">Tear-off, deck inspection, and repairs. Specialty high-temp underlayment is installed — metal panels transfer heat and standard felt underlayments can fail underneath them.</p>
            </div>
            <div class="process-step" data-animate="fade-up">
                <div class="process-number">4</div>
                <h3>Panel Install &amp; Trim</h3>
                <p style="font-size: 0.9rem; color: var(--color-text-light); margin-top: var(--space-2);">Panels installed sequentially, seams locked, ridge cap and trim pieces fitted precisely. Every penetration (vents, skylights) receives custom metal flashing — no sealant-only details.</p>
            </div>
        </div>
    </div>
</section>

<!-- ── Why Kamps ─────────────────────────────────────────────────────── -->
<section style="padding: var(--space-16) 0; background: var(--color-white);">
    <div class="container">
        <div class="section-header" data-animate="fade-up">
            <p class="eyebrow">Why It Matters</p>
            <h2>Metal Roofing Expertise Built for Michigan Conditions</h2>
        </div>
        <div class="why-grid" style="margin-top: var(--space-10);">
            <div class="why-item" data-animate="fade-up">
                <div class="why-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"></polyline></svg>
                </div>
                <div>
                    <h3 style="font-size: 1rem; margin-bottom: 0.4rem;">Precision Measurements — No Waste</h3>
                    <p style="font-size: 0.9rem; color: var(--color-text-light);">Panels are cut to exact length before arriving on-site. Waste is minimal, pricing is accurate, and the finished product has no field-trimmed edges that can degrade over time.</p>
                </div>
            </div>
            <div class="why-item" data-animate="fade-up">
                <div class="why-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>
                </div>
                <div>
                    <h3 style="font-size: 1rem; margin-bottom: 0.4rem;">Built for Freeze-Thaw</h3>
                    <p style="font-size: 0.9rem; color: var(--color-text-light);">Michigan's temperature swings — sometimes 40°F in a single day — require metal roofing systems that account for thermal expansion. Standing seam clip systems accommodate movement without stress.</p>
                </div>
            </div>
            <div class="why-item" data-animate="fade-up">
                <div class="why-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="12" y1="1" x2="12" y2="23"></line><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>
                </div>
                <div>
                    <h3 style="font-size: 1rem; margin-bottom: 0.4rem;">Long-Term Cost Analysis Provided</h3>
                    <p style="font-size: 0.9rem; color: var(--color-text-light);">Every metal roofing estimate includes a 40-year cost comparison against asphalt replacement cycles so you can see the real financial picture — not just the invoice total.</p>
                </div>
            </div>
            <div class="why-item" data-animate="fade-up">
                <div class="why-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
                </div>
                <div>
                    <h3 style="font-size: 1rem; margin-bottom: 0.4rem;">30+ Years of West Michigan Installs</h3>
                    <p style="font-size: 0.9rem; color: var(--color-text-light);">Daniel has installed metal roofs on Grand Rapids homes in every neighborhood and roof configuration. Experience with complex hip-and-valley layouts, dormers, and steep pitches that require extra detailing.</p>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- ── FAQ ──────────────────────────────────────────────────────────── -->
<section style="padding: var(--space-16) 0; background: var(--color-light);">
    <div class="container">
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: var(--space-12); align-items: start;">
            <div data-animate="fade-up">
                <p class="eyebrow">Common Questions</p>
                <h2>What Grand Rapids Homeowners Ask About Metal Roofing</h2>
                <p class="prose" style="margin-top: var(--space-4);">
                    Straight answers on noise, cost, installation, and lifespan — from someone who has installed metal roofs in West Michigan for three decades.
                </p>
                <p style="margin-top: var(--space-4); font-size: 0.9rem; color: var(--color-text-light);">Last Updated: April 2026</p>
                <a href="/contact" class="btn btn-primary" style="margin-top: var(--space-6);">Ask a Specific Question</a>
            </div>
            <div class="faq-grid" data-animate="fade-up">
                <div class="faq-item">
                    <div class="faq-question"><div class="faq-icon">Q</div>Is metal roofing loud when it rains?</div>
                    <div class="faq-answer">With proper underlayment and insulation, a residential metal roof is no louder than asphalt during rain. The "loud tin roof" experience is from uninsulated agricultural buildings — not properly installed standing seam systems.</div>
                </div>
                <div class="faq-item">
                    <div class="faq-question"><div class="faq-icon">Q</div>How much does metal roofing cost in Grand Rapids?</div>
                    <div class="faq-answer">$12,000–$25,000+ for full residential installation. Standing seam is on the higher end; exposed fastener costs less. Over 40 years, the per-year cost is often competitive with replacing asphalt shingles twice in the same period.</div>
                </div>
                <div class="faq-item">
                    <div class="faq-question"><div class="faq-icon">Q</div>Can metal be installed over existing shingles?</div>
                    <div class="faq-answer">Sometimes, but a full tear-off is better. Installing over shingles traps moisture and can void warranties. Tear-off also allows deck inspection — critical before a 40–70 year roof goes down.</div>
                </div>
                <div class="faq-item">
                    <div class="faq-question"><div class="faq-icon">Q</div>How long does a metal roof last in Michigan?</div>
                    <div class="faq-answer">40–70 years with minimal maintenance. Metal handles Michigan freeze-thaw cycles better than asphalt — it expands and contracts without cracking and sheds snow without the ice dam risk that shortens shingle lifespan.</div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- ── Closing CTA ───────────────────────────────────────────────────── -->
<section class="closing-cta">
    <div class="container" style="position: relative; z-index: 1;">
        <div style="max-width: 680px; margin: 0 auto; text-align: center;" data-animate="fade-up">
            <p class="eyebrow" style="color: var(--color-accent);">A Roof That Outlasts Everything Else</p>
            <h2 style="color: white; margin-bottom: var(--space-4);">Get Your Metal Roofing Estimate — No Obligation</h2>
            <p style="color: rgba(255,255,255,0.75); max-width: 540px; margin: 0 auto var(--space-8); line-height: 1.65;">
                $12,000–$25,000+ installed. Free 40-year cost comparison included. Daniel Kamps personally handles every estimate in Grand Rapids and across West Michigan.
            </p>
            <div style="display: flex; gap: var(--space-4); justify-content: center; flex-wrap: wrap;">
                <a href="/contact" class="btn btn-accent btn-lg">Schedule My Free Estimate</a>
                <a href="tel:" class="btn btn-outline-white btn-lg">Call Daniel Kamps</a>
            </div>
            <p style="color: rgba(255,255,255,0.5); font-size: 0.8rem; margin-top: var(--space-6);">Licensed &amp; Insured · Grand Rapids, MI · Kent County &amp; West Michigan</p>
        </div>
    </div>
</section>

<?php include $_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php'; ?>
