<?php
/**
 * slate-roof-installation.php — Kamps Professional Roofing
 * Service Page: Slate Roof Installation — Grand Rapids, MI
 * Generated by Page One Insights
 */

require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/functions.php';

$breadcrumbs = [
    ['name' => 'Home',     'url' => '/'],
    ['name' => 'Services', 'url' => '/services'],
    ['name' => 'Slate Roof Installation', 'url' => '/services/slate-roof-installation'],
];

$pageTitle       = "Slate Roof Installation Grand Rapids MI | Kamps Roofing";
$pageDescription = "Natural slate roof installation in Grand Rapids, MI. 75–150 year lifespans — the most durable roofing material available. Structural assessments included. Free estimates from Daniel Kamps.";
$pageKeywords    = "slate roof installation grand rapids mi, natural slate roofing grand rapids, premium slate roof grand rapids, luxury roofing materials michigan, slate roof replacement west michigan";
$canonicalUrl    = SITE_URL . '/services/slate-roof-installation';
$ogImage         = 'https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470057340_122125694816552346_3172886313220324016_n.jpg';
$heroImage       = 'https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470057340_122125694816552346_3172886313220324016_n.jpg';
$currentPage     = 'services';

$schemaMarkup = '[' . breadcrumb_schema($breadcrumbs) . ',' . service_schema(
    'Slate Roof Installation',
    'Natural slate roof installation in Grand Rapids, MI. The longest-lasting roofing material available — 75 to 150 years. Structural assessments included. Expert sourcing and precision hand-set installation by Daniel Kamps.',
    '/services/slate-roof-installation'
) . ',' . json_encode([
    '@context'   => 'https://schema.org',
    '@type'      => 'FAQPage',
    'mainEntity' => [
        [
            '@type'          => 'Question',
            'name'           => 'How long does slate roofing last?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Natural slate lasts 75–150 years when properly installed and maintained. Some slate roofs in the eastern United States are over a century old and still performing. In Michigan, properly installed soft slate lasts 75–100 years; hard slate (Vermont, Pennsylvania) can exceed 150 years.'],
        ],
        [
            '@type'          => 'Question',
            'name'           => 'How much does slate roofing cost in Grand Rapids?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Slate roofing in Grand Rapids typically runs $20,000–$50,000+ for full installation. Cost depends on slate type, roof complexity, and whether structural reinforcement is needed. The per-year cost over a 100-year lifespan is often comparable to replacing asphalt shingles four times.'],
        ],
        [
            '@type'          => 'Question',
            'name'           => 'Can slate be repaired if one tile breaks?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Yes — individual slate tiles can be replaced without disturbing the rest of the roof. A skilled slate roofer removes the damaged tile, installs a new one with a slate hook, and seals it properly. This is one of slate\'s advantages over other materials — repairability without full re-roof.'],
        ],
    ],
], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ']';

include $_SERVER['DOCUMENT_ROOT'] . '/includes/head.php';
include $_SERVER['DOCUMENT_ROOT'] . '/includes/header.php';
?>

<style>
.inner-hero {
  position: relative;
  min-height: 55vh;
  display: flex;
  align-items: center;
  background-size: cover;
  background-position: center;
  padding-top: 80px;
}
.inner-hero .hero-content { text-align: left; max-width: 700px; }
.process-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.process-step {
  text-align: center;
  padding: 2rem 1.5rem;
  background: var(--color-white);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-card);
}
.process-number {
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  color: white;
  font-family: var(--font-heading);
  font-size: 1.5rem;
  font-weight: 800;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 1rem;
}
.process-step h3 { font-size: 1rem; margin-bottom: 0.5rem; color: var(--color-dark); }
.process-step p { font-size: 0.875rem; color: var(--color-gray); line-height: 1.5; }
.why-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.why-item {
  display: flex;
  gap: 1rem;
  padding: 1.5rem;
  background: var(--color-white);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-card);
}
.why-icon {
  flex-shrink: 0;
  width: 48px;
  height: 48px;
  border-radius: var(--radius-md);
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
}
.why-item h3 { font-size: 1rem; margin-bottom: 0.4rem; color: var(--color-dark); }
.why-item p { font-size: 0.875rem; color: var(--color-gray); line-height: 1.5; }
.faq-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.faq-item {
  background: var(--color-white);
  border-radius: var(--radius-lg);
  padding: 1.75rem;
  box-shadow: var(--shadow-card);
  border-left: 4px solid var(--color-accent);
}
.faq-item h3 { font-size: 1rem; margin-bottom: 0.75rem; color: var(--color-dark); }
.faq-item p { font-size: 0.9rem; color: var(--color-gray); line-height: 1.6; }
@media (max-width: 1023px) {
  .process-grid { grid-template-columns: 1fr 1fr; }
}
@media (max-width: 767px) {
  .why-grid { grid-template-columns: 1fr; }
}
@media (max-width: 480px) {
  .process-grid { grid-template-columns: 1fr; }
}
</style>

<?php echo breadcrumb_nav($breadcrumbs); ?>

<!-- Hero — CTA #1 -->
<section class="inner-hero" style="background-image: url('https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470057340_122125694816552346_3172886313220324016_n.jpg');">
  <div class="hero-overlay"></div>
  <div class="container">
    <div class="hero-content">
      <span class="hero-eyebrow">Kamps Professional Roofing</span>
      <h1>Slate Roof Installation Grand Rapids, MI</h1>
      <p class="hero-subtitle">The longest-lasting roofing material available — 75 to 150 years on a properly prepared structure. One of the few West Michigan contractors with genuine slate expertise.</p>
      <div class="hero-buttons">
        <a href="/contact" class="btn btn-accent btn-lg">Get a Free Estimate</a>
        <?php echo phone_link('btn btn-outline-white btn-lg', 'Call Now'); ?>
      </div>
      <div class="hero-trust">
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg> Licensed &amp; Insured</span>
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg> 30+ Years Experience</span>
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="20 6 9 17 4 12"></polyline></svg> Free Estimates</span>
      </div>
    </div>
  </div>
</section>

<!-- Service Detail -->
<section style="background: var(--color-light); padding: var(--space-16) 0;">
  <div class="container">
    <div class="about-split" data-animate>
      <div class="about-content">
        <div class="section-header" style="text-align:left; margin-bottom: 2rem;">
          <span class="eyebrow">Natural Slate in Grand Rapids</span>
          <h2>A Roof That May Outlast the House Itself</h2>
        </div>
        <p>Natural slate is the most durable roofing material available. A Grand Rapids home with a properly installed slate roof today — backed by correct structural prep and quality sourcing — could still be performing when your grandchildren inherit the property. The 75-to-150-year lifespan isn't marketing language; there are slate roofs on century-old homes across Michigan's historic districts still doing their job.</p>
        <p>The investment reflects the outcome: <strong>$20,000-$50,000+</strong> for a full slate installation in the Grand Rapids area. That range accounts for slate type (soft vs. hard), roof complexity, and the structural reinforcement most homes need — slate weighs 700-1,000 lbs per square, three to four times heavier than asphalt. Every Kamps slate estimate includes a structural assessment because it's not optional; it's the foundation that makes everything else work.</p>
        <p>Daniel Kamps is one of the few West Michigan roofing contractors who sources directly from quality quarries in Vermont and Pennsylvania, then handles the hand-set installation that slate requires. This is not a material for subcontracting or learning on the job. Each slate is individually fastened, ridge and hip tiles are set in mortar, and flashing at every penetration is custom-fabricated metal — no caulk shortcuts on a roof meant to last a century.</p>
        <p>Individual broken slates can be replaced without disturbing the rest of the roof — one of the practical advantages over other premium materials. That repairability, combined with the extraordinary lifespan, makes slate one of the lowest cost-per-year roofing options available when measured across the full life of the material.</p>
        <p style="font-size: 0.8rem; color: var(--color-gray);">Last Updated: <?php echo date('F Y'); ?></p>
      </div>
      <div class="about-image">
        <picture>
          <img src="https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470057340_122125694816552346_3172886313220324016_n.jpg" alt="Natural slate roof installation on Grand Rapids Michigan historic home by Kamps Professional Roofing" width="600" height="450" loading="lazy" style="border-radius: var(--radius-lg); width: 100%; object-fit: cover;">
        </picture>
      </div>
    </div>
  </div>
</section>

<!-- Why Choose Kamps -->
<section style="padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">Why Kamps</span>
      <h2>Why Slate Requires a Specialist — and Why Kamps Is That Specialist</h2>
    </div>
    <div class="why-grid">
      <div class="why-item" data-animate>
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>
        </div>
        <div>
          <h3>One of Few West Michigan Slate Contractors</h3>
          <p>Slate is rare enough in Grand Rapids that most roofers have never installed it. Daniel has — repeatedly, on historic and custom homes. The learning curve for slate is steep; you don't want a contractor working it out on your project.</p>
        </div>
      </div>
      <div class="why-item" data-animate>
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="20 6 9 17 4 12"></polyline></svg>
        </div>
        <div>
          <h3>Quality Quarry Sourcing</h3>
          <p>Not all slate is equal. Soft slate from certain regions degrades faster under Michigan's freeze-thaw cycles. Daniel sources from quarries with documented track records for northern climate performance.</p>
        </div>
      </div>
      <div class="why-item" data-animate>
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
        </div>
        <div>
          <h3>Structural Assessment — No Surprises</h3>
          <p>Every slate estimate includes a framing evaluation. If reinforcement is needed, it's scoped and priced before you commit. No contractor should quote slate without seeing what's underneath — and Kamps doesn't.</p>
        </div>
      </div>
      <div class="why-item" data-animate>
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
        </div>
        <div>
          <h3>Workmanship That Matches the Material</h3>
          <p>Slate is the most premium roofing material available. Daniel sets every slate individually, mortars ridge and hip tiles correctly, and takes no shortcuts on flashing details that would compromise a 100-year roof.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Mid-page CTA — CTA #2 -->
<div class="cta-banner">
  <div class="container">
    <h2>Get a Slate Roofing Estimate — Structural Assessment Included</h2>
    <p>Most Grand Rapids contractors don't offer slate. Daniel Kamps does — with sourcing from quality quarries, structural prep, and the installation experience this material demands.</p>
    <div style="display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap;">
      <a href="/contact" class="btn btn-accent btn-lg">Schedule My Free Estimate</a>
      <?php echo phone_link('btn btn-outline-white btn-lg'); ?>
    </div>
  </div>
</div>

<!-- Process Steps -->
<section style="background: var(--color-light); padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">How It Works</span>
      <h2>Slate Roof Installation: A Deliberate, Methodical Process</h2>
    </div>
    <div class="process-grid">
      <div class="process-step" data-animate>
        <div class="process-number">1</div>
        <h3>Structural &amp; Design Consultation</h3>
        <p>Framing is assessed for load capacity. Slate type, color, and size are selected. This consultation determines whether reinforcement is needed and finalizes the scope before material is ordered.</p>
      </div>
      <div class="process-step" data-animate>
        <div class="process-number">2</div>
        <h3>Slate Sourcing &amp; Selection</h3>
        <p>Slate is sourced from reputable quarries — Vermont, Pennsylvania, and select imported sources. Each lot is reviewed for quality and freeze-thaw suitability for Michigan conditions.</p>
      </div>
      <div class="process-step" data-animate>
        <div class="process-number">3</div>
        <h3>Structural Prep</h3>
        <p>Framing reinforcement completed if required. Existing roofing removed, deck inspected, specialty underlayment installed. Flashing at all penetrations is custom-fabricated metal.</p>
      </div>
      <div class="process-step" data-animate>
        <div class="process-number">4</div>
        <h3>Individual Slate Installation</h3>
        <p>Each slate is hand-set and individually fastened. Ridge and hip tiles are set in mortar. The process is slower than shingles — precision is the point.</p>
      </div>
    </div>
  </div>
</section>

<!-- FAQ -->
<section style="padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">Frequently Asked Questions</span>
      <h2>What Grand Rapids Homeowners Ask About Slate Roofing</h2>
    </div>
    <div class="faq-grid">
      <div class="faq-item" data-animate>
        <h3>How long does slate roofing last?</h3>
        <p>Natural slate lasts 75-150 years when properly installed. Soft slate (New York, Virginia) runs 75-100 years; hard slate (Vermont, Pennsylvania) can exceed 150. Some slate roofs on historic Michigan homes are over a century old and still performing.</p>
      </div>
      <div class="faq-item" data-animate>
        <h3>How much does slate roofing cost in Grand Rapids?</h3>
        <p>$20,000-$50,000+ for full installation. Cost depends on slate type, roof complexity, and structural reinforcement needs. Over a 100-year lifespan, the per-year cost is often comparable to replacing asphalt shingles four times in the same period.</p>
      </div>
      <div class="faq-item" data-animate>
        <h3>Can slate be repaired if one tile breaks?</h3>
        <p>Yes — individual slates can be replaced without touching the rest of the roof. A slate hook removes the damaged tile, a new one is inserted and fastened, and the repair is invisible. This repairability is one of slate's practical advantages over many other materials.</p>
      </div>
    </div>
  </div>
</section>

<!-- Closing CTA — CTA #3 -->
<section style="background: var(--color-dark); padding: 5rem 0;">
  <div class="container" style="text-align: center;">
    <h2 style="color: white; margin-bottom: 1rem;">Get a Free Slate Roofing Estimate in Grand Rapids</h2>
    <p style="color: rgba(255,255,255,0.8); max-width: 600px; margin: 0 auto 2rem;">$20,000-$50,000+ installed. Structural assessment included at no charge. Daniel Kamps — one of the few West Michigan contractors with genuine slate installation expertise.</p>
    <div style="display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap;">
      <a href="/contact" class="btn btn-accent btn-lg">Schedule My Free Estimate</a>
      <?php echo phone_link('btn btn-outline-white btn-lg'); ?>
    </div>
  </div>
</section>

<?php include $_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php'; ?>
