<?php
/**
 * tile-roof-installation.php — Kamps Professional Roofing
 * Service Page: Tile Roof Installation — Grand Rapids, MI
 * Generated by Page One Insights
 */

require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/functions.php';

$breadcrumbs = [
    ['name' => 'Home',     'url' => '/'],
    ['name' => 'Services', 'url' => '/services'],
    ['name' => 'Tile Roof Installation', 'url' => '/services/tile-roof-installation'],
];

$pageTitle       = "Tile Roof Installation Grand Rapids MI | Kamps Roofing";
$pageDescription = "Clay and concrete tile roof installation in Grand Rapids, MI. 50+ year lifespans with proper structural prep for Michigan's freeze-thaw climate. Free estimates — Daniel Kamps.";
$pageKeywords    = "tile roof installation grand rapids, clay tile roofing mi, concrete tile roof grand rapids, residential tile roofing kent county, tile roof replacement west michigan";
$canonicalUrl    = SITE_URL . '/services/tile-roof-installation';
$ogImage         = 'https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470039241_122125599908552346_4973791851142167865_n.jpg';
$heroImage       = 'https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470039241_122125599908552346_4973791851142167865_n.jpg';
$currentPage     = 'services';

$schemaMarkup = '[' . breadcrumb_schema($breadcrumbs) . ',' . service_schema(
    'Tile Roof Installation',
    'Professional clay and concrete tile roof installation in Grand Rapids, MI. Structural assessments included. Freeze-thaw resistant installation methods for Michigan climate. 50+ year lifespans.',
    '/services/tile-roof-installation'
) . ',' . json_encode([
    '@context'   => 'https://schema.org',
    '@type'      => 'FAQPage',
    'mainEntity' => [
        [
            '@type'          => 'Question',
            'name'           => 'Is tile roofing practical in Michigan?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Yes, with proper installation. The key is selecting freeze-thaw resistant tile — not all tile products are rated for Michigan\'s temperature swings. Kamps specifies products tested for northern climates and uses installation methods that account for thermal movement and moisture.'],
        ],
        [
            '@type'          => 'Question',
            'name'           => 'How much does a tile roof cost in Grand Rapids?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Tile roof installation in Grand Rapids typically runs $15,000–$35,000+ depending on tile type (concrete vs. clay) and roof complexity. Clay is more expensive than concrete; both require structural assessment before pricing is finalized.'],
        ],
        [
            '@type'          => 'Question',
            'name'           => 'How long do tile roofs last?',
            'acceptedAnswer' => ['@type' => 'Answer', 'text' => 'Clay tile lasts 50–100 years; concrete tile typically 40–50 years. Both significantly outlast asphalt shingles. Lifespan depends on proper installation, adequate structural support, and correct flashing at all penetrations.'],
        ],
    ],
], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ']';

include $_SERVER['DOCUMENT_ROOT'] . '/includes/head.php';
include $_SERVER['DOCUMENT_ROOT'] . '/includes/header.php';
?>

<style>
.process-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.process-step {
  text-align: center;
  padding: 2rem 1.5rem;
  background: var(--color-white);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-card);
}
.process-number {
  width: 56px;
  height: 56px;
  border-radius: 50%;
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  color: white;
  font-family: var(--font-heading);
  font-size: 1.5rem;
  font-weight: 800;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 1rem;
}
.process-step h3 { font-size: 1rem; margin-bottom: 0.5rem; color: var(--color-dark); }
.process-step p { font-size: 0.875rem; color: var(--color-gray); line-height: 1.5; }
.why-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.why-item {
  display: flex;
  gap: 1rem;
  padding: 1.5rem;
  background: var(--color-white);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-card);
}
.why-icon {
  flex-shrink: 0;
  width: 48px;
  height: 48px;
  border-radius: var(--radius-md);
  background: linear-gradient(135deg, var(--color-primary), var(--color-accent));
  display: flex;
  align-items: center;
  justify-content: center;
  color: white;
}
.why-item h3 { font-size: 1rem; margin-bottom: 0.4rem; color: var(--color-dark); }
.why-item p { font-size: 0.875rem; color: var(--color-gray); line-height: 1.5; }
.faq-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: 1.5rem;
  margin-top: 2.5rem;
}
.faq-item {
  background: var(--color-white);
  border-radius: var(--radius-lg);
  padding: 1.75rem;
  box-shadow: var(--shadow-card);
  border-left: 4px solid var(--color-accent);
}
.faq-item h3 { font-size: 1rem; margin-bottom: 0.75rem; color: var(--color-dark); }
.faq-item p { font-size: 0.9rem; color: var(--color-gray); line-height: 1.6; }
@media (max-width: 1023px) {
  .process-grid { grid-template-columns: 1fr 1fr; }
}
@media (max-width: 767px) {
  .why-grid { grid-template-columns: 1fr; }
}
@media (max-width: 480px) {
  .process-grid { grid-template-columns: 1fr; }
}
</style>

<?php echo breadcrumb_nav($breadcrumbs); ?>

<!-- Hero — CTA #1 -->
<section class="hero hero-inner" style="background-image: url('https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470039241_122125599908552346_4973791851142167865_n.jpg');">
  <div class="hero-overlay"></div>
  <div class="container">
    <div class="hero-content">
      <span class="hero-eyebrow">Kamps Professional Roofing</span>
      <h1>Tile Roof Installation Grand Rapids, MI</h1>
      <p class="hero-subtitle">Clay and concrete tile roofing done correctly for Michigan's freeze-thaw climate — structural assessments included, no surprises, 50+ year lifespans.</p>
      <div class="hero-buttons">
        <a href="/contact" class="btn btn-accent btn-lg">Get a Free Estimate</a>
        <?php echo phone_link('btn btn-outline-white btn-lg', 'Call Now'); ?>
      </div>
      <div class="hero-trust">
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg> Licensed &amp; Insured</span>
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg> 30+ Years Experience</span>
        <span class="hero-trust-item"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="20 6 9 17 4 12"></polyline></svg> Free Estimates</span>
      </div>
    </div>
  </div>
</section>

<!-- Service Detail -->
<section style="background: var(--color-light); padding: var(--space-16) 0;">
  <div class="container">
    <div class="about-split" data-animate>
      <div class="about-content">
        <div class="section-header" style="text-align:left; margin-bottom: 2rem;">
          <span class="eyebrow">Tile Roofing in Grand Rapids</span>
          <h2>Tile Roofing Is Practical in Michigan — With the Right Installation</h2>
        </div>
        <p>Clay and concrete tile can last 50-100 years on a West Michigan home — but only when installed correctly for our climate. The biggest failure point with tile in Michigan isn't the tile itself; it's freeze-thaw damage from moisture infiltration when the product or installation isn't specified for northern conditions. Kamps selects only tile products with documented freeze-thaw cycling ratings appropriate for Grand Rapids winters.</p>
        <p>A full tile roof installation in Grand Rapids runs <strong>$15,000-$35,000+</strong> depending on tile type and roof complexity. Clay tile is the premium option — 50-100 years lifespan with color baked in that won't fade. Concrete tile is more affordable at 40-50 years, available in flat, low-profile, and barrel styles. Both weigh 3-4x more than asphalt shingles, which means most homes require structural reinforcement before tile installation can begin.</p>
        <p>Before any number is finalized, Daniel Kamps evaluates the framing — that assessment is included in your estimate, not billed separately. If reinforcement is needed, the scope and cost are defined upfront so there are no change orders mid-project. Tile is less common in West Michigan than shingles or metal, which means most contractors here don't have deep tile experience. Kamps is an exception — the knowledge to specify the right product, prep the structure correctly, and install with methods that account for Michigan's temperature swings.</p>
        <p>Every valley and penetration is flashed with metal, hip and ridge tiles are capped and mortared, and the fastening pattern is engineered for the specific tile profile. No caulk-only details on tile work — ever. The installation quality has to match the quality of the material, or the 50-year promise is just a number on a brochure.</p>
        <p style="font-size: 0.8rem; color: var(--color-gray);">Last Updated: <?php echo date('F Y'); ?></p>
      </div>
      <div class="about-image">
        <picture>
          <img src="https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/photos/1776176914927-470039241_122125599908552346_4973791851142167865_n.jpg" alt="Clay tile roof installation on Grand Rapids Michigan home by Kamps Professional Roofing" width="600" height="450" loading="lazy" style="border-radius: var(--radius-lg); width: 100%; object-fit: cover;">
        </picture>
      </div>
    </div>
  </div>
</section>

<!-- Why Choose Kamps -->
<section style="padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">Why Kamps for Tile</span>
      <h2>Rare Expertise in a Less Common Roofing Material</h2>
    </div>
    <div class="why-grid">
      <div class="why-item" data-animate>
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg>
        </div>
        <div>
          <h3>Structural Assessments Included</h3>
          <p>Most contractors skip this or charge separately. Kamps evaluates framing before quoting — so the estimate you receive accounts for all required work, not just the tile itself.</p>
        </div>
      </div>
      <div class="why-item" data-animate>
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="20 6 9 17 4 12"></polyline></svg>
        </div>
        <div>
          <h3>Michigan Climate Specification</h3>
          <p>Not all tile is rated for freeze-thaw. Kamps specifies products with documented freeze-thaw cycling ratings appropriate for Grand Rapids winters — and installs them with methods that account for thermal movement.</p>
        </div>
      </div>
      <div class="why-item" data-animate>
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="12" y1="1" x2="12" y2="23"></line><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>
        </div>
        <div>
          <h3>Long-Term Value Analysis</h3>
          <p>Tile is more expensive upfront but cheaper per year over its lifespan. Daniel provides the 50-year cost comparison against asphalt so you can make the decision based on real numbers.</p>
        </div>
      </div>
      <div class="why-item" data-animate>
        <div class="why-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>
        </div>
        <div>
          <h3>Precision Installation on Premium Materials</h3>
          <p>Tile is expensive — mistakes are expensive too. Daniel's 30+ years of experience with specialty roofing materials means the installation matches the quality of the product itself.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Mid-page CTA — CTA #2 -->
<div class="cta-banner">
  <div class="container">
    <h2>Is Your Home Ready for a Tile Roof? Find Out Free.</h2>
    <p>Kamps evaluates your framing during the estimate — no separate engineering fee. You get a complete picture before committing to anything.</p>
    <div style="display: flex; gap: 1rem; justify-content: center; flex-wrap: wrap;">
      <a href="/contact" class="btn btn-accent btn-lg">Schedule My Free Assessment</a>
      <?php echo phone_link('btn btn-outline-white btn-lg'); ?>
    </div>
  </div>
</div>

<!-- Process Steps -->
<section style="background: var(--color-light); padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">How It Works</span>
      <h2>Tile Roof Installation: From Assessment to Completion</h2>
    </div>
    <div class="process-grid">
      <div class="process-step" data-animate>
        <div class="process-number">1</div>
        <h3>Structural Assessment</h3>
        <p>The framing is evaluated before any tile is ordered. If reinforcement is needed, the scope and cost are defined upfront — no change orders mid-project.</p>
      </div>
      <div class="process-step" data-animate>
        <div class="process-number">2</div>
        <h3>Tile Selection &amp; Ordering</h3>
        <p>Clay or concrete, style, color, and freeze-thaw rating are confirmed. Only products rated for Michigan's climate are specified — not everything in the catalog qualifies.</p>
      </div>
      <div class="process-step" data-animate>
        <div class="process-number">3</div>
        <h3>Deck Reinforcement &amp; Prep</h3>
        <p>Structural work is completed, old roofing removed, and the deck prepared with appropriate underlayment systems for tile — not standard shingle underlayment.</p>
      </div>
      <div class="process-step" data-animate>
        <div class="process-number">4</div>
        <h3>Tile Install &amp; Ridge Cap</h3>
        <p>Tiles installed with proper fastening pattern, all hip and ridge tiles capped and mortared, every valley and penetration flashed with metal.</p>
      </div>
    </div>
  </div>
</section>

<!-- FAQ -->
<section style="padding: var(--space-16) 0;">
  <div class="container">
    <div class="section-header" data-animate>
      <span class="eyebrow">Frequently Asked Questions</span>
      <h2>What Michigan Homeowners Ask About Tile Roofing</h2>
    </div>
    <div class="faq-grid">
      <div class="faq-item" data-animate>
        <h3>Is tile roofing practical in Michigan?</h3>
        <p>Yes, with proper installation. The key is selecting freeze-thaw resistant tile — not all tile products are rated for Michigan's temperature swings. Kamps specifies products tested for northern climates and installs them with methods that account for thermal movement.</p>
      </div>
      <div class="faq-item" data-animate>
        <h3>How much does a tile roof cost in Grand Rapids?</h3>
        <p>$15,000-$35,000+ depending on tile type and roof complexity. Clay is more expensive than concrete; both require a structural assessment before final pricing. Kamps includes that assessment in your estimate.</p>
      </div>
      <div class="faq-item" data-animate>
        <h3>How long do tile roofs last?</h3>
        <p>Clay tile lasts 50-100 years; concrete tile typically 40-50 years. Both significantly outlast asphalt shingles. Lifespan depends on proper installation, adequate structural support, and correct flashing at all penetrations.</p>
      </div>
    </div>
  </div>
</section>

<!-- Closing CTA — CTA #3 -->
<section class="closing-cta">
  <div class="container">
    <h2>Get a Complete Tile Roof Estimate in Grand Rapids</h2>
    <p>$15,000-$35,000+ installed. Framing evaluation included at no extra charge. Free estimate within 24-48 hours across Grand Rapids and Kent County.</p>
    <div class="btn-row">
      <a href="/contact" class="btn btn-accent btn-lg">Schedule My Free Estimate</a>
      <?php echo phone_link('btn btn-outline-white btn-lg'); ?>
    </div>
  </div>
</section>

<?php include $_SERVER['DOCUMENT_ROOT'] . '/includes/footer.php'; ?>
