<?php
/**
 * footer.php — Kamps Professional Roofing
 * Shared site footer — closes <main>, outputs 4-column footer,
 * back-to-top, mobile CTA bar, and all script tags.
 * Generated by Page One Insights — Phase 2
 *
 * Optional variables (set before include):
 *   $useSwiper      (bool)  Load Swiper.js bundle
 *   $useVanillaTilt (bool)  Load VanillaTilt.js
 */
$useSwiper      ??= false;
$useVanillaTilt ??= false;
?>

  </main><!-- /#main-content -->

  <!-- =========================================================
       SITE FOOTER
       ========================================================= -->
  <footer class="site-footer" role="contentinfo"
          itemscope itemtype="https://schema.org/WPFooter">

    <div class="container">

      <!-- ── 4-Column Footer Grid ─────────────────────────────── -->
      <div class="footer-grid">

        <!-- COL 1 — Company Info & Entity Block ──────────────── -->
        <div class="footer-col">

          <a href="/" class="footer-logo" aria-label="Kamps Professional Roofing — Home">
            <img
              src="https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/logo/1776176882754-461430316_10233986853122130_3081695463203055235_n.jpg"
              alt="Kamps Professional Roofing"
              width="150"
              height="42"
              loading="lazy"
            >
          </a>

          <p class="footer-tagline">
            Covering Grand Rapids homes with three decades of roofing expertise.
            Roof replacement, repairs, gutters, and siding — done right the first time.
          </p>

          <!-- Trust Badges -->
          <div class="footer-trust" aria-label="Trust indicators">
            <span class="trust-badge">
              <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24"
                   fill="none" stroke="currentColor" stroke-width="2.5"
                   stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
              </svg>
              Licensed &amp; Insured
            </span>
            <span class="trust-badge">
              <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24"
                   fill="none" stroke="currentColor" stroke-width="2.5"
                   stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                <circle cx="12" cy="12" r="10"></circle>
                <polyline points="12 6 12 12 16 14"></polyline>
              </svg>
              30+ Years Experience
            </span>
            <span class="trust-badge">
              <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24"
                   fill="none" stroke="currentColor" stroke-width="2.5"
                   stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path>
                <circle cx="12" cy="10" r="3"></circle>
              </svg>
              Grand Rapids, MI
            </span>
          </div>

          <!-- AEO Entity Block with Microdata ───────────────── -->
          <div class="aeo-entity"
               itemscope itemtype="https://schema.org/RoofingContractor">

            <meta itemprop="name"        content="Kamps Professional Roofing">
<?php if (!empty(SITE_PHONE)): ?>
            <meta itemprop="telephone"   content="<?php echo htmlspecialchars(SITE_PHONE); ?>">
<?php endif; ?>
<?php if (!empty(SITE_EMAIL)): ?>
            <meta itemprop="email"       content="<?php echo htmlspecialchars(SITE_EMAIL); ?>">
<?php endif; ?>
            <meta itemprop="url"         content="<?php echo SITE_URL; ?>">
            <meta itemprop="description" content="Kamps Professional Roofing is a roofing company based in Grand Rapids, MI, serving the greater West Michigan area. Led by Daniel Kamps with over three decades of experience, specializing in roof replacement, roof repair, and storm damage restoration.">

            <div itemprop="address"
                 itemscope itemtype="https://schema.org/PostalAddress">
              <meta itemprop="addressLocality" content="Grand Rapids">
              <meta itemprop="addressRegion"   content="MI">
              <meta itemprop="postalCode"      content="49525">
              <meta itemprop="addressCountry"  content="US">
            </div>

            <p class="entity-text">
              <strong>Kamps Professional Roofing</strong> is a roofing company based in
              <span itemprop="areaServed">Grand Rapids, MI</span>, serving the greater
              West Michigan area. Founded with over 30 years of experience, Kamps
              specializes in roof replacement, roof repair, and storm damage restoration.
<?php if (!empty(SITE_PHONE)): ?>
              Contact: <a href="tel:<?php echo preg_replace('/[^0-9+]/', '', SITE_PHONE); ?>"
                          itemprop="telephone"><?php echo htmlspecialchars(SITE_PHONE_DISPLAY); ?></a>
              |
<?php endif; ?>
<?php if (!empty(SITE_EMAIL)): ?>
              <a href="mailto:<?php echo htmlspecialchars(SITE_EMAIL); ?>"
                 itemprop="email"><?php echo htmlspecialchars(SITE_EMAIL); ?></a>
              |
<?php endif; ?>
              <a href="<?php echo SITE_URL; ?>" itemprop="url">kampsprofessionalroofing.com</a>.
              Licensed and insured.
            </p>

          </div><!-- /.aeo-entity -->

        </div><!-- /COL 1 -->


        <!-- COL 2 — Roofing Services ─────────────────────────── -->
        <div class="footer-col">
          <h4>Roofing Services</h4>
          <ul>
            <li><a href="/services/roof-replacement">Roof Replacement</a></li>
            <li><a href="/services/roof-repair">Roof Repair</a></li>
            <li><a href="/services/emergency-roof-repair">Emergency Roof Repair</a></li>
            <li><a href="/services/storm-damage-roof-repair">Storm Damage Repair</a></li>
            <li><a href="/services/roof-inspection">Roof Inspection</a></li>
            <li><a href="/services/roof-maintenance">Roof Maintenance</a></li>
            <li><a href="/services/asphalt-shingle-roofing">Asphalt Shingle Roofing</a></li>
            <li><a href="/services/metal-roofing">Metal Roofing</a></li>
            <li><a href="/services/tile-roof-installation">Tile Roof Installation</a></li>
            <li><a href="/services/slate-roof-installation">Slate Roof Installation</a></li>
            <li><a href="/services/cedar-shake-roofing">Cedar Shake Roofing</a></li>
            <li><a href="/services/insurance-roof-replacement">Insurance Claims Help</a></li>
          </ul>
        </div><!-- /COL 2 -->


        <!-- COL 3 — Siding, Gutters & Service Areas ──────────── -->
        <div class="footer-col">
          <h4>Siding &amp; Gutters</h4>
          <ul>
            <li><a href="/services/siding-installation">Siding Installation</a></li>
            <li><a href="/services/siding-repair">Siding Repair</a></li>
            <li><a href="/services/siding-replacement">Siding Replacement</a></li>
            <li><a href="/services/gutter-installation">Gutter Installation</a></li>
            <li><a href="/services/gutter-repair">Gutter Repair</a></li>
            <li><a href="/services/gutter-replacement">Gutter Replacement</a></li>
            <li><a href="/services/gutter-cleaning">Gutter Cleaning</a></li>
            <li><a href="/services/fence-installation">Fence Installation</a></li>
          </ul>

          <h4 style="margin-top: var(--space-6);">Service Areas</h4>
          <ul>
            <li><a href="/service-areas">Grand Rapids, MI</a></li>
            <li><a href="/service-areas">West Michigan</a></li>
            <li><a href="/service-areas">Kentwood</a></li>
            <li><a href="/service-areas">Wyoming</a></li>
            <li><a href="/service-areas">Grandville</a></li>
            <li><a href="/service-areas">Rockford</a></li>
            <li><a href="/service-areas">Lowell</a></li>
            <li><a href="/service-areas">Comstock Park</a></li>
          </ul>
        </div><!-- /COL 3 -->


        <!-- COL 4 — Contact Info ─────────────────────────────── -->
        <div class="footer-col">
          <h4>Contact Us</h4>

<?php if (!empty(SITE_PHONE)): ?>
          <div class="contact-item">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"
                 fill="none" stroke="currentColor" stroke-width="2"
                 stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
              <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 13a19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 3.6 2.18h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L7.91 9.91a16 16 0 0 0 6 6l.91-.91a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 17z"></path>
            </svg>
            <a href="tel:<?php echo preg_replace('/[^0-9+]/', '', SITE_PHONE); ?>">
              <?php echo htmlspecialchars(SITE_PHONE_DISPLAY); ?>
            </a>
          </div>
<?php endif; ?>

<?php if (!empty(SITE_EMAIL)): ?>
          <div class="contact-item">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"
                 fill="none" stroke="currentColor" stroke-width="2"
                 stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
              <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path>
              <polyline points="22,6 12,13 2,6"></polyline>
            </svg>
            <a href="mailto:<?php echo htmlspecialchars(SITE_EMAIL); ?>">
              <?php echo htmlspecialchars(SITE_EMAIL); ?>
            </a>
          </div>
<?php endif; ?>

          <div class="contact-item">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"
                 fill="none" stroke="currentColor" stroke-width="2"
                 stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
              <path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path>
              <circle cx="12" cy="10" r="3"></circle>
            </svg>
            <span>Grand Rapids, MI 49525</span>
          </div>

          <div class="contact-item">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"
                 fill="none" stroke="currentColor" stroke-width="2"
                 stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
              <circle cx="12" cy="12" r="10"></circle>
              <polyline points="12 6 12 12 16 14"></polyline>
            </svg>
            <span>Mon–Fri: 7am–6pm<br>Sat: 8am–4pm</span>
          </div>

          <div style="margin-top: var(--space-6);">
            <a href="/contact" class="btn btn-accent btn-sm" style="display:inline-flex;">
              Get a Free Estimate
            </a>
          </div>

          <!-- Social Icons -->
          <div class="footer-social" style="margin-top: var(--space-6); display:flex; gap: var(--space-3);">
            <a href="#" aria-label="Kamps Professional Roofing on Facebook"
               class="social-icon" target="_blank" rel="noopener noreferrer">
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
                   fill="currentColor" aria-hidden="true">
                <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path>
              </svg>
            </a>
            <a href="#" aria-label="Kamps Professional Roofing on Instagram"
               class="social-icon" target="_blank" rel="noopener noreferrer">
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
                   fill="none" stroke="currentColor" stroke-width="2"
                   stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>
                <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>
                <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>
              </svg>
            </a>
          </div>

        </div><!-- /COL 4 -->

      </div><!-- /.footer-grid -->


      <!-- ── Footer Bottom Bar ──────────────────────────────────── -->
      <div class="footer-bottom">

        <p>&copy; <?php echo date('Y'); ?> Kamps Professional Roofing. All rights reserved.</p>

        <nav aria-label="Footer legal links">
          <ul style="display:flex; gap: var(--space-4); list-style:none; margin:0; padding:0;">
            <li><a href="/privacy-policy"     style="color:rgba(255,255,255,0.5); font-size:0.8rem;">Privacy Policy</a></li>
            <li><a href="/terms-of-service"   style="color:rgba(255,255,255,0.5); font-size:0.8rem;">Terms of Service</a></li>
            <li><a href="/sitemap"            style="color:rgba(255,255,255,0.5); font-size:0.8rem;">Sitemap</a></li>
          </ul>
        </nav>

        <p class="footer-credit">
          <a href="https://pageoneinsights.com" rel="dofollow" target="_blank"
             aria-label="Website designed and hosted by Page One Insights LLC">
            Web Design &amp; Hosting by Page One Insights, LLC
          </a>
        </p>

      </div><!-- /.footer-bottom -->

    </div><!-- /.container -->

  </footer><!-- /.site-footer -->


  <!-- ── Back-to-Top Button ─────────────────────────────────── -->
  <button class="back-to-top" id="back-to-top"
          aria-label="Scroll back to top of page">
    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24"
         fill="none" stroke="currentColor" stroke-width="2.5"
         stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
      <line x1="12" y1="19" x2="12" y2="5"></line>
      <polyline points="5 12 12 5 19 12"></polyline>
    </svg>
  </button>


  <!-- ── Floating Mobile CTA Bar ───────────────────────────── -->
  <div class="mobile-cta-bar" role="complementary" aria-label="Quick contact options">
    <div style="display:grid; grid-template-columns:1fr 1fr; gap: var(--space-2);">
<?php if (!empty(SITE_PHONE)): ?>
      <a href="tel:<?php echo preg_replace('/[^0-9+]/', '', SITE_PHONE); ?>"
         class="btn btn-outline-white btn-sm" style="justify-content:center;">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"
             fill="none" stroke="currentColor" stroke-width="2.5"
             stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 13a19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 3.6 2.18h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L7.91 9.91a16 16 0 0 0 6 6l.91-.91a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 17z"></path>
        </svg>
        Call Now
      </a>
<?php else: ?>
      <a href="tel:" class="btn btn-outline-white btn-sm" style="justify-content:center;">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24"
             fill="none" stroke="currentColor" stroke-width="2.5"
             stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 13a19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 3.6 2.18h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L7.91 9.91a16 16 0 0 0 6 6l.91-.91a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 17z"></path>
        </svg>
        Call Now
      </a>
<?php endif; ?>
      <a href="/contact" class="btn btn-accent btn-sm" style="justify-content:center;">
        Free Estimate
      </a>
    </div>
  </div><!-- /.mobile-cta-bar -->


  <!-- =========================================================
       SCRIPTS
       ========================================================= -->

  <!-- Lucide Icons (inline SVG rendering) -->
  <script src="https://unpkg.com/lucide@latest/dist/umd/lucide.min.js" defer></script>

  <!-- Swiper.js — conditional ──────────────────────────────── -->
<?php if ($useSwiper): ?>
  <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" defer></script>
<?php endif; ?>

  <!-- VanillaTilt.js — conditional ─────────────────────────── -->
<?php if ($useVanillaTilt): ?>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-tilt/1.8.1/vanilla-tilt.min.js" defer></script>
<?php endif; ?>

  <!-- Site Scripts ─────────────────────────────────────────── -->
  <script src="/assets/js/animations.js" defer></script>
  <script src="/assets/js/effects.js"    defer></script>
  <script src="/assets/js/main.js"       defer></script>

  <!-- Inline init: icons + header scroll + hamburger + back-to-top -->
  <script>
  (function () {
    'use strict';

    /* ── Header scroll behaviour ─────────────────────────────── */
    const header = document.getElementById('site-header');
    if (header) {
      const onScroll = () => {
        header.classList.toggle('scrolled', window.scrollY > 80);
      };
      window.addEventListener('scroll', onScroll, { passive: true });
      onScroll(); // run once on load
    }

    /* ── Hamburger / mobile menu ─────────────────────────────── */
    const hamburger = document.getElementById('hamburger');
    const navMenu   = document.getElementById('nav-menu');
    if (hamburger && navMenu) {
      hamburger.addEventListener('click', function () {
        const isOpen = navMenu.classList.toggle('active');
        hamburger.classList.toggle('active', isOpen);
        hamburger.setAttribute('aria-expanded', String(isOpen));
        hamburger.setAttribute('aria-label', isOpen ? 'Close navigation menu' : 'Open navigation menu');
        document.body.style.overflow = isOpen ? 'hidden' : '';
      });

      // Close on nav link click
      navMenu.querySelectorAll('a').forEach(function (link) {
        link.addEventListener('click', function () {
          navMenu.classList.remove('active');
          hamburger.classList.remove('active');
          hamburger.setAttribute('aria-expanded', 'false');
          hamburger.setAttribute('aria-label', 'Open navigation menu');
          document.body.style.overflow = '';
        });
      });

      // Close on Escape key
      document.addEventListener('keydown', function (e) {
        if (e.key === 'Escape' && navMenu.classList.contains('active')) {
          navMenu.classList.remove('active');
          hamburger.classList.remove('active');
          hamburger.setAttribute('aria-expanded', 'false');
          document.body.style.overflow = '';
          hamburger.focus();
        }
      });
    }

    /* ── Dropdown ARIA: toggle aria-expanded on hover/focus ──── */
    document.querySelectorAll('.nav-dropdown').forEach(function (item) {
      const trigger = item.querySelector('.nav-dropdown-trigger');
      if (!trigger) return;
      item.addEventListener('mouseenter', function () {
        trigger.setAttribute('aria-expanded', 'true');
      });
      item.addEventListener('mouseleave', function () {
        trigger.setAttribute('aria-expanded', 'false');
      });
      trigger.addEventListener('focus', function () {
        trigger.setAttribute('aria-expanded', 'true');
      });
      trigger.addEventListener('blur', function (e) {
        if (!item.contains(e.relatedTarget)) {
          trigger.setAttribute('aria-expanded', 'false');
        }
      });
    });

    /* ── Back-to-top button ──────────────────────────────────── */
    const btt = document.getElementById('back-to-top');
    if (btt) {
      window.addEventListener('scroll', function () {
        btt.classList.toggle('visible', window.scrollY > 300);
      }, { passive: true });
      btt.addEventListener('click', function () {
        window.scrollTo({ top: 0, behavior: 'smooth' });
      });
    }

    /* ── Lucide icon init (runs after deferred script) ───────── */
    window.addEventListener('load', function () {
      if (window.lucide) lucide.createIcons();
    });

  }());
  </script>

</body>
</html>
