<?php
/**
 * functions.php — Kamps Professional Roofing
 * Site-wide helper functions and constants
 * Generated by Page One Insights — Phase 2
 */

// ============================================================
// Site Constants
// ============================================================
define('SITE_NAME',          'Kamps Professional Roofing');
define('SITE_URL',           'https://kampsprofessionalroofing.com');
define('SITE_PHONE',         '');
define('SITE_PHONE_DISPLAY', '');
define('SITE_EMAIL',         '');
define('SITE_ADDRESS',       'Grand Rapids, MI 49525');
define('SITE_CITY',          'Grand Rapids');
define('SITE_STATE',         'MI');
define('SITE_ZIP',           '49525');
define('OWNER_NAME',         'Daniel Kamps');
define('SITE_TAGLINE',       'Covering You with Excellence');
define('FORM_ACTION',        'https://design.pageone.cloud/api/leads/kamps-professional-roofing');
define('LOGO_URL',           'https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/logo/1776176882754-461430316_10233986853122130_3081695463203055235_n.jpg');
define('SITE_INDUSTRY',      'roofing');

// ============================================================
// URL Helpers
// ============================================================

/**
 * Returns an absolute site URL for the given path.
 */
function site_url(string $path = ''): string {
    return SITE_URL . '/' . ltrim($path, '/');
}

/**
 * Converts a service name to a URL-safe slug.
 * "Residential Roof Leak Repair" → "residential-roof-leak-repair"
 */
function service_slug(string $name): string {
    $slug = mb_strtolower(trim($name));
    $slug = preg_replace('/[^a-z0-9\s\-]/', '', $slug);
    $slug = preg_replace('/[\s]+/', '-', $slug);
    return trim($slug, '-');
}

/**
 * Returns the root-relative URL for a service page.
 */
function service_url(string $name): string {
    return '/services/' . service_slug($name);
}

// ============================================================
// Nav / Active State Helpers
// ============================================================

/**
 * Returns 'aria-current="page"' if $slug matches $currentPage.
 */
function aria_current(string $currentPage, string $slug): string {
    return ($currentPage === $slug) ? 'aria-current="page"' : '';
}

/**
 * Returns the CSS class string 'active' if $slug matches $currentPage.
 */
function active_class(string $currentPage, string $slug): string {
    return ($currentPage === $slug) ? 'active' : '';
}

// ============================================================
// Contact Helpers
// ============================================================

/**
 * Returns a <a href="tel:…"> element, or empty string when no phone is set.
 *
 * @param string $class   Optional CSS class attribute value
 * @param string $label   Optional display text (defaults to SITE_PHONE_DISPLAY)
 */
function phone_link(string $class = '', string $label = ''): string {
    if (empty(SITE_PHONE)) return '';
    $display    = $label ?: SITE_PHONE_DISPLAY;
    $digits     = preg_replace('/[^0-9+]/', '', SITE_PHONE);
    $class_attr = $class ? ' class="' . htmlspecialchars($class) . '"' : '';
    return '<a href="tel:' . $digits . '"' . $class_attr . '>'
         . htmlspecialchars($display) . '</a>';
}

/**
 * Returns a <a href="mailto:…"> element, or empty string when no email is set.
 *
 * @param string $class   Optional CSS class attribute value
 * @param string $label   Optional display text (defaults to SITE_EMAIL)
 */
function email_link(string $class = '', string $label = ''): string {
    if (empty(SITE_EMAIL)) return '';
    $display    = $label ?: SITE_EMAIL;
    $class_attr = $class ? ' class="' . htmlspecialchars($class) . '"' : '';
    return '<a href="mailto:' . htmlspecialchars(SITE_EMAIL) . '"' . $class_attr . '>'
         . htmlspecialchars($display) . '</a>';
}

// ============================================================
// Schema Helpers
// ============================================================

/**
 * Builds a BreadcrumbList JSON-LD string.
 *
 * @param array $items  Each item: ['name' => '…', 'url' => '/relative/path']
 */
function breadcrumb_schema(array $items): string {
    $list = [];
    foreach ($items as $i => $item) {
        $list[] = [
            '@type'    => 'ListItem',
            'position' => $i + 1,
            'name'     => $item['name'],
            'item'     => SITE_URL . $item['url'],
        ];
    }
    return json_encode([
        '@context'        => 'https://schema.org',
        '@type'           => 'BreadcrumbList',
        'itemListElement' => $list,
    ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
}

/**
 * Outputs a visible HTML breadcrumb <nav> element.
 *
 * @param array $items  Each item: ['name' => '…', 'url' => '/relative/path']
 *                      The last item is rendered without a link (current page).
 */
function breadcrumb_nav(array $items): string {
    $html = '<nav aria-label="Breadcrumb" class="breadcrumb-nav">'
          . '<ol class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">';
    foreach ($items as $i => $item) {
        $pos    = $i + 1;
        $isLast = ($i === count($items) - 1);
        $html  .= '<li class="breadcrumb-item' . ($isLast ? ' active' : '') . '"'
                . ' itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">'
                . '<meta itemprop="position" content="' . $pos . '">';
        if ($isLast) {
            $html .= '<span itemprop="name">' . htmlspecialchars($item['name']) . '</span>';
        } else {
            $html .= '<a href="' . htmlspecialchars($item['url']) . '" itemprop="item">'
                   . '<span itemprop="name">' . htmlspecialchars($item['name']) . '</span>'
                   . '</a>';
        }
        $html .= '</li>';
    }
    $html .= '</ol></nav>';
    return $html;
}

// ============================================================
// Form Helpers
// ============================================================

/**
 * Outputs the hidden honeypot field that must appear in EVERY contact form.
 * Call inside every <form> to block spam bots.
 *
 * Usage: <?php echo form_honeypot(); ?>
 *   or   <?php form_honeypot_echo(); ?>
 */
function form_honeypot(): string {
    return '<input type="text" name="_honeypot" style="display:none" tabindex="-1" autocomplete="off">';
}

/** Echoes the honeypot field directly (convenience wrapper). */
function form_honeypot_echo(): void {
    echo form_honeypot();
}

/**
 * Returns the standard hidden fields required for every contact form.
 * Includes honeypot + form_action is set via FORM_ACTION constant.
 *
 * @param string $nextUrl  Absolute URL of the thank-you page (e.g. SITE_URL.'/thank-you')
 * @param string $subject  Email subject line sent to the notification endpoint
 */
function form_hidden_fields(string $nextUrl = '', string $subject = ''): string {
    $next    = $nextUrl ?: SITE_URL . '/thank-you';
    $subj    = $subject ?: SITE_NAME . ' — New Website Inquiry';
    $html    = form_honeypot() . "\n";
    $html   .= '<input type="hidden" name="_next"     value="' . htmlspecialchars($next, ENT_QUOTES, 'UTF-8') . '">' . "\n";
    $html   .= '<input type="hidden" name="_subject"  value="' . htmlspecialchars($subj, ENT_QUOTES, 'UTF-8') . '">' . "\n";
    return $html;
}

// ============================================================

/**
 * Returns an AggregateRating schema fragment (JSON-LD) for merge into page schema.
 * Caller is responsible for wrapping in a full schema object.
 *
 * @param float  $rating  Average rating (default 4.9)
 * @param int    $count   Review count (default 87)
 */
function aggregate_rating_schema(float $rating = 4.9, int $count = 87): array {
    return [
        '@type'       => 'AggregateRating',
        'ratingValue' => $rating,
        'reviewCount' => $count,
        'bestRating'  => 5,
        'worstRating' => 1,
    ];
}

/**
 * Builds a Service schema JSON-LD string for an individual service page.
 *
 * @param string $serviceName        Display name of the service
 * @param string $serviceDescription One-paragraph description
 * @param string $pageUrl            Root-relative path (e.g. '/services/roof-repair')
 */
function service_schema(string $serviceName, string $serviceDescription, string $pageUrl): string {
    return json_encode([
        '@context'    => 'https://schema.org',
        '@type'       => 'Service',
        'name'        => $serviceName,
        'description' => $serviceDescription,
        'provider'    => [
            '@type' => 'RoofingContractor',
            'name'  => SITE_NAME,
            'url'   => SITE_URL,
        ],
        'areaServed'  => [
            '@type' => 'City',
            'name'  => SITE_CITY,
            'containedInPlace' => [
                '@type'  => 'State',
                'name'   => 'Michigan',
            ],
        ],
        'url' => SITE_URL . $pageUrl,
    ], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
}
