<?php
/**
 * header.php — Kamps Professional Roofing
 * Shared site header: skip link, glassmorphism navbar, and <main> opener.
 * Generated by Page One Insights — Phase 2
 *
 * Requires: $currentPage (string) set before include.
 * Outputs:  skip-link → <header> → <main id="main-content">
 */
$currentPage ??= '';
?>

  <!-- Skip to Content (Accessibility) ─────────────────────── -->
  <a href="#main-content" class="skip-link">Skip to main content</a>

  <!-- =========================================================
       SITE HEADER — glassmorphism, fixed, scroll-aware
       ========================================================= -->
  <header class="site-header" id="site-header" role="banner">
    <div class="container">
      <div class="header-inner">

        <!-- Logo ─────────────────────────────────────────────── -->
        <a href="/" class="site-logo" aria-label="Kamps Professional Roofing — Return to homepage">
          <img
            src="https://db.pageone.cloud/storage/v1/object/public/client-assets/kamps-professional-roofing/logo/1776176882754-461430316_10233986853122130_3081695463203055235_n.jpg"
            alt="Kamps Professional Roofing logo — Grand Rapids MI roofing contractors"
            width="160"
            height="45"
            loading="eager"
          >
        </a>

        <!-- Desktop Navigation ───────────────────────────────── -->
        <nav aria-label="Main navigation">
          <ul class="nav-links" id="nav-menu" role="list">

            <li>
              <a href="/" <?php echo aria_current($currentPage, 'home'); ?>>Home</a>
            </li>

            <!-- Services mega-dropdown ──────────────────────── -->
            <li class="nav-dropdown">
              <a href="/services"
                 <?php echo aria_current($currentPage, 'services'); ?>
                 aria-haspopup="true"
                 aria-expanded="false"
                 class="nav-dropdown-trigger">
                Services
                <svg class="dropdown-chevron" xmlns="http://www.w3.org/2000/svg" width="12" height="12"
                     viewBox="0 0 24 24" fill="none" stroke="currentColor"
                     stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"
                     aria-hidden="true">
                  <polyline points="6 9 12 15 18 9"></polyline>
                </svg>
              </a>

              <ul class="nav-dropdown-menu" role="menu" aria-label="Services submenu">

                <!-- ── Roofing ── -->
                <li class="nav-dropdown-heading" role="presentation">
                  <span>Roofing</span>
                </li>
                <li role="menuitem">
                  <a href="/services/roof-replacement">Roof Replacement</a>
                </li>
                <li role="menuitem">
                  <a href="/services/roof-repair">Roof Repair</a>
                </li>
                <li role="menuitem">
                  <a href="/services/emergency-roof-repair">Emergency Roof Repair</a>
                </li>
                <li role="menuitem">
                  <a href="/services/storm-damage-roof-repair">Storm Damage Repair</a>
                </li>
                <li role="menuitem">
                  <a href="/services/roof-inspection">Roof Inspection</a>
                </li>
                <li role="menuitem">
                  <a href="/services/metal-roofing">Metal Roofing</a>
                </li>
                <li role="menuitem">
                  <a href="/services/asphalt-shingle-roofing">Asphalt Shingle Roofing</a>
                </li>
                <li role="menuitem">
                  <a href="/services/insurance-roof-replacement">Insurance Claims</a>
                </li>

                <!-- ── Gutters & Siding ── -->
                <li class="nav-dropdown-heading" role="presentation">
                  <span>Gutters &amp; Siding</span>
                </li>
                <li role="menuitem">
                  <a href="/services/gutter-installation">Gutter Installation</a>
                </li>
                <li role="menuitem">
                  <a href="/services/gutter-repair">Gutter Repair</a>
                </li>
                <li role="menuitem">
                  <a href="/services/siding-installation">Siding Installation</a>
                </li>
                <li role="menuitem">
                  <a href="/services/siding-repair">Siding Repair</a>
                </li>

                <li class="nav-dropdown-divider" role="separator"></li>
                <li role="menuitem">
                  <a href="/services" class="nav-dropdown-all">
                    View All Services
                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12"
                         viewBox="0 0 24 24" fill="none" stroke="currentColor"
                         stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"
                         aria-hidden="true">
                      <line x1="5" y1="12" x2="19" y2="12"></line>
                      <polyline points="12 5 19 12 12 19"></polyline>
                    </svg>
                  </a>
                </li>

              </ul>
            </li><!-- /services dropdown -->

            <li>
              <a href="/about" <?php echo aria_current($currentPage, 'about'); ?>>About</a>
            </li>

            <li>
              <a href="/service-areas" <?php echo aria_current($currentPage, 'service-areas'); ?>>
                Service Areas
              </a>
            </li>

            <li>
              <a href="/contact" <?php echo aria_current($currentPage, 'contact'); ?>>Contact</a>
            </li>

          </ul>
        </nav>

        <!-- Desktop CTA ──────────────────────────────────────── -->
        <div class="header-cta">
<?php if (!empty(SITE_PHONE)): ?>
          <a href="tel:<?php echo preg_replace('/[^0-9+]/', '', SITE_PHONE); ?>"
             class="header-phone">
            <?php echo htmlspecialchars(SITE_PHONE_DISPLAY); ?>
          </a>
<?php endif; ?>
          <a href="/contact" class="btn btn-accent btn-sm">Free Estimate</a>
        </div>

        <!-- Mobile Hamburger ─────────────────────────────────── -->
        <button class="hamburger"
                id="hamburger"
                aria-label="Open navigation menu"
                aria-expanded="false"
                aria-controls="nav-menu">
          <span></span>
          <span></span>
          <span></span>
        </button>

      </div><!-- /.header-inner -->
    </div><!-- /.container -->
  </header><!-- /.site-header -->

  <!-- =========================================================
       MAIN CONTENT
       ========================================================= -->
  <main id="main-content" tabindex="-1">

  <style>
    /* ── Header: additional styles not in framework.css ─────── */

    /* Dropdown chevron rotates on hover */
    .nav-dropdown:hover .dropdown-chevron,
    .nav-dropdown-trigger[aria-expanded="true"] .dropdown-chevron {
      transform: rotate(180deg);
    }
    .dropdown-chevron {
      display: inline-block;
      vertical-align: middle;
      margin-left: 3px;
      transition: transform var(--transition-fast);
      flex-shrink: 0;
    }

    /* Dropdown section headings */
    .nav-dropdown-heading {
      padding: 0.5rem 1rem 0.25rem;
      pointer-events: none;
    }
    .nav-dropdown-heading span {
      font-family: var(--font-heading);
      font-size: 0.65rem;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 1.5px;
      color: var(--color-gray);
      display: block;
    }

    /* Dropdown divider */
    .nav-dropdown-divider {
      height: 1px;
      background: var(--color-gray-light);
      margin: 0.25rem 1rem;
      list-style: none;
    }

    /* "View All" accent link */
    .nav-dropdown-all {
      color: var(--color-accent) !important;
      font-weight: 600 !important;
      display: flex !important;
      align-items: center;
      gap: 4px;
    }
    .nav-dropdown-all:hover {
      background: rgba(6, 182, 212, 0.08) !important;
    }

    /* Desktop phone in header */
    .header-phone {
      color: var(--color-primary);
      font-family: var(--font-heading);
      font-size: var(--font-size-sm);
      font-weight: 600;
      margin-right: var(--space-4);
      white-space: nowrap;
    }
    .header-phone:hover { color: var(--color-accent); }

    /* Mobile menu: expand dropdown items inline ──────────────── */
    @media (max-width: 768px) {
      .nav-dropdown-trigger .dropdown-chevron { display: none; }
      .nav-dropdown-menu {
        position: static !important;
        opacity: 1 !important;
        visibility: visible !important;
        transform: none !important;
        background: transparent !important;
        box-shadow: none !important;
        padding: 0 !important;
        min-width: 0 !important;
        border-top: 1px solid rgba(255,255,255,0.1);
        margin-top: var(--space-2);
      }
      .nav-dropdown-heading { display: none; }
      .nav-dropdown-divider { display: none; }
      .nav-dropdown-menu a {
        color: rgba(255,255,255,0.75) !important;
        font-size: var(--font-size-base) !important;
        padding: var(--space-2) var(--space-4) !important;
      }
      .nav-dropdown-menu a:hover {
        background: rgba(255,255,255,0.1) !important;
        color: var(--color-white) !important;
      }
      .nav-dropdown-all {
        color: var(--color-accent) !important;
      }
    }
  </style>
