<?php
/**
 * head.php — Kamps Professional Roofing
 * Shared <head> include — outputs DOCTYPE through <body> opening tag.
 * Generated by Page One Insights — Phase 2
 *
 * Variables to set BEFORE including this file:
 * -----------------------------------------------
 * Required:
 *   $pageTitle        (string)  Full page title, 50–60 chars
 *   $pageDescription  (string)  Meta description, 140–155 chars
 *   $pageKeywords     (string)  Comma-separated keyword list
 *   $canonicalUrl     (string)  Absolute canonical URL
 *   $ogImage          (string)  Absolute OG image URL (1200×630 ideal)
 *   $currentPage      (string)  Page slug — used by header.php for active state
 *   $schemaMarkup     (string)  Page-specific JSON-LD (raw JSON string or '')
 *
 * Optional:
 *   $heroImage        (string)  Absolute URL — triggers <link rel="preload"> for hero bg
 *   $useSwiper        (bool)    Load Swiper CSS in <head>
 *   $bodyClass        (string)  Extra classes on <body>
 */

require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/functions.php';

// ── Defaults ──────────────────────────────────────────────────────────────────
$pageTitle       ??= SITE_NAME . ' | Roofing Contractors Grand Rapids, MI';
$pageDescription ??= 'Kamps Professional Roofing provides roof replacement, roof repair, storm damage restoration, gutters, and siding in Grand Rapids, MI. Led by Daniel Kamps with 30+ years of experience. Call for a free estimate.';
$pageKeywords    ??= 'roofing grand rapids mi, roof repair grand rapids, roof replacement grand rapids mi, gutter installation grand rapids, siding contractors grand rapids';
$canonicalUrl    ??= SITE_URL;
$ogImage         ??= LOGO_URL;
$currentPage     ??= '';
$schemaMarkup    ??= '';
$heroImage       ??= '';
$useSwiper       ??= false;
$bodyClass       ??= '';

$isHomepage = ($currentPage === 'home');
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Primary SEO ──────────────────────────────────────────── -->
  <title><?php echo htmlspecialchars($pageTitle, ENT_QUOTES, 'UTF-8'); ?></title>
  <meta name="description" content="<?php echo htmlspecialchars($pageDescription, ENT_QUOTES, 'UTF-8'); ?>">
  <meta name="keywords"    content="<?php echo htmlspecialchars($pageKeywords,    ENT_QUOTES, 'UTF-8'); ?>">
  <link rel="canonical"    href="<?php echo htmlspecialchars($canonicalUrl,       ENT_QUOTES, 'UTF-8'); ?>">
  <meta name="robots"      content="index, follow">
  <meta name="author"      content="<?php echo htmlspecialchars(SITE_NAME, ENT_QUOTES, 'UTF-8'); ?>">

  <!-- Open Graph ───────────────────────────────────────────── -->
  <meta property="og:type"        content="website">
  <meta property="og:url"         content="<?php echo htmlspecialchars($canonicalUrl, ENT_QUOTES, 'UTF-8'); ?>">
  <meta property="og:title"       content="<?php echo htmlspecialchars($pageTitle,    ENT_QUOTES, 'UTF-8'); ?>">
  <meta property="og:description" content="<?php echo htmlspecialchars($pageDescription, ENT_QUOTES, 'UTF-8'); ?>">
  <meta property="og:image"       content="<?php echo htmlspecialchars($ogImage, ENT_QUOTES, 'UTF-8'); ?>">
  <meta property="og:image:width"  content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:site_name"   content="<?php echo htmlspecialchars(SITE_NAME, ENT_QUOTES, 'UTF-8'); ?>">
  <meta property="og:locale"      content="en_US">

  <!-- Twitter Card ─────────────────────────────────────────── -->
  <meta name="twitter:card"        content="summary_large_image">
  <meta name="twitter:title"       content="<?php echo htmlspecialchars($pageTitle,       ENT_QUOTES, 'UTF-8'); ?>">
  <meta name="twitter:description" content="<?php echo htmlspecialchars($pageDescription, ENT_QUOTES, 'UTF-8'); ?>">
  <meta name="twitter:image"       content="<?php echo htmlspecialchars($ogImage,         ENT_QUOTES, 'UTF-8'); ?>">

  <!-- Favicon ──────────────────────────────────────────────── -->
  <link rel="icon"             type="image/x-icon"    href="/assets/images/favicon.ico">
  <link rel="icon"             type="image/png" sizes="32x32" href="/assets/images/favicon-32x32.png">
  <link rel="icon"             type="image/png" sizes="16x16" href="/assets/images/favicon-16x16.png">
  <link rel="apple-touch-icon" sizes="180x180"        href="/assets/images/apple-touch-icon.png">
  <meta name="theme-color" content="#1a2b3c">

  <!-- Google Fonts — preconnect ────────────────────────────── -->
  <link rel="preconnect"   href="https://fonts.googleapis.com">
  <link rel="preconnect"   href="https://fonts.gstatic.com" crossorigin>
  <link rel="dns-prefetch" href="https://fonts.googleapis.com">
  <link rel="dns-prefetch" href="https://fonts.gstatic.com">

  <!-- Preload heading font subset (Montserrat 700) ─────────── -->
  <link rel="preload" as="style"
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700;800&family=Open+Sans:wght@400;500;600&display=swap">

  <!-- Google Fonts ─────────────────────────────────────────── -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800&family=Open+Sans:wght@400;500;600&display=swap">

  <!-- Swiper CSS — conditional ─────────────────────────────── -->
<?php if ($useSwiper): ?>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css">
<?php endif; ?>

  <!-- Hero image preload — conditional ─────────────────────── -->
<?php if (!empty($heroImage)): ?>
  <link rel="preload" as="image" href="<?php echo htmlspecialchars($heroImage, ENT_QUOTES, 'UTF-8'); ?>">
<?php endif; ?>

  <!-- Stylesheet ───────────────────────────────────────────── -->
  <link rel="stylesheet" href="/assets/css/framework.css">

  <!-- Google Analytics 4 — replace GA_MEASUREMENT_ID ──────── -->
  <!--
  <script async src="https://www.googletagmanager.com/gtag/js?id=GA_MEASUREMENT_ID"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){ dataLayer.push(arguments); }
    gtag('js', new Date());
    gtag('config', 'GA_MEASUREMENT_ID');
  </script>
  -->

<?php if ($isHomepage): ?>
  <!-- Google Search Console — replace token value ──────────── -->
  <!-- <meta name="google-site-verification" content="REPLACE_WITH_GSC_TOKEN"> -->
<?php endif; ?>

  <!-- Base LocalBusiness / RoofingContractor Schema ────────── -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "RoofingContractor",
    "@id": "<?php echo SITE_URL; ?>/#business",
    "name": "<?php echo SITE_NAME; ?>",
    "description": "Kamps Professional Roofing is led by Daniel Kamps, who brings over three decades of dedicated roofing experience to Grand Rapids, MI. We specialize in roof replacement, roof repair, storm damage restoration, gutter installation, and siding services across West Michigan.",
    "url": "<?php echo SITE_URL; ?>",<?php if (!empty(SITE_PHONE)): ?>
    "telephone": "<?php echo htmlspecialchars(SITE_PHONE); ?>",<?php endif; ?><?php if (!empty(SITE_EMAIL)): ?>
    "email": "<?php echo htmlspecialchars(SITE_EMAIL); ?>",<?php endif; ?>
    "address": {
      "@type": "PostalAddress",
      "addressLocality": "<?php echo SITE_CITY; ?>",
      "addressRegion": "<?php echo SITE_STATE; ?>",
      "postalCode": "<?php echo SITE_ZIP; ?>",
      "addressCountry": "US"
    },
    "geo": {
      "@type": "GeoCoordinates",
      "latitude": 43.0642,
      "longitude": -85.6468
    },
    "areaServed": {
      "@type": "GeoCircle",
      "geoMidpoint": {
        "@type": "GeoCoordinates",
        "latitude": 43.0642,
        "longitude": -85.6468
      },
      "geoRadius": "100000"
    },
    "founder": {
      "@type": "Person",
      "name": "Daniel Kamps"
    },
    "knowsAbout": [
      "Roof Replacement", "Roof Repair", "Emergency Roof Repair",
      "Storm Damage Roof Repair", "Roof Inspection", "Metal Roofing",
      "Asphalt Shingle Roofing", "Gutter Installation", "Siding Installation",
      "Insurance Roof Replacement"
    ],
    "priceRange": "$$",
    "currenciesAccepted": "USD",
    "paymentAccepted": "Cash, Check, Credit Card, Financing",
    "logo": {
      "@type": "ImageObject",
      "url": "<?php echo LOGO_URL; ?>"
    },
    "image": "<?php echo LOGO_URL; ?>",
    "sameAs": []
  }
  </script>

<?php if ($isHomepage): ?>
  <!-- WebSite + SearchAction Schema (homepage only) ────────── -->
  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "name": "<?php echo SITE_NAME; ?>",
    "url": "<?php echo SITE_URL; ?>",
    "potentialAction": {
      "@type": "SearchAction",
      "target": {
        "@type": "EntryPoint",
        "urlTemplate": "<?php echo SITE_URL; ?>/?s={search_term_string}"
      },
      "query-input": "required name=search_term_string"
    }
  }
  </script>
<?php endif; ?>

<?php if (!empty($schemaMarkup)): ?>
  <!-- Page-specific Schema ─────────────────────────────────── -->
  <script type="application/ld+json">
  <?php echo $schemaMarkup; ?>
  </script>
<?php endif; ?>

</head>
<body<?php echo $bodyClass ? ' class="' . htmlspecialchars($bodyClass, ENT_QUOTES, 'UTF-8') . '"' : ''; ?>>
